### ISSUE TITLE
Contribution: high quality "Ranger Station" icon

### ISSUE THREAD

**Issue by brycenesbitt** [mapbox/maki#103]
Here's a CC compatible very high quality Ranger Station icon:
http://wiki.openstreetmap.org/w/index.php?title=File:NPS_ranger_station.svg&page=1
Could you add this?

iD has the matching preset, JOSM and cartocss pull requests are in.

**Comment by brycenesbitt** [comment]
amenity=ranger_station

**Comment by samanpwbb** [comment]
Fixed in upcoming version of maki: https://github.com/mapbox/maki-2/pull/50
