### ISSUE TITLE
Contribution: "aed" icon (Standardized Public Automated External Defibrillator Symbol)

### ISSUE THREAD

**Issue by brycenesbitt** [mapbox/maki#104]
An Automated External Defibrillator (aed) is supplied in public areas, for use in case of heart attack. There's a standard symbol meant to make them easier to identify.  Here's a good version of that:
http://josm.openstreetmap.de/attachment/ticket/8849/aed.2.svg
See:
http://josm.openstreetmap.de/ticket/8849

**Comment by aparlato** [comment]
This was done.
