### ISSUE TITLE
New Icons (mostly shops)

### ISSUE THREAD

**Issue by a-di-na** [mapbox/maki#110]
Hello, 
I think we need some more icons for shops, e.g. 
- [ ] shop=furniture 
- [x] shop=hairdresser 
- [x] shop=hardware 
- [x] shop=laundry 
- [ ] shop=kiosk 
- [x] shop=optician 
- [x] shop=shoes 
- [ ] shop=chemist 
- [ ] shop=stationery 
- [ ] shop=video 
- [ ] shop=second_hand 
- [x] shop=photo 
- [ ] shop=deli 
- [x] shop=confectionery
- [ ] shop=beauty
- [x] shop=jewelry 
- [x] shop=gift
- [ ] shop=toys
- [x] shop=travel_agency
- [ ] shop=outdoor
- [ ] shop=fabric 
- [ ] shop=medical_supply (maybe "disability" works here?)
- [ ] shop=hearing_aids 

I will try to add some - would be happy if someone wants to help. :)

**Comment by tristen** [comment]
Closing. Revised the checklist and many are addressed. Please re-open as separate icon asks if these are still required.
