### ISSUE TITLE
render.sh errors

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki#121]
I get the following errors (below) when I run render.sh. Is this an issue?

    Nickis-MacBook-Pro:maki nickidlugash$ ./render.sh
    montage: unable to read font `/usr/local/share/ghostscript/fonts/n019003l.pfb' @ error/annotate.c/RenderFreetype/1126.
    montage: Postscript delegate failed `/var/tmp/magick-15056sKa7XZA6Je1F': No such file or directory @ error/ps.c/ReadPSImage/837.
    montage: unable to read font `/usr/local/share/ghostscript/fonts/n019003l.pfb' @ error/annotate.c/RenderFreetype/1126.
    montage: Postscript delegate failed `/var/tmp/magick-15071dNbebxohg5SC': No such file or directory @ error/ps.c/ReadPSImage/837.

**Comment by martinburch** [comment]
Try installing ghostscript (with e.g. `brew install ghostscript`)
ImageMagick (required by maki) requires ghostscript for some functions.
