### ISSUE TITLE
Recycling icon

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/maki#152]
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling

**Comment by bhousel** [comment]
"I'm sure there will eventually be a recycling icon.." -- @aaronlidman, 2013

https://github.com/openstreetmap/iD/blame/6b8add7fe7f4072fd8b3bbca1a3eee66b79d0b6b/data/presets/presets/amenity/recycling.json#L2

**Comment by aaronlidman** [comment]
:grimacing:

**Comment by gravitylow** [comment]
Would also love to see this.

**Comment by dasulit** [comment]
https://github.com/mapbox/maki/pull/298 👀
