### ISSUE TITLE
Religious-group icons request.

### ISSUE THREAD

**Issue by lunardog** [mapbox/maki#157]
As a humble request, I would appreciate icons for two religious sites: Buddhist and Shinto. A Buddhist temple is often represented as a Buddha statue or 8-spoked wheel. A Shinto shrine is tough, sometimes marked as the reverse svastika. A tori gate should be clear enough.

I'm building a hiking course map for Japan, temples and shrines are quite important. Churches and synagogues don't exist.

**Comment by friedbunny** [comment]
Bumping this request for Japan-specific religious symbols.

Here are the rough glyphs ([SVGs here](http://en.wikipedia.org/wiki/Japanese_map_symbols)) and how Apple renders them:
![japan_temples_shrines](https://cloud.githubusercontent.com/assets/1198851/7671478/c314355c-fc86-11e4-9f2d-bc9361e5b4fa.png)

Top: Buddhist temples (*manji*, swastika)
Bottom: Shinto shrines (*torii*, gate)

**Comment by nadsumatal** [comment]
Thank you!

**Comment by friedbunny** [comment]
Not ready to PR yet, but [I've been working on `religious-buddhist`](https://github.com/mapbox/maki/compare/mb-pages...friedbunny:157-japan-religious). Smallest size needs work, then I'll move on to `religious-shinto`.
