### ISSUE TITLE
Cat icon

### ISSUE THREAD

**Issue by heatherrudow** [mapbox/maki#163]
I'm working on a Very Important Project and I need a cat icon.

**Comment by heatherrudow** [comment]
All I want for my birthday is a cat icon in Maki,

**Comment by incanus** [comment]
![jterhorst_2014-aug-25](https://cloud.githubusercontent.com/assets/17722/6068907/e2d08504-ad34-11e4-9752-95cbfb693689.jpg)

**Comment by tristen** [comment]
![enhanced-2477-1396642696-6](https://cloud.githubusercontent.com/assets/61150/6069017/fd49499c-ad4e-11e4-8771-97ae683addcc.jpg)

**Comment by geografa** [comment]
Someone needs to do this meow.

**Comment by ian29** [comment]
cat agree more

**Comment by tristen** [comment]
mew too

**Comment by dnomadb** [comment]
you gotta be kitten me

**Comment by mwanee** [comment]
purrty please

**Comment by bsudekum** [comment]
Stop giving me so much cattitude and make the dang icon.

**Comment by tmcw** [comment]
PRRR requests accepted

**Comment by incanus** [comment]
![bsqngkqcqaaowle jpg-large](https://cloud.githubusercontent.com/assets/17722/6863160/aecddc9c-d409-11e4-8c91-7742ca6bc832.jpg)

_Son, we need to talk._

**Comment by heatherrudow** [comment]
![](http://themanwebsite.weebly.com/uploads/8/7/4/2/8742399/5998140.jpg)

**Comment by freenerd** [comment]
Next steps:

- [ ] Start crowdfunding campaign to acquire lump sum of money
- [ ] Throw lump sum of money at design agency to create cat icon
- [ ] Profit

**Comment by heatherrudow** [comment]
Can someone start a gofundme?

**Comment by freenerd** [comment]
:cat: :no_entry_sign: :sob:

**Comment by heatherrudow** [comment]
It should be noted that Maki designer and cat dad @samanpwbb is currently nursing son back to health from a double ear and upper respiratory infection. 

Think about the children. #prayforCyrus #catmakiorbust 
![fullsizerender](https://cloud.githubusercontent.com/assets/6133528/10291453/d9ae562a-6b77-11e5-99a0-36026a67919b.jpg)

**Comment by incanus** [comment]
![sad2](https://cloud.githubusercontent.com/assets/17722/10291527/2805463a-6b5f-11e5-9eec-03cf0fcd00a4.jpg)

**Comment by planemad** [comment]
![](http://wallpaperhdbase.com/wp-content/gallery/sad-cat-pictures/sad_cat.jpg)

**Comment by heatherrudow** [comment]
Rumor has it that a soon-to-be hired designer could get to the bottom of this Very Important Issue. 

![](http://media.giphy.com/media/m7ZFt0RdB7Pz2/giphy.gif)

**Comment by incanus** [comment]
![bsqngkqcqaaowle jpg-large](https://cloud.githubusercontent.com/assets/17722/10488611/58f9b262-724e-11e5-8775-1c2197f8cb5a.jpg)

_I'll need this on my desk by Monday._

**Comment by tristen** [comment]
_After trying on my Halloween costume and learning the news this might happen..._

![bee-costume-cat](https://cloud.githubusercontent.com/assets/61150/10489328/a5a190f0-726a-11e5-83f2-e98327554107.gif)

**Comment by heatherrudow** [comment]
Did you know there is still no cat icon in maki

**Comment by andreasviglakis** [comment]
> Did you know there is still no cat icon in maki

woah if true

**Comment by tristen** [comment]
Claw-ful :(

**Comment by samanpwbb** [comment]
[This is an SVG](https://www.mapbox.com/maki-icons/images/contributing.svg):

![screen shot 2016-12-02 at 4 41 32 pm](https://cloud.githubusercontent.com/assets/108094/20851368/18b47992-b8ae-11e6-820f-216a23b61eb3.png)

**Comment by bsudekum** [comment]
@samanpwbb thanks for pointing out that is an SVG. Is it a cat though? No. Please fix.

**Comment by dnomadb** [comment]
I'm feline pretty bad about this

**Comment by samanpwbb** [comment]
- There is a cat icon inside the svg, conveniently located right next to instructions for how to contribute to maki.

**Comment by bhousel** [comment]
Looks like a pig to me.  A pig is not a cat.

**Comment by stepankuzmin** [comment]
![14798255645810](https://cloud.githubusercontent.com/assets/533564/20866310/990ca9dc-ba3b-11e6-9485-8202260acbc5.png)

You have to be kitten me!

**Comment by incanus** [comment]
![bwebster_2014-nov-19](https://cloud.githubusercontent.com/assets/17722/20949022/0cc08b5a-bbcc-11e6-8a47-c0f4401c96a2.jpg)

**Comment by alinapaz** [comment]
![cnqazroueaaczux](https://cloud.githubusercontent.com/assets/1594300/20949310/865bf1c4-bbcd-11e6-8975-822019a0f6da.jpg)

plz?

**Comment by todrobbins** [comment]
HAS 🐈 NOW?

**Comment by pratikyadav** [comment]
![1hkv18](https://cloud.githubusercontent.com/assets/12744420/21923979/f3a6df40-d99c-11e6-8d13-dd5bcdb86fea.jpg)

**Comment by heatherrudow** [comment]
bump this issue please 

![](https://catmacros.files.wordpress.com/2010/06/bump_kitty.jpg)

**Comment by incanus** [comment]
that cat nose what's up

**Comment by perrygeo** [comment]
We've been moving fast on this. Almost too fast.

![4dsv0jh](https://cloud.githubusercontent.com/assets/1151287/21948679/03ba32f8-d9c3-11e6-809a-2e22aabb6aac.gif)

I think we should paws and consider our design goals here.

**Comment by freenerd** [comment]
![cat-with-question-mark](https://user-images.githubusercontent.com/25713/47109735-06840500-d21d-11e8-9c6a-f81877a10c19.jpg)

**Comment by alinapaz** [comment]
pretty kitty please?

![lala-11272-071](https://user-images.githubusercontent.com/1594300/51877971-e63b0a80-2322-11e9-9916-f8bcfc1e094e.jpg)

**Comment by heatherrudow** [comment]
<3!!!

**Comment by heatherrudow** [comment]
I heard that @samanpwbb has some free time to work on this issue.
![istockphoto-530829594-612x612](https://user-images.githubusercontent.com/6133528/51935285-6b253300-23ba-11e9-97c9-c81b6c8c08de.jpg)

**Comment by bhousel** [comment]
I've been using [FontAwesome's cat icon](https://fontawesome.com/icons/cat?style=solid) as a tempurrary workaround.

<img width="600" alt="screenshot 2019-01-29 14 57 15" src="https://user-images.githubusercontent.com/38784/51936582-869e3700-23d6-11e9-87b7-bd12eabdf3dc.png">

**Comment by kkaefer** [comment]
+1 \*bump\*

**Comment by incanus** [comment]
\*bump\* 

![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2Fxu3nTl5OdCuqs%2Fgiphy.gif&f=1)

**Comment by christoph-buente** [comment]
@kkaefer After all those years, i don't think it's ever gonna happen.

**Comment by heatherrudow** [comment]
[image: Cat Fuck This GIF]

**Comment by kkaefer** [comment]
I can't believe this is still open after 6 years!! When will it be available in the enterprise version of the icon set?

**Comment by tristen** [comment]
> When will it be available in the enterprise version of the icon set?

Subscribe

**Comment by heatherrudow** [comment]
Very important question. I'd like to speak to the manager, please. @samanpwbb??

**Comment by christoph-buente** [comment]
> I can't believe this is still open after 6 years!! When will it be available in the enterprise version of the icon set?

Thanks @kkaefer for taking action here. I gave up hope on this years ago and watch kitten videos on youtube instead.

**Comment by incanus** [comment]
![](http://media.mnn.com/assets/images/2015/09/polydactyl-cat.jpg.838x0_q80.jpg)

**Comment by elifitch** [comment]
With the advent of Style Components, do we feel that this is something we have room for on the roadmap? cc @mapbox/map-design-team @heatherrudow

**Comment by incanus** [comment]
I'm always in favor of harnessing any improvements to Mapbox <em>Mew</em>dio. 🐾

**Comment by vknoppkewetzel** [comment]
me-ohw-mg

**Comment by pratikyadav** [comment]
Cats are excited about this. 

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/12744420/102141057-160b3280-3e15-11eb-9c0e-08d384146fa9.gif)

**Comment by kkaefer** [comment]
I’m hearing that this has finally been promoted to P0, so I’m keeping my paws crossed!

**Comment by heatherrudow** [comment]
![tenor](https://user-images.githubusercontent.com/6133528/107676584-27728e80-6c4e-11eb-9543-1bc40a9a6cc1.gif)

**Comment by marenab** [comment]
The Board is in favor of promoting this issue to level Purr0
![cat-meeting](https://user-images.githubusercontent.com/29718272/108261750-e3353180-7118-11eb-8bb3-bbad28698ad0.gif)

**Comment by tristen** [comment]
Friends,

We have a [cat icon](https://github.com/mapbox/maki/blob/main/icons/animal-shelter.svg) and it's purr-fect.

**Comment by heatherrudow** [comment]
If a cat were as old as this issue, they would be ~50 in human years.

**Comment by incanus** [comment]
![external-content duckduckgo](https://user-images.githubusercontent.com/17722/135135352-bd0984d2-9b36-43c7-91d8-067ec0eb1697.jpg)

_They should have sent a poet._
