### ISSUE TITLE
RFC Doctor icon.

### ISSUE THREAD

**Issue by xorgy** [mapbox/maki#167]
Doctor is a difficult thing to express, I could use just a stethoscope, but I'm not sure that would be correct enough. There's also the Rod of Asclepius, but that is used here for hospitals as well, so I'm also unsure about that.

Here's what I have.

[![doctor-24](http://magnifi.ca/photos/doctor-24.png)](http://magnifi.ca/photos/doctor-24.svg)

**Comment by nickidlugash** [comment]
Done in https://github.com/mapbox/maki-2
