### ISSUE TITLE
Request Hops Symbol

### ISSUE THREAD

**Issue by akatie** [mapbox/maki#168]
I request a hops symbol to denote hopyard and/or brewery/brewpub

Maybe something similar to:

http://www.iconsdb.com/custom-color/hops-icon.html

**Comment by tristen** [comment]
Closing as stale. This also seems pretty niche for Maki. [`beer`](https://github.com/mapbox/maki/blob/master/icons/beer-15.svg) is a generic alternative. Hops have a resemblance to pine cones making them less legible to denote brewery (breweries also may or may not use hops).
