### ISSUE TITLE
Veterinary icon

### ISSUE THREAD

**Issue by dkniffin** [mapbox/maki#171]
One good option for this one are the "snake/cane symbol" (don't know the right name for this; the one used for doctors) with a V over it (http://www.clarksvilleanimalcontrol.com/images/icon_vet.gif).

Another might be a red cross with a paw on it, but I think I heard we're not actually supposed to use the cross (something to do with the geneva convention or something)

**Comment by nickidlugash** [comment]
Done in https://github.com/mapbox/maki-2
