### ISSUE TITLE
How to programmatically access SVG inline styles?

### ISSUE THREAD

**Issue by TehNrd** [mapbox/maki#183]
I'm curious if there is a reliable way to systematically access/modify the inline styles for the SVG icons. Specifically the color and the single pixel border around the icon.

For example, you'll notice on this Mapbox marker they have modified the outside border to contrast with the pin color, http://api.tiles.mapbox.com/v3/marker/pin-l-car+f44@2x.png . I am trying to do something similar but I don't see away to explicitly locate the correct SVG elements with consistent parameters. Something like id="border" id="icon".

Maybe someone from Mapbox could shed some light on how they accomplished this with their markers API?

Apologies if this is not the correct place for this type of question.

**Comment by samanpwbb** [comment]
See https://github.com/mapbox/maki-chef/
