### ISSUE TITLE
Information icon (i)

### ISSUE THREAD

**Issue by MateoV** [mapbox/maki#184]
This is in the [backlog](https://github.com/mapbox/maki/wiki/Maki-Backlog) as `tourism=information`, but calling it out because I think it deserves a high priority. Would be great to have on "outdoors" maps ;)

![openstreetmap relation_ london 65606](https://cloud.githubusercontent.com/assets/843058/3125106/2490319a-e785-11e3-9687-eda3ac7ff5c4.jpg)

**Comment by samanpwbb** [comment]
This exists, see the icon called `information`.
