### ISSUE TITLE
Add support for Bower

### ISSUE THREAD

**Issue by slavafomin** [mapbox/maki#203]
Hello!

Thank you for this great library.

However, could you please add support for *Bower*? Right now I see no other way to use it in my project, cause I'm including all dependencies via *Bower*.

**Comment by mnquintana** [comment]
I have an open PR for exactly this: #198 

Hopefully they take a look at it soon!

**Comment by tmcw** [comment]
We're happy to support installing with npm, download, or directly from GitHub with bower:

    bower install mapbox/maki
