### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by andreasviglakis** [mapbox/maki#209]
Received the following error while running `dev-render.sh`

![](https://slack-files.com/files-tmb/T02G2QA3A-F03N52T3T-2324edec0f/pasted_image_at_2015_02_17_06_21_pm_1024.png)

@jfirebaugh

**Comment by jfirebaugh** [comment]
Upstream we would need https://github.com/fontello/svgpath/issues/8 in order to handle elliptical arc commands in the SDF renderer.

@ajashton Are you going to swap the `a` commands back to `c`?

**Comment by ajashton** [comment]
This should be fixed with 8b286aafc8c09a8ba3d30ea94ee9d8fb86172595 and c8b3a7b60d56976fee06fee3ec12e6120e6ed655

**Comment by jfirebaugh** [comment]
:+1:
