### ISSUE TITLE
"Couldn't find path for dentist"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/maki#210]
The SDF renderer looks for a `path` element with a style property containing `fill: #44444` or `fill: #454545`. But [`dentist-24.svg`](https://raw.githubusercontent.com/mapbox/maki/mb-pages/src/dentist-24.svg) doesn't follow this pattern. It should be consistent with the other SVGs.

**Comment by christoph-buente** [comment]
Hey @jfirebaugh,

we submitted this icon with the wrong color. Sorry for that. I tried to change it locally and run the dev-render.sh sdf but still with no success. There seems to be something serverly broken, but it is beyond my knowledge what it is. If you figure it out, please let us know so we can adopt all the other icons we want to sumit. See #208 

Cheers, Christoph

**Comment by ajashton** [comment]
I fixed the colros in 3d3bffae2b45e0913d178628bd5b5205ff7481ef but still get "Couldn't find path for dentist" when I run render-sdf.js... not sure why that might be.
