### ISSUE TITLE
Icon names

### ISSUE THREAD

**Issue by robslotboom** [mapbox/maki#216]
Is it possible to include a simple textfile listing all icon names?

Best regards,

Robert

**Comment by samanpwbb** [comment]
@robslotboom will a json file suit your needs? -> https://github.com/mapbox/maki/blob/mb-pages/_includes/maki.json

**Comment by robslotboom** [comment]
Dear Saman,

Absolutely!!! Than you

Best regards,

Robert Slotboom

STUDIO345
-------------------------------------
Van Berchemstraat 133
6981 JA  Doesburg

T	0313 795055
W	studio345.nl

Op 20 mei 2015, om 18:05 heeft Saman Bemel-Benrud <notifications@github.com> het volgende geschreven:
