### ISSUE TITLE
dev-render.sh doesn't export @2x.json files

### ISSUE THREAD

**Issue by apollolm** [mapbox/maki#218]
...does it?

I'm trying add custom icons to a local fork of maki for use in mapbox-gl-js.

I'm able to run the dev-render.sh just fine, and it spits out `maki-sprite.json` with my changes.
It also spits out `images/maki-sprite.png` and `images/maki-sprite@2x.png`

But I don't see it spitting out a `maki-sprite@2x.json`.
Since I have a retina display, my app is trying to pull `maki-sprite@2x.json`

Also - the .json file that I get looks like this:

      "circle-stroked-24": { "x": 0, "y": 0, "width": 24, "height": 24 },
      "circle-stroked-18": { "x": 24, "y": 0, "width": 18, "height": 18 },
      "circle-stroked-12": { "x": 42, "y": 0, "width": 12, "height": 12 },

...whereas outdoors.json looks like this:

    wetland_noveg_64: { x: 0, y: 0, width: 64, height: 32, pixelRatio: 1 },
    wetland_64: { x: 66, y: 0, width: 64, height: 32, pixelRatio: 1 },
    airport-24: { x: 0, y: 34, width: 24, height: 24, pixelRatio: 1},

...it includes a pixelRatio property.
The 2x.json should have pixelRatio: 2 as per https://www.mapbox.com/mapbox-gl-styles/sprites/outdoors@2x.json

Is the .sh script available that creates the correct maki scripts to use in mapbox-gl-js?

**Comment by jfirebaugh** [comment]
Hi @apollolm -- the `maki-sprite.json` that dev-render.sh generates is a different format than, and unrelated to, the sprite .json for Mapbox GL. For generating GL sprites, you want to use [`gl-style-spritify` from mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec#building-sprites). You can point it at the [`renders`](https://github.com/mapbox/maki/tree/mb-pages/renders) directory from maki if that's what you want in the sprite sheet.

**Comment by apollolm** [comment]
I see. Thanks!
