### ISSUE TITLE
Provide webfont

### ISSUE THREAD

**Issue by IvanSanchez** [mapbox/maki#228]
It would be nice if a webfont is provided. There is already a project (https://github.com/fontello/maki.font.git) which creates webfont files from the set of .svg files from maki, but tends to be outdated.

It would be ideal to provide some bootstrap-style icon font, a la https://materialdesignicons.com/bootstrap

**Comment by samanpwbb** [comment]
Feel free to make webfonts with maki yourself, but this is out of scope for the project.
