### ISSUE TITLE
changin color using Arcgis10 (.style)

### ISSUE THREAD

**Issue by vlasvlasvlas** [mapbox/maki#233]
Hi! i want to change the icon color using the .style file for Arcgis 10

but the tool for changing symbol color (symbol selector window) its disabled when i try to use maki .style

how can i change symbol color using maki icons using Arcgis 10?

**Comment by williamscraigm** [comment]
The ArcGIS styles import the vectors as EMF based picture markers.  It's not possible to change the colors of this type of marker within ArcMap.  This is possible with the ArcGIS Pro style where these are vector markers.

**Comment by vlasvlasvlas** [comment]
oki thanks! :)
