### ISSUE TITLE
(How) Does "render.sh android" work?

### ISSUE THREAD

**Issue by durandt** [mapbox/maki#234]
Hi, 

I wonder whether "render.sh android" works and if it does, how. 
Here are the following commands I tried and the outputs I got: 

```
$ ./render.sh android
usage: RES_DIR=/path/to/src/main/res ./render.sh android [12|18|24] [icon-name] ...
```

```
$ RES_DIR=/Users/abcdef05/maki/res ./render.sh android
usage: RES_DIR=/path/to/src/main/res ./render.sh android [12|18|24] [icon-name] ...
```

```
$ RES_DIR=/Users/abcdef05/maki/res ./render.sh android 24 Heart
./render.sh: line 45: m: unbound variable
```

(poke @moskvax )

Regards, 

Thibault D.

**Comment by samanpwbb** [comment]
Maki's structure will be changing soon, we don't plan on supporting this script moving forward. See https://github.com/mapbox/maki-2/
