### ISSUE TITLE
maki cleanup backlog

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/maki#240]
Most of the icons need at least some minor cleanup. Here's a specific, but non-exhaustive list of some changes to make:

- [x] Aerialway - make the top wire feel less like it's cropped to the bounding box
- [x] Dam - Soften curves
- [x] X - Pull in corners 1px
- [x] Cricket - make it a person (Nat to design once all 'streets icons' are completed)
- [ ] Clothing store - Too boxy: needs clearer silhouette, more rounded, reduce bulk: make sleeves separate from body (#251)
- [x] Circle - Pull in a pixel all around
- [x] Cinema - Totally redo it. Try a ticket
- [x] Cemetery - Try to make silhouette more distinct
- [x] Castle - Mostly good, make bottom corner radiuses more elegant, more counter space at small size
- [x] Car - Counter shape of window feels upside down.
- [x] Campsite - Round top of 11px icon
- [x] Cafe - More consistent with style guide
- [x] Building - Looks too much like a house
- [x] Beer - Needs to be more consistent with the rest of the icon set
- [x] Basketball - Redo with a player (Nat to design once all 'streets icons' are completed)
- [x] Baseball - Redo with a player (Nat to design once all 'streets icons' are completed)
- [x] Bank - Should hatching be allowed in the icon set?
- [x] Art Gallery - Switch to framed image, add a art supply store icon
- [x] American football - Redo with a player (Nat to design once all 'streets icons' are completed)
- [x] Alcohol shop - Simplify the icon, remove the glass?
- [x] Airplane - Square off the small airplane icon
- [x] Library - Give it more visual weight, fill in the book pages
- [x] Industry - Soften the edges
- [x] Ice cream - Redraw so it looks better. Go with a single scoop on a waffle cone.
- [x] Heart - Scale it down, round it
- [x] Gift - Try a box with a lit that extends a pixel to the left and right
- [x] Garden - Redraw the whole thing, add bulk
- [x] Ferry - Water near bottom of icon is weird looking
- [x] Fuel - Remove the display with numbers, separate gas pump from base for legibility (#252)
- [x] Fast food - Reduce bulk of both 11 and 15px icons, on 15px, proportions are weird
- [x] Escalator - Consider making the escalator a solid
- [x] Embassy - Icon is inelegant, redraw
- [x] Drinking fountain - Redraw with water drop instead of cup
- [x] Doctor - Add bulk so it's not all strokess
- [x] Dentist - Redraw with more exaggerated roots
- [x] Lighthouse - Windows are not clear enough, consider showing projecting light
- [x] Wheelchar - Should have less counter strokes, feel more unified (Nat to design once all 'streets icons' are completed)
- [x] Wetlands - Redraw: clarify shape of water and plants
- [x] Veterinary - Scale down toes to lighten icon
- [x] Toilet - Simplify, make 15 look more like 11, man looks like he's wearing a kilt
- [x] Tennis - Less angular, fill out limbs (Nat to design once all 'streets icons' are completed)
- [x] Telephone - Make it angled so it doesn't look like a bridge
- [x] Soccer - Needs lots of cleanup: less angled, more rounded (Nat to design once all 'streets icons' are completed)
- [x] Shop - Redraw, what is that weird white bar in the icon.
- [x] Shelter - Simplify, just a roof with support beams
- [x] School - New concept: ruler + pencil
- [x] Religious Jewish - alignment issues with geometry
- [x] Rail - Redraw to look more heavy duty
- [x] Post - clean up top triangle so it's same width as the bottom container
- [x] Playground - Find a way to add a person (Nat to design once all 'streets icons' are completed)
- [x] Pitch - New concept: person running (Nat to design once all 'streets icons' are completed)
- [x] Pharmacy - New concept: hut with cross
- [x] Park - Same concept, redraw
- [x] Music - Same concept, redraw

**Comment by natslaughter** [comment]
@samanpwbb thanks a bunch for the list!

**Comment by nickidlugash** [comment]
@natslaughter should `religious-jewish` be on this list?

**Comment by natslaughter** [comment]
@nickidlugash I just doubled checked the `religious-jewish` icon and you're right: it should be on this list. The geometry is slightly off. I will add and fix.

**Comment by natslaughter** [comment]
Here is the new list of final refinements

- [ ] american football 11px needs better pixel alignment, 15px needs work
- [ ] baseball 15 px bat too small and body to long
- [ ] building 11 & 15 need pixel alignment
- [ ] coffee : maybe remove the saucer, maybe align saucer to cup over all looks rough
- [ ] car: ensure 11px is aligned to grid
- [ ] cemetery: join base and body of 
- [ ] cinema: 11px icon is off 15px too. both are sloppy
- [ ] commercial: building with awning 
- [ ] cricket: needs some work, but don’t worry about it until later
- [ ] danger: missing 15 px
- [ ] dam: make water look like waves in wetland
- [ ] drinking water: 11px more aligned
- [ ] embassy: less space between flag and flagpole (for both scales)
- [ ] fast food: 11px alignment issues, 15 px do less gap between buns and meat
- [ ] ferry: margin between boat and water a little bigger
- [ ] fuel: check alignment
- [ ] garden: not aligned or centered on 11px, on 15x make bottom edges of flower more curved
- [ ] gift: more alignment
- [ ] ice cream: define the scoop shape and make more aligned with grid.
- [ ] industry: 11px bottom of bldg is not aligned, make a little smaller
- [ ] lighthouse: 11px a little more work
- [ ] park: 11px too blurry, try to get more negative space around the trunk and branch. pull bottom edge of the leaves up to be aligned
- [ ] pharmacy: 15px cross is not aligned
- [ ] pitch: 11px not aligned. try to find a more generic icon like kids crossing 
- [ ] place of worship: 11px needs to be aligned
- [ ] playground: swing needs more definition and width
- [ ] post: too tall
- [ ] rail: update 15x, 11px needs to match the 15 better
- [ ] religious-jewish: better pixel aligned
- [ ] school: pencil has too many distinct parts, look at converting the ruler marker voids to a .5 pixel
- [ ] shelter: 2px strokes not 1px
- [ ] soccer: player needs more of a torso.
- [ ] tennis: look at leg alignment 11px racket is really blurry
- [ ] toilet: 11px look into joining the legs 
- [ ] warehouse: use exact same shape on 15px as 11px
- [ ] waste basket: maybe 1 too many pixels between bin and top on the 15px
- [ ] wheelchair: join the wheel

**Comment by natslaughter** [comment]
pick up later tonight or tomorrow morning on 11px shelter

**Comment by natslaughter** [comment]
Here is the new final list of refinements:

- [ ] Building 11px could be better
- [ ] Campsite 11px looks blurry
- [ ] Car 11px: extend wheels to 2 pixels
- [ ] Cinema: Thicken and clarify the reels
- [ ] Cemetery: base looks too wide; bring in 1 pixel
- [ ] Commercial: remove sign, 15px seems a bit small
- [ ] Danger: 11px look at alignment
- [ ] Fast-food: Round bottom bun a little
- [ ] Ice Cream: 11px is too abstract, 15px increase size of top circles
- [ ] Gift: 11px middle void is too much. Try 1 or 1.5 pixels
- [ ] Park: Trunk is too thin… needs work
- [ ] Playground: 11px needs a bit more work
- [ ] Soccer: Torso is a little short on 15 px
- [ ] Warehouse: 15px too much space between top boxes
- [ ] Wheelchair: 15px leg is too thin

**Comment by natslaughter** [comment]
After looking at all icons on Satellite map, return to these icons and tweak:

- [ ] Alcohol Shop - Looks a little fuzzy
- [ ] Beer - The top of the glass is cropped strangely
- [ ] Lodging - Pushing the trim space a little too much
- [ ] Park - Choose the more natural looking tree. Work on carving out one void to define a branch
- [ ] Pharmacy - Bottom heavy and the pestle should be re-aligned
- [ ] School - Looks horrible on maps
- [ ] Industry - Pull up 1 pixel
- [ ] Restaurant - Look into clarifying the fork tongs. They look fuzzy.

**Comment by samanpwbb** [comment]
Done for now.
