### ISSUE TITLE
Fuel Icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#252]
@emilymdubois 

Check out ticket #240 for reference. It has the back log list of remaining work with notes.

Regarding the fuel icon, the numbers need to be removed, there needs to be some space between the tank and the nozzle for visual clarity, and make sure it follows the design guidelines.

**Comment by emilymdubois** [comment]
This was merged into the `maki-2.0` branch, tracked on [PR 253](https://github.com/mapbox/maki/pull/253)
