### ISSUE TITLE
More Energy specific related icons

### ISSUE THREAD

**Issue by vlasvlasvlas** [mapbox/maki#254]
Hi! would be great to have more energy specific related icons..

we made some for Argentina Ministry of energy & minery following maki kind-of guidelines. 

If you want i can upload them & help with a starting baseline

:)

**Comment by tristen** [comment]
Closing as stale. There are a few energy related icons like [charging stations](https://github.com/mapbox/maki/blob/master/icons/charging-station-15.svg) and [windmill](https://github.com/mapbox/maki/blob/master/icons/windmill-15.svg). If you have others you would like to contribute to Maki, please submit them as pull requests 🙏
