### ISSUE TITLE
Maki 3 ? or 2 ?

### ISSUE THREAD

**Issue by dav-m85** [mapbox/maki#256]
Just found out about Maki on the [Mapbox blog](https://www.mapbox.com/blog/introducing-maki-3/).  

However I'm pretty confused as for the versioning, the Github release **v2.0.2** seems to be what the post refers to as "Maki 3", but there no mention of it anywhere in the code.

Besides, a few links are broken on the README, not sure where they shall go for I would have providen a PR for it.

That said, amazing work @mapbox, lovin' it.

**Comment by samanpwbb** [comment]
We've announced 3 versions of maki over the years, but the npm version scheme never aligned to the announced versions. I should have had a little more foresight and bumped the npm version all the way up to 3 this time around.

I'll take a look at the read me and make sure the links are all working.
