### ISSUE TITLE
Telco Tower / Base Station / Cellular Tower

### ISSUE THREAD

**Issue by kazitoufiq** [mapbox/maki#257]
Need Telco Tower / Base Station / Cellular Tower icon

**Comment by aparlato** [comment]
Still iterating, however here is a first draft.

![image](https://cloud.githubusercontent.com/assets/15698320/22045987/9f180c68-dcd2-11e6-861a-04149b50186d.png)

**Comment by aparlato** [comment]
Also, [man_made=communications_tower](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcommunications_tower) ([taginfo](http://taginfo.openstreetmap.org/tags/man_made=communications_tower) ) and [tower:type=communication](http://taginfo.openstreetmap.org/tags/tower%3Atype=communication) and [man_made=tower](http://taginfo.openstreetmap.org/tags/man_made=tower) appear to be the most common associated tags.

**Comment by tristen** [comment]
This was done in #445
