### ISSUE TITLE
Make `drinking-water` icon bigger

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki#265]
The `drinking-water` icons, especially `-11`, does not have as much visual weight as the other icons. Can we bulk it up a bit? Perhaps make the water droplet bigger?

/cc @natslaughter

**Comment by natslaughter** [comment]
@nickidlugash 
Let me know if you think works any better on your end

![screen shot 2016-05-06 at 9 20 25 am](https://cloud.githubusercontent.com/assets/16616543/15074266/edf82844-136b-11e6-9333-f89610b1b047.png)

**Comment by nickidlugash** [comment]
@natslaughter I think it looks good! Can you push this up to a branch so I can pull it down and test it on a map?

**Comment by nickidlugash** [comment]
@natslaughter hmm now I'm thinking we should go back to the cup O_O What do you think?

![drinking-water-11-72](https://cloud.githubusercontent.com/assets/5607844/15090011/076398fa-13e3-11e6-892a-aa5efd4b94af.png)

**Comment by natslaughter** [comment]
@nickidlugash I think you're right. Seeing them side by side, the cup concept reads better.

**Comment by samanpwbb** [comment]
This is done!
