### ISSUE TITLE
OSM type => Mapbox maki mapping

### ISSUE THREAD

**Issue by dpieri** [mapbox/maki#269]
Are you willing to share how Mapbox maps the type property of OSM POI labels to maki properties in Mapbox Streets tilesets? Is it a simple mapping, or a more involved translation?

If it is a simple mapping, would you be willing to open source it?

**Comment by tristen** [comment]
Mapping is loosely a 1:1 mapping for OSM and different for other data with varying complexity. Because of the complexity and frequency of changes, this is not shared.
