### ISSUE TITLE
Hospital Icon Violates the Geneva Convention

### ISSUE THREAD

**Issue by wonderchook** [mapbox/maki#27]
Using the red cross symbol as an icon for hospital violates the Geneva Convention(1).  It would be good to find a universal hospital/medical symbol that doesn't.

(1) http://en.wikipedia.org/wiki/Emblems_of_the_International_Red_Cross_and_Red_Crescent_Movement#Use_of_the_emblems

**Comment by samanpwbb** [comment]
I don't see any better alternatives.
