### ISSUE TITLE
viewpoint icon

### ISSUE THREAD

**Issue by valleyofdawn** [mapbox/maki#271]
For tourism=viewpoint

**Comment by rasagy** [comment]
I made minor tweaks to the icons made by @sarahmamy in her [PR](https://github.com/mapbox/maki/pull/392) — thanks a lot for sharing it! 🙇 

I used circular 15˚ grid and exaggerated the negative space between the dot and rays, which especially helps with the 11px icon:

<img width="35" alt="screenshot 2018-06-20 20 55 33" src="https://user-images.githubusercontent.com/1117531/41779204-b4b4691a-764e-11e8-8f70-d2ccdd494e52.png">

Base grid:
<img width="352" alt="screenshot 2018-06-22 19 03 14" src="https://user-images.githubusercontent.com/1117531/41779268-ee060b60-764e-11e8-9b93-5a6ece528b8e.png">

Minor tweaks to make it align closely to the grid:

<img width="363" alt="screenshot 2018-06-22 19 04 21" src="https://user-images.githubusercontent.com/1117531/41779370-3b018d72-764f-11e8-98d1-9df9f8dac26c.png">
<img width="495" alt="screenshot 2018-06-22 19 05 01" src="https://user-images.githubusercontent.com/1117531/41779375-3c4fd986-764f-11e8-861b-c8c3530f24c3.png">

@natslaughter Would love your feedback on one specific detail: if the 1px radius dot in the 11px works better when it perfectly aligns with the grid (but looks like a rectangle when pixelated) or when it is aligned to the center of a pixel (and looks like a + when pixelated).

<img width="185" alt="screenshot 2018-06-22 19 09 12" src="https://user-images.githubusercontent.com/1117531/41779556-c4cec632-764f-11e8-9fa4-76b155174383.png" align="left">
<img width="220" alt="screenshot 2018-06-22 19 07 41" src="https://user-images.githubusercontent.com/1117531/41779557-c50111e6-764f-11e8-9219-55599a705369.png">

**Comment by rasagy** [comment]
Here’s a stab at 11px icon with more tapered rays:

<img width="35" alt="screenshot 2018-07-05 19 24 21" src="https://user-images.githubusercontent.com/1117531/42329893-784f363a-808f-11e8-962f-9c284762dbd0.png">

Older version for comparison:

<img width="35" alt="screenshot 2018-06-20 20 55 33" src="https://user-images.githubusercontent.com/1117531/41779204-b4b4691a-764e-11e8-8f70-d2ccdd494e52.png">

----

Because of the vertical 1px shift, the rays don’t look like they are converging at the circle’s center. I’ll see if I can redo the tapering to change this slightly.

**Comment by natslaughter** [comment]
@rasagy I would quickly see if additional tapering of the ray's ends helps create more negative space: I don't see much difference in the two versions above.

**Comment by rasagy** [comment]
Worked on even more tapering, with the two rays on the edge converging more towards the circle’s center:

<img width="17" alt="screenshot 2018-07-11 17 52 07" src="https://user-images.githubusercontent.com/1117531/42571243-2f9263c8-8534-11e8-950a-432cde1c779f.png">

(Top is with most tapering, middle is the last iteration with minimal tapering, bottom is the oldest version with no tapering)

**Comment by natslaughter** [comment]
@rasagy the top icon - with the most tapering - is looking great. 
Next action: map mock-up.

**Comment by rasagy** [comment]
Perfect. I also made minor tweaks to the 15px icon to add a bit of tapering, going ahead with the top options for both sizes:

<img width="37" alt="screenshot 2018-07-17 18 48 07" src="https://user-images.githubusercontent.com/1117531/42819719-fb1ff084-89f1-11e8-962e-cbc72ed2041a.png">

**Comment by tristen** [comment]
Connecting the dots that this was added to Maki https://github.com/mapbox/maki/blob/master/icons/viewpoint-11.svg
