### ISSUE TITLE
Does Mapbox marker icon uses icons from Maki icon set?

### ISSUE THREAD

**Issue by rahuldhawani** [mapbox/maki#277]
Some icons in the Maki Icon set are different than the icons in the Mapbox icon set. For example 
![screen shot 2016-06-09 at 9 27 15 pm](https://cloud.githubusercontent.com/assets/7352827/15937580/24da46b2-2e8d-11e6-80c4-47fe58be877a.png)
![screen shot 2016-06-09 at 9 27 48 pm](https://cloud.githubusercontent.com/assets/7352827/15937603/36d38766-2e8d-11e6-8217-a768ed71c44b.png)

First icon is from Maki i.e.`baseball-15.svg` and the second is from mapbox i.e. when I provide `baseball` in the `marker-symbol`. This is just one example, there are many as these like, basketball, cinema etc.

Now I am confused that does Mapbox actually uses Maki icons as a default set of icons? 
In this [article](https://www.mapbox.com/help/markers/#simple-style) its stated that any of the Maki Icon name will work and it works but both are not same.

**Comment by samanpwbb** [comment]
Mapbox marker API is pinned to an old version of maki, and many markers have been redesigned. [We released version 2.0.0](https://github.com/mapbox/maki/pull/241) recently, which has fully redrawn icons.

We has no plans to update the marker API to the latest version of Maki.
