### ISSUE TITLE
General Historical Landmark Icon Request

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#286]

**Comment by samanpwbb** [comment]
https://github.com/mapbox/maki/blob/master/icons/monument-15.svg wouldn't work for this?

**Comment by natslaughter** [comment]
@samanpwbb 
yes, it would.

**Comment by YunjieLi** [comment]
I'll still make another one that works better in the East Asian context

**Comment by natslaughter** [comment]
This was resolved with [this landmark](https://github.com/mapbox/maki/blob/master/icons/landmark-15.svg) icon.
