### ISSUE TITLE
Karaoke Icon Request

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#288]

**Comment by geografa** [comment]
cc @incanus for inspiration

**Comment by incanus** [comment]
something like this but make it pop

![](http://interest-hobby.com/highresolution/l_017.jpg)

**Comment by geografa** [comment]
![pop](https://cloud.githubusercontent.com/assets/134753/17913589/10ad2044-6950-11e6-84b3-7b08a6054575.jpg)

but with a mic drop.

**Comment by xrwang** [comment]
gonna do a pass at this one, feel free to reject.

**Comment by natslaughter** [comment]
@xrwang 
I made this 11 x 11 pixel draft Friday and am not sure it's working at 100% scale. It reads too abstract and needs to look more unique. Maybe a different kind of microphone that's more modern?


![karaoke-11-draft-01](https://cloud.githubusercontent.com/assets/16616543/18054628/a47b5b98-6dd2-11e6-98e1-ef2c9567f693.png)

**Comment by incanus** [comment]
Yeah, a little abstract. Also, handheld mics like these are more common: 

![](http://image.flaticon.com/icons/png/256/69/69364.png)

![](https://cdn1.iconfinder.com/data/icons/social-messaging-productivity-3/128/microphone-512.png)

![](http://cdn.vectorstock.com/i/composite/41,94/karaoke-icon-vector-734194.jpg)

![microphone_318-47736](https://cloud.githubusercontent.com/assets/17722/18054823/4eef1a2e-6dba-11e6-8823-04d3c90c351a.jpg)

**Comment by natslaughter** [comment]
@incanus I agree. 
The handheld mics have a more distinct silhouette and would probably work better.

**Comment by xrwang** [comment]
here's a draft of what i was working on, @natslaughter @YunjieLi, i'll put the ai in a dropbox and if it's helpful at all, maybe we can continue with it. thanks!
<img width="356" alt="screen shot 2016-08-29 at 9 10 59 am" src="https://cloud.githubusercontent.com/assets/4019929/18058309/9db4d410-6dc8-11e6-984e-8ca4e510c299.png">

**Comment by xrwang** [comment]
(fyi, the one i did is 15px, so hopefully it's a productive overlap)

**Comment by YunjieLi** [comment]
Just saw this conversation!!

These are the -15 and -11 ones I did last Friday
![image](https://cloud.githubusercontent.com/assets/12749701/18059668/d907bca2-6dce-11e6-943e-efe54602a2df.png)
