### ISSUE TITLE
Electric Vehicle Charging Station Icon Request

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#291]

**Comment by aparlato** [comment]
http://taginfo.openstreetmap.org/tags/amenity=charging_station

For this I am using the fuel icon and replacing the small meter window with a lightning bolt inside the pump. The 11px is still getting a little lost, but 15 is looking fairly good.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22226971/966a6f66-e17d-11e6-8614-9abef838f51f.png)
**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22226979/9fdc22d8-e17d-11e6-885f-22303b8f64ca.png)

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22227254/40cf696a-e17f-11e6-8e4f-910b168df31c.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22227267/53201204-e17f-11e6-9e30-2b9f19678768.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22227262/4a5e0fd6-e17f-11e6-899b-edb1d3ef3d61.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22227274/5cfe642e-e17f-11e6-8c35-cae2997a772c.png)

**Comment by natslaughter** [comment]
@aparlato Looks good!
Any way you could create a branch for this icon so I could pull and check it out in Illustrator?

**Comment by aparlato** [comment]
@natslaughter just pushed it into a branch :+1:

**Comment by natslaughter** [comment]
@aparlato just checked these icons out in Illustrator: both are legible and :+1: and ready for a PR

**Comment by zimirrr** [comment]
Is there any other icons for Electric Vehicle Charging Station and where can I get this icon?

**Comment by tristen** [comment]
This is done https://github.com/mapbox/maki/blob/master/icons/charging-station-15.svg
