### ISSUE TITLE
Document the naming convention for alternate icons

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki#296]
For some Maki icon concepts, it makes sense to include alternative icons. We can append `alt1` etc to their file names (after the maki name, before the size).

The original icon (aka the one without "alt" in the name) should be the icon that the Mapbox Streets style uses for that Mapbox Streets data Maki value. In most cases, this is the icon users will want to use in conjunction with the Mapbox Streets data. If they want to use an alternative icon with our data, they can just rename the icons in their project accordingly.   

We have two icons in our latest batch that could be renamed using this system:
- `landmark-{size}` --> `landmark-alt1-{size}` (and bring back the original `landmark-{size}` that was overridden)
- `central-building-{size}` --> `building-alt1-{size}`. I think the name "central building" is too specific – this icon could be used to represent any kind of building.

^ @natslaughter what do you think of these suggested updates?

/cc @samanpwbb

**Comment by natslaughter** [comment]
@nickidlugash 
I think this is a logical approach to this issue.

**Comment by natslaughter** [comment]
@nickidlugash 
Do you feel that the `icon-name-alt1-15` technique works?
If so, can we close this issue?

**Comment by nickidlugash** [comment]
@natslaughter I think we should move forward with this for now, and can revisit later if necessary based on user feedback.

Let's get this documented in the guidelines first though before we close the ticket.

**Comment by tristen** [comment]
Covered by @willymaps commits here https://github.com/mapbox/maki-icons/pull/146/commits/c32fbb48cdbf5dd9c35476cf66ef5cc253aba2bd#diff-65e360863a7d9b7c5763333775e588f2c9a363f5d98eee00e86b68f3359439f9R500-R503 Closing!
