### ISSUE TITLE
Horse riding icon

### ISSUE THREAD

**Issue by Hufkratzer** [mapbox/maki#304]
There will be an icon needed for leisure=horse_riding presets in iD, see
https://github.com/openstreetmap/iD/issues/3619

JOSM uses this one:
https://josm.openstreetmap.de/browser/trunk/images/presets/leisure/horse_riding.svg

In iD there are similar icons used for highway=bridleway and route=horse, see here:
https://github.com/openstreetmap/iD/blob/c8e4f76c230512dc82dc060bf337e3ba489b113e/svg/iD-sprite.src.svg

**Comment by aparlato** [comment]
**First Draft**

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21238209/06180a8e-c2b7-11e6-9583-0c33ff92b4c8.png) 
![image](https://cloud.githubusercontent.com/assets/15698320/21238221/0e6c7c2e-c2b7-11e6-9e80-e58b5c196165.png)
**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21238231/19af30d6-c2b7-11e6-8044-de839b6e6650.png) 
![image](https://cloud.githubusercontent.com/assets/15698320/21238235/2358432a-c2b7-11e6-8b47-83194fed9d75.png)

**Comment by Hufkratzer** [comment]
Hmm. Thanks for the information, but the horse riding icons that I mentioned initially look better to me. Is it necessary that the rider and the tail of the horse are disconnected from the horse? Can't the horse have ears? (The [maki-dog](https://github.com/mapbox/maki/blob/master/icons/dog-park-15.svg) has.) Why are the legs of the horse so short and why is the neck so long? It doesn't look like a real horse to me. Why can't the rider sit straight? Can't he have arms?

Here are some external links that perhaps can explain better what I mean:
- http://horses.about.com/od/learntoride/ht/properseat.htm - How To Sit in The Saddle Correctly
- http://www.youtube.com/watch?v=hVnq-vNKDps - Intro Movie The Horse Soldiers

**Comment by aparlato** [comment]
**Draft 2**

Definitely getting better. Currently working through some pathfinder issues to clean things up.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21276446/563cc214-c386-11e6-83b9-c68d88406a2b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21276457/6039aef8-c386-11e6-81c3-a626a9c7f83b.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21278087/16d6ba64-c38e-11e6-8e86-b08b6b0ac757.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21278097/1f561afe-c38e-11e6-970f-4903b847b6fc.png)

**Comment by Hufkratzer** [comment]
Much better, thanks. Maybe you can improve the rider a bit more, please look at [this page](http://www.equine-world.co.uk/riding_horses/rider_position.asp) :
> The upper body should remain straight but not stiff with the head looking forward. It should be possible to draw a straight line from the shoulder to the hip to the foot of the rider.

I think, the position of the feet is not so important in the icon, I don't know if it can be improved. But the head should better sit straight on top of the body, like [here](https://github.com/openstreetmap/iD/blob/c8e4f76c230512dc82dc060bf337e3ba489b113e/svg/iD-sprite.src.svg).

**Comment by aparlato** [comment]
**Draft 3**

Two here for comparison

**A)**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21283597/0df530de-c3ba-11e6-811f-656884000e99.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21283600/1492a2fa-c3ba-11e6-98d2-f2481766f7bf.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21283660/19e3be64-c3bb-11e6-91a7-60cd7ca3f670.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21283663/1fe0af2a-c3bb-11e6-9099-c99af784f4ae.png)


OR

**B:** which is blockier/made of of more components in a way that might feel more appropriate?

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21283639/cf73f538-c3ba-11e6-821f-4f6d28f98c05.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21283640/d696857e-c3ba-11e6-997a-cc1f62eb79be.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21283648/e49f270c-c3ba-11e6-92a3-407a37204356.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21283651/eb93a024-c3ba-11e6-924b-5440dc2655d1.png)

Still working on this. Looking at it now, I'm not really liking the second version posted here.

**Comment by Hufkratzer** [comment]
What about making the rider less tall in the 15px version so that 11px and 15px versions are more similar?, something like
![v2-15px-rider-less-tall](https://cloud.githubusercontent.com/assets/5958184/21286094/cd544f60-c44a-11e6-8ffc-afc9611da5bb.png)

The second version would only make sense with a 4th leg for the horse, something like this:
![v1-15px-4legs](https://cloud.githubusercontent.com/assets/5958184/21286077/757c1458-c44a-11e6-9e6c-6743b718ffc0.png)
(But since the other animals in maki (dog, cow) also have just 3 legs I assume the first version fits better into this concept.)

**Comment by Hufkratzer** [comment]
The front leg(s) should either be straight or angled as you can see [here](https://en.wikipedia.org/wiki/File:Trakehner_Reithengst,_Auktion_Neumünster_2004.jpg) (from https://en.wikipedia.org/wiki/Equine_conformation which has more examples)

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21328963/4e390ab6-c604-11e6-927f-e4b5e59ff03e.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21328973/58930c8c-c604-11e6-8f3c-db2d569d8397.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21328978/5f73dff4-c604-11e6-8139-b5b0108353c4.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21328986/67305fb0-c604-11e6-9034-769b822bcd00.png)

**Comment by Hufkratzer** [comment]
Horses lift their tail like this typically before they poop,
see video https://youtu.be/ir97e1wsFO8

**Comment by aparlato** [comment]
This was done.
