### ISSUE TITLE
The Maki editor only works with SVG paths. No transforms ...

### ISSUE THREAD

**Issue by benjaminhon** [mapbox/maki#305]
Im am trying to upload the maki fonts into the icon editor, but even this theres an error,

```
The following icons have been discarded:
File nameMessage
aerialway-11.svg Transformed path.
aerialway-15.svg Transformed path.
airfield-11.svg Transformed path.
```

Im just trying to make 2 sets, one blue color and the other green color.

Any help is appreciated

**Comment by samanpwbb** [comment]
Supporting transforms adds some complexity to SVG parsing. It's doable but honestly not a high priority at Mapbox right now since we make sure our SVGs are clean before importing them into the editor. You can try to modify your SVGs and remove the transforms.

**Comment by mimilove66** [comment]
我想问一下使用什么软件制作一个Maki图标，求告知

**Comment by micahcochran** [comment]
> 我想问一下使用什么软件制作一个Maki图标，求告知

[Inkscape](https://inkscape.org/)

**Comment by tristen** [comment]
Closing as stale
