### ISSUE TITLE
emergency-phone icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#306]
For id-support from #270 

[Emergency Phone on taginfo](http://taginfo.openstreetmap.org/tags/emergency=phone#overview)

icon for emergency:phone

Other icons of this:

<img src="https://cloud.githubusercontent.com/assets/15698320/21066269/932ce16c-be19-11e6-901c-da857b2c1b2a.png" width=100>

<img src="https://cloud.githubusercontent.com/assets/15698320/21066277/9d7466ae-be19-11e6-902a-79a6c8c8927f.png" width=100>

<img src="https://cloud.githubusercontent.com/assets/15698320/21066283/a3d0382a-be19-11e6-9847-a49d4cfbddd7.png" width=100>

<img src="https://cloud.githubusercontent.com/assets/15698320/21066286/a7bac19e-be19-11e6-9b41-ebb3c37cefec.png" width=100>

[reference to Maki 1 icon for emergency-phone](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/emergency-telephone-24.svg)

cc @nickidlugash

**Comment by aparlato** [comment]
First draft pushed to maki-2-updates branch.

**Comment by natslaughter** [comment]
@aparlato 
First icon project! \0/ \0/ \0/

- Overall I think the icon concept is good as it's globally recognizable. 
- You might want to take a look at the existing Maki icon `telephone`, and use the existing telephone geometry we have for consistency. 
- Also, you'll want to make sure the geometry is pixel aligned, and snaps to the grid

![screen shot 2016-12-12 at 2 16 24 pm](https://cloud.githubusercontent.com/assets/16616543/21112934/9cff8dc6-c075-11e6-9a87-a9214b274f49.png)

**Comment by aparlato** [comment]
#### Question

I have two options for emergency-phone-11. One has a thicker cross. I'm more inclined toward the thinner cross as I think it improves clarity, but it would break the general rule of strokes being 1px wide (it is 1/2 px wide). I've seen other icons do this (eg. waste-basket), so the question is, should I maintain 1px stroke, or if it does not matter, which appears to work better?

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21116927/73f855f6-c06c-11e6-81b4-4bb55df8ac11.png)


![image](https://cloud.githubusercontent.com/assets/15698320/21116803/e8869082-c06b-11e6-9b03-ae451c8c8cab.png)

OR

![image](https://cloud.githubusercontent.com/assets/15698320/21116961/a2c5f424-c06c-11e6-8b6b-fc6f60b41266.png)


![image](https://cloud.githubusercontent.com/assets/15698320/21116942/8ff1a136-c06c-11e6-8485-f3d36f2c6883.png)

____

**15:**

![image](https://cloud.githubusercontent.com/assets/15698320/21116725/88ca291a-c06b-11e6-9a03-e7959475226a.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21116776/ca03f000-c06b-11e6-85ae-464b5d8c151e.png)

**Comment by aparlato** [comment]
#### Draft 2

Not sure 11 is working yet. Still feels cramped and unclear.

[emergency-phone-11](https://github.com/mapbox/maki/blob/id-support/icons/emergency-phone-11.svg)
[emergency-phone-15](https://github.com/mapbox/maki/blob/id-support/icons/emergency-phone-15.svg)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21123769/93d2a1d8-c08f-11e6-835c-706afc21ecfc.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123789/adc5c354-c08f-11e6-82ea-20656560cf9d.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21123777/9d5bad80-c08f-11e6-85f9-155ab0193972.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123784/a4d7074e-c08f-11e6-9287-537679884a92.png)

**Comment by natslaughter** [comment]
@aparlato 
Looking good.

One thing to note about the `emergency-phone-15` that also will apply to the other icons is how pixels are given a color value percentage based on what is in the pixel. The `plus sign` for example is based on a half grid, which makes it a little blurry. 
One way you can check for this is the pixel preview (shift+command+y) and quickly see what it will look like at 100% scale

<img width="499" alt="screen shot 2016-12-13 at 11 34 40 am" src="https://cloud.githubusercontent.com/assets/16616543/21149333/2e839298-c129-11e6-8c8a-d39fc909592a.png">  
normal view
<img width="498" alt="screen shot 2016-12-13 at 11 34 55 am" src="https://cloud.githubusercontent.com/assets/16616543/21149340/31998640-c129-11e6-9de3-1cac28a3d13b.png">  
pixel preview

**Comment by natslaughter** [comment]
@aparlato 
for the `emergency-phone-11`, try making the `plus sign` .5 pixel widths instead of 1 pixel, and position the plus so that the vertical stroke is centered within the pixel grid.

<img width="59" alt="screen shot 2016-12-13 at 11 48 05 am" src="https://cloud.githubusercontent.com/assets/16616543/21149658/42a972f0-c12a-11e6-879c-d65501eee59b.png">    

<img width="147" alt="screen shot 2016-12-13 at 11 50 51 am" src="https://cloud.githubusercontent.com/assets/16616543/21149700/6c377f7c-c12a-11e6-99b9-0d6643f1a8df.png">

**Comment by aparlato** [comment]
**Question: I posted two versions of the 11px revised at actual size in pixel preview. The second one is much clearer _but_ the plus sign falls a little outside of trim area. Is this still the better option or do I work to keep it inside of trim area as a first priority in which case I'll have to continue working option 1?

![image](https://cloud.githubusercontent.com/assets/15698320/21152675/34031e30-c11c-11e6-8458-3e264d93a555.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21152693/465c14ce-c11c-11e6-8898-637c7d0485a2.png)

**Comment by natslaughter** [comment]
@aparlato 
you can try uploading an .svg to the maki editor and seeing how applying background fills look.

**Comment by aparlato** [comment]
**1)** emergency-phone-11 (with plus outside trim) 
**2)** emergency-phone-11 (inside trim) 
**3)** telephone-11 (for reference)


**in circle background: 0px padding**
![image](https://cloud.githubusercontent.com/assets/15698320/21153503/93ed8d32-c11f-11e6-98b4-8117ca657429.png)

**in circle background: 4px padding**
![image](https://cloud.githubusercontent.com/assets/15698320/21153511/a0d5df68-c11f-11e6-97ce-a3a331423991.png)

Based on this I'm leaning toward the one inside trim, less so because of the trim, moreso because it appears clearer on a background. I'll try to make that one more clear.

**Comment by nickidlugash** [comment]
> Based on this I'm leaning toward the one inside trim

Sounds good to me.

**Comment by aparlato** [comment]
I know @natslaughter was going to work on a new phone icon, but I kind of like it turned vertically.
![image](https://cloud.githubusercontent.com/assets/15698320/21247033/683577ea-c2e1-11e6-9d43-b0e60f7ad33a.png)

Also pretty good turned 90 deg.

![image](https://cloud.githubusercontent.com/assets/15698320/21247102/e6550578-c2e1-11e6-8f0f-68bb988b47cf.png)
(both pics at 11px)

**Comment by aparlato** [comment]
With new telephone icon (Thank you @natslaughter !)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21355040/7fb0fa40-c69a-11e6-8522-59a1aebe4456.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21355045/86b0b2a4-c69a-11e6-97ef-a1af2cab389b.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21355052/8e4de7d4-c69a-11e6-93d0-61246021a3de.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21355057/959295bc-c69a-11e6-919f-e468c5a8a12f.png)

____
I think this looks good. The plus in the 11px version crosses a pixel on the horizontal stroke leaves a little blurry grey-ness, however, after trying different positions and sizes, I have found this to be the most clear and consistent with the 15px. Below is an example of what it looks like to have a clearer plus. When it gets larger and more clear like this, it also has to get closer to the phone and the whole thing begins to feel like a single mark rather than two (a phone with a plus).
![image](https://cloud.githubusercontent.com/assets/15698320/21355247/4017cc14-c69b-11e6-8d65-a6feedf04996.png)

**Comment by aparlato** [comment]
This was done.
