### ISSUE TITLE
city icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#307]
For id-support from #270 

[City on tag info](http://taginfo.openstreetmap.org/tags/place=city)

[reference to Maki 1 icon of city](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/city-24.svg)

icon for place:city

cc @nickidlugash

**Comment by aparlato** [comment]
#### First draft of city

[city-11](https://github.com/mapbox/maki/blob/id-support/icons/city-11.svg)

[city-15](https://github.com/mapbox/maki/blob/id-support/icons/city-15.svg)

**11:** ![image](https://cloud.githubusercontent.com/assets/15698320/21123496/e987312c-c08d-11e6-8092-b3e69274a1c7.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123628/a4ed78d6-c08e-11e6-8d1c-fc71ba875509.png)



**15:** ![image](https://cloud.githubusercontent.com/assets/15698320/21123485/dde84068-c08d-11e6-8162-2824549625c6.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123636/b3c258f4-c08e-11e6-98da-9509932cc6ef.png)


It would be good to look at these next to [Village](https://github.com/mapbox/maki/issues/314) and [Town](https://github.com/mapbox/maki/issues/313)

**Comment by natslaughter** [comment]
@aparlato 
Nice start, and I think the relationships with the `town` and `village` icons is working. 
A few things to consider:

`city-15` 
- The taller building's top could be more exaggerated and use the extra pixel of space above the building.
- The taller building's windows are not within the pixel grid, and would be crisper voids if they were positioned like the smaller building.
- The taller building's bottom should align to the pixel grid
- Just a thought: some of these comments will extend the height of the taller building, and shifting on building up or down to give the icon depth and perspective, you might want to look at shifting the smaller building up: basically reversing what you have now. This would also suggest that you switch the `town` and `village` icons, but I don't see any problem with that since those icons just have one building that's copied.

**Comment by aparlato** [comment]
**Draft 2**

I feel like 11 might look a little to pointed rather than stepped on the top of the left building which might make it feel a bit too much like town-11.

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21157761/78f7d6da-c12f-11e6-9252-06e3bef0faba.png)


**15:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21157777/8485ab8a-c12f-11e6-94be-1323d70818e0.png)

**Comment by aparlato** [comment]
Thoughts on this approach for city? I'm about to try similar things for town and village.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21208874/d36c48b6-c225-11e6-85f4-a13eb8166967.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21208881/d9e81d28-c225-11e6-97c6-9a00c6d9d7e1.png)

**Comment by aparlato** [comment]
update to ^
Thoughts on this approach to city, town, village? (posting to all three tickets)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21209433/1246d60c-c229-11e6-9249-ec1d0b1d27da.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209440/1ba5861c-c229-11e6-897f-af8ea7661dc9.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209446/2495cea8-c229-11e6-8ea5-6803e9cdcd05.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21209460/3ca398c2-c229-11e6-99a3-42caeacf6e7a.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209464/440932ac-c229-11e6-897c-9a75112a0356.png)  ![image](https://cloud.githubusercontent.com/assets/15698320/21209471/4b194dc0-c229-11e6-906d-79543dc97b7c.png)

**Comment by aparlato** [comment]
I tried to take the suggestions from the meeting today. Let me know what's working, what's not.

A) less going on, two buildings
B) buildings are **not** identical (or nearly) pairings
C) corners are rounded/friendly

![image](https://cloud.githubusercontent.com/assets/15698320/21248417/cfd08278-c2eb-11e6-9b70-4fe638c32c7a.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248423/d5f8ce44-c2eb-11e6-8004-693c5fff18a8.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248426/dbee0918-c2eb-11e6-9d93-9f4d890538e1.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21248434/ef0db2be-c2eb-11e6-80ca-0f1fa5047f89.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248440/f679bff2-c2eb-11e6-9f72-f669b9795b04.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248443/ff9c4a6e-c2eb-11e6-8f12-a9aadcf6d572.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21248454/1031951e-c2ec-11e6-8209-4a4d5ba1bade.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248458/159ca1ce-c2ec-11e6-985a-7c0136dc3612.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248462/1a53c3f0-c2ec-11e6-838e-d8857ed8c0ba.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21248471/296a1024-c2ec-11e6-9c38-3074898e63f2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248473/32d66b4e-c2ec-11e6-9281-6afa5426ab50.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248484/3e72664c-c2ec-11e6-8be3-a87630239908.png)

_____

Debating about white space in village, might be too much, but it lines up well on the pixels. It's clearly way out of proportion when blown up. I'll try reworking it, but below is what happens when I use any less white space which I think is hard to read. Might have to rework the whole thing.
![image](https://cloud.githubusercontent.com/assets/15698320/21248694/9b2e6bc8-c2ed-11e6-967c-7b4035e99d77.png)

**Comment by natslaughter** [comment]
@aparlato 
Nice work!

Overall, I think this concept might work, although they still look like discrete objects to me. Personally, I think overlapping two objects might read more like "one" object, instead of two objects that read more "side by side." I would be curious to hear with others think. 

I'll post icon comments on respective tickets.

- Although I love the idea of a skyscraper with no roof, I'm not sure the building on the right works.
- In the 15-pixel icon, the windows seem too close to the building edges.

**Comment by aparlato** [comment]
I'm liking city and town. About to do more work on village. I think it needs to be smaller relative to the other 2.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282326/bba5e46a-c3a8-11e6-80a1-a5d321fbea3c.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282328/c384a5fe-c3a8-11e6-99f8-cbca5ed752c7.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282334/ccbc863c-c3a8-11e6-95ae-aa6c434e114b.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282348/e1d5b110-c3a8-11e6-9426-e9c0ef5872f1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282352/e8a9f94c-c3a8-11e6-851e-0f3c763fe3b2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282353/eebe2b5a-c3a8-11e6-9a98-dff77b2e4540.png)

**Comment by aparlato** [comment]
Changed the village from above comment. I think this works better.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282326/bba5e46a-c3a8-11e6-80a1-a5d321fbea3c.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282328/c384a5fe-c3a8-11e6-99f8-cbca5ed752c7.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282811/45e85dc4-c3ae-11e6-8c25-295388da9ed5.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282348/e1d5b110-c3a8-11e6-9426-e9c0ef5872f1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282352/e8a9f94c-c3a8-11e6-851e-0f3c763fe3b2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282814/4f2b4bf8-c3ae-11e6-89f5-5b2c817d9a95.png)

**Comment by aparlato** [comment]
This was done.
