### ISSUE TITLE
industrial icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#308]
For id-support from #270 

[Industrial on taginfo](http://taginfo.openstreetmap.org/tags/landuse=industrial)

[reference to Maki 1 icon for industrial](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/industrial-24.svg)

icon for landuse:industrial

cc @nickidlugash

**Comment by natslaughter** [comment]
@nickidlugash @bhousel 
I just remembered that Maki already has an [industry](https://github.com/mapbox/maki/blob/master/icons/industry-15.svg) icon that should be used for this `industrial` icon need. 

cc/ @aparlato
