### ISSUE TITLE
mobile-phone icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#311]
For id-support from #270 

[Mobile-phone on taginfo](http://taginfo.openstreetmap.org/tags/?key=shop&value=mobile_phone)

[reference to Maki 1 icon for mobile-phone](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/mobilephone-24.svg)

icon for shop:mobile_phone

cc @nickidlugash

**Comment by aparlato** [comment]
#### Question

I have two options for mobile-phone-11. I think for the actual size it's shown at, the first option is clearer at this point despite being more ambiguous when large.

**11:**

![image](https://cloud.githubusercontent.com/assets/15698320/21117345/046e153e-c06e-11e6-9566-28b27a7c7b0c.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21118358/68e75706-c072-11e6-9a6f-5508ca52b553.png)



**OR**
![image](https://cloud.githubusercontent.com/assets/15698320/21118390/8b65cdda-c072-11e6-9fba-e09b7345e584.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21118375/7785d0da-c072-11e6-952a-535acd950084.png)

**Comment by aparlato** [comment]
#### First draft mobile-phone

15 is starting to feel pretty good. 11 isn't there yet I don't think.

[mobile-phone-11](https://github.com/mapbox/maki/blob/id-support/icons/mobile-phone-11.svg)
[mobile-phone-15](https://github.com/mapbox/maki/blob/id-support/icons/mobile-phone-15.svg)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21123963/da9ad512-c090-11e6-84b3-963c15ba6152.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123966/e08fde2c-c090-11e6-8dc8-21350b72a0e2.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21123974/e820ba76-c090-11e6-93f9-582ef1df0d83.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123981/ef64a0ae-c090-11e6-8d56-21670d517015.png)

**Comment by bhousel** [comment]
@aparlato this looks pretty good, thank you for your work on the icons!

I noticed that the [renders on github](https://cloud.githubusercontent.com/assets/15698320/21123974/e820ba76-c090-11e6-93f9-582ef1df0d83.png) look pretty blurry as opposed to the [raw svgs](https://github.com/mapbox/maki/blob/id-support/icons/mobile-phone-11.svg) that look very crisp.  I have a retina and a non retina screen, and I've compared both png and svg on both screens, and I wonder if there's something in the rasterization step that is introducing bluriness into the icons?  

Any thoughts @natslaughter ?

**Comment by aparlato** [comment]
@bhousel I think that's just because those are screenshots I put in the post for quick viewing, at size and enlarged, and then separate links to the real svg files. If you want, I can do a real export as png if you think it's helpful to have that in addition to the png. In the meantime though, I'll go quickly clarify in the posts that these are screenshots for quick viewing.

**Comment by bhousel** [comment]
@aparlato It's ok, iD renders them as svg in the browser, so they'll look crisp at any size. I just wanted to make sure you weren't stuck on trying to make the 11px pngs look perfect.  Also there's a fast way to export artboard renders from Illustrator that would avoid whatever artifacts the screenshotting is introducing, but I can't remember of the top of my head how to do it.

**Comment by samanpwbb** [comment]
Hi @aparlato! Looks like a good start. One bit of feedback: When possible, the 11px icon should look like a scaled down 15px icon since often the two are used together to represent the same point at different zoom levels on a map. In this case the two icons look a little too different.

**Comment by natslaughter** [comment]
@aparlato 

I'm not sure if github is just reading the .svg code and generating the image, which could explain the difference in clarity between the two images. [raw svgs](https://github.com/mapbox/maki/blob/id-support/icons/mobile-phone-11.svg)  

I think the blurry-ness @bhousel is seeing is due to
- screenshots/pngs from illustrator
- some of the geometry isn't pixel aligned

Here is a diagram showing how just shifting around some of the geometry can make the icon crisper. They might not be the 'ideal' shape or icon close up, but at 100% scale one could argue that it's better to have legibility and crispness. 

<img width="674" alt="screen shot 2016-12-13 at 1 39 45 pm" src="https://cloud.githubusercontent.com/assets/16616543/21153867/49ed7e5c-c13a-11e6-9010-8299af77c37a.png">

<img width="459" alt="screen shot 2016-12-13 at 1 45 04 pm" src="https://cloud.githubusercontent.com/assets/16616543/21153892/61309f2c-c13a-11e6-86f1-25b4c7d3dd19.png">

regarding @samanpwbb 's comment, it seems like you could make the 15 pixel icon have a more vertical screen, similar to the 11 pixel icon.

**Comment by aparlato** [comment]
@samanpwbb Do you think the nine button or four button mobile-phone-15 best fits a scaled up mobile-phone-11 (that has four buttons)? I actually feel like the nine button looks more consistent.

**11** ![image](https://cloud.githubusercontent.com/assets/15698320/21154269/a192a64a-c122-11e6-8644-f0b8ed26265a.png)
**15 four button** ![image](https://cloud.githubusercontent.com/assets/15698320/21154276/a98defe4-c122-11e6-852b-737479ad2db6.png)
**15 9 button** ![image](https://cloud.githubusercontent.com/assets/15698320/21154285/b1b1ec0c-c122-11e6-8956-b41638beed95.png)

Also, does anyone know why mobile-phone-11 is really disappearing with a 0px padding border when it fits in the trim area pretty well?
![image](https://cloud.githubusercontent.com/assets/15698320/21154479/58e74454-c123-11e6-9a30-d4229f637269.png)
<img src="https://cloud.githubusercontent.com/assets/15698320/21154464/4c3d793a-c123-11e6-95aa-a59ea3970c82.png" width=100>

**Comment by samanpwbb** [comment]
I would go with 4 buttons on both.

**Comment by nickidlugash** [comment]
I prefer the nine button – if you blur your eyes a tiny bit, you can see that the proportion of positive and negative space in the nine button is much closer to the 11px version. I think this is more important in terms of seamless transition between the sizes than the actual number of buttons.

**Comment by aparlato** [comment]
**Draft 3**

Rounder corners. I feel like this might lead to a bit of a loss in clarity. The corners were slightly rounded before, so open to thoughts on this.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21246859/29d464ee-c2e0-11e6-88a3-c3ffd372fe40.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21246869/3161baf4-c2e0-11e6-8ab7-3fe1839e1e8e.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21246884/45a47aba-c2e0-11e6-9056-a373d3c019bd.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21246879/3e571f4c-c2e0-11e6-9b18-ec391d60bcef.png)

**Comment by aparlato** [comment]
This was done.
