### ISSUE TITLE
slaughterhouse icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#312]
For id-support from #270 

[Slaughterhouse](http://taginfo.openstreetmap.org/tags/industrial=slaughterhouse)

[reference to Maki 1 icon for slaughterhouse](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/slaughterhouse-24.svg)

icon for industrial:slaughterhouse

cc @nickidlugash

**Comment by natslaughter** [comment]
@aparlato @samanpwbb 

Here is a first pass. 
For the icon-concept, the previous cattle icon drawn at 24x24 is a bit difficult at 11x11. I chose a meat cleaver but am open to other suggestions.

![screen shot 2016-12-14 at 11 47 03 am](https://cloud.githubusercontent.com/assets/16616543/21191505/55de5542-c1f3-11e6-8265-8340f94ec665.png)

**Comment by natslaughter** [comment]
@nickidlugash wanted me to take a stab at drawing some cattle.
It's tricky but it could work with some refinement.  
![screen shot 2016-12-14 at 4 40 20 pm](https://cloud.githubusercontent.com/assets/16616543/21202257/30e68c9a-c21c-11e6-898f-d1174291aa62.png)

cc @aparlato

**Comment by aparlato** [comment]
@natslaughter (house), the cattle look great! I'm torn between the two icons, because I feel like the meat cleaver is less ambiguous in some ways, but it also makes me think butcher before slaughterhouse. 
I wouldn't want to think I'm visiting a butcher and end up in a slaughterhouse. The two are conceptually similar, but very different in terms of whether would I go there for any reason.
Do you think this is a valid concern on the meat cleaver? If so, I'd definitely go with cattle.

**Comment by bhousel** [comment]
> I'm torn between the two icons, because I feel like the meat cleaver is less ambiguous in some ways, but it also makes me think butcher before slaughterhouse.

I'd probably use the meat cleaver for a butcher, but I'm sure I'd find some use for a cow icon.  They both look great..

**Comment by aparlato** [comment]
Two versions

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21333849/eda70762-c620-11e6-9e26-f728251ab9f4.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21333850/f42f53c8-c620-11e6-8d40-f7c5744ba76f.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21333856/fc07b216-c620-11e6-8d8d-920539ba4204.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21333858/0243d2a4-c621-11e6-86ba-834f61f54cf3.png)

_____

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21333868/0e2cc2c4-c621-11e6-9d6d-1fb434f01666.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21333875/139074a4-c621-11e6-9cfe-b0278a4c6647.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21333878/1b1989ae-c621-11e6-81c3-a45f58d2d7e0.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21333883/212ada28-c621-11e6-8782-7e5277aed47e.png)

**Comment by Hufkratzer** [comment]
perhaps

![cow-sm](https://cloud.githubusercontent.com/assets/5958184/21349377/e4e1275c-c6b1-11e6-9a7a-cde09381aee5.jpg)

![cow](https://cloud.githubusercontent.com/assets/5958184/21349192/d0729f36-c6b0-11e6-9840-e1ba08ebe598.jpg)
**?**

**Comment by aparlato** [comment]
This was done.
