### ISSUE TITLE
town icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#313]
For id-support from #270 

[Town on taginfo](http://taginfo.openstreetmap.org/tags/place=town)

[reference to Maki 1 icon for town](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/town-24.svg)

icon for place:town

cc @nickidlugash

**Comment by aparlato** [comment]
#### First draft of town:

[town-11](https://github.com/mapbox/maki/blob/id-support/icons/town-11.svg)

[town-15](https://github.com/mapbox/maki/blob/id-support/icons/town-15.svg)

**11:** ![image](https://cloud.githubusercontent.com/assets/15698320/21123518/1368e396-c08e-11e6-8a8c-b5cbdab70cfa.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123603/92cdf522-c08e-11e6-8a29-7dac904b5001.png)


**15:** ![image](https://cloud.githubusercontent.com/assets/15698320/21123528/2278db98-c08e-11e6-8f35-ca80ad328339.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123595/82e2b670-c08e-11e6-9fe3-bc742f01de74.png)



It would be good to look at these next to [City](https://github.com/mapbox/maki/issues/307) and [Village](https://github.com/mapbox/maki/issues/314)

**Comment by natslaughter** [comment]
@aparlato 
I think these are off to a good start, but primarily need the building voids to be more clear.

**Comment by aparlato** [comment]
**Draft 2**



**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21158172/fea91338-c130-11e6-813c-6e00c8e16202.png)


**15:** 

![image](https://cloud.githubusercontent.com/assets/15698320/21158026/878721be-c130-11e6-90bd-bfbe08f46bac.png)

**Comment by aparlato** [comment]
**To consider:**
![image](https://cloud.githubusercontent.com/assets/15698320/21166817/ccfb1f1c-c15c-11e6-9f36-54f4618b6e78.png)

Posting this from Slack into the ticket.
____
One alternative approach to using the buildings next to each other is to have a single building type to represent each, making a singular icon. Below are a quick look at what that might look like.

City
![image](https://cloud.githubusercontent.com/assets/15698320/21166766/7311b2b8-c15c-11e6-82f5-cf48e166e50a.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21166770/7ad927c4-c15c-11e6-9079-e73fef2f8d2a.png)
____
Town
![image](https://cloud.githubusercontent.com/assets/15698320/21166775/8215ca56-c15c-11e6-87a6-4b5ae457c0bc.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21166781/88d17304-c15c-11e6-8a0e-a007a870d98b.png)

____
Village
![image](https://cloud.githubusercontent.com/assets/15698320/21166784/8fee31fe-c15c-11e6-9d5d-ed1bcb93d1de.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21166790/973ecf7c-c15c-11e6-9ed3-ef03f912678e.png)
____

In the meantime I'm trying to think up other alternatives. @natslaughter suggested circles scaled by population which I like, but I would be concerned that it would not be distinct enough and that it might become confusing having two sizes for each representative circle (but maybe that wouldn't matter).

_posting this same comment to city #307 and village #314_

**Comment by aparlato** [comment]
Thoughts on this approach to city, town, village? (posting to all three tickets)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21209433/1246d60c-c229-11e6-9249-ec1d0b1d27da.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209440/1ba5861c-c229-11e6-897f-af8ea7661dc9.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209446/2495cea8-c229-11e6-8ea5-6803e9cdcd05.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21209460/3ca398c2-c229-11e6-99a3-42caeacf6e7a.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209464/440932ac-c229-11e6-897c-9a75112a0356.png)  ![image](https://cloud.githubusercontent.com/assets/15698320/21209471/4b194dc0-c229-11e6-906d-79543dc97b7c.png)

**Comment by aparlato** [comment]
**Updates from Friday update to village ticket**
Just updating on all three tickets (city, town, village)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282326/bba5e46a-c3a8-11e6-80a1-a5d321fbea3c.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282328/c384a5fe-c3a8-11e6-99f8-cbca5ed752c7.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282811/45e85dc4-c3ae-11e6-8c25-295388da9ed5.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282348/e1d5b110-c3a8-11e6-9426-e9c0ef5872f1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282352/e8a9f94c-c3a8-11e6-851e-0f3c763fe3b2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282814/4f2b4bf8-c3ae-11e6-89f5-5b2c817d9a95.png)

**Comment by aparlato** [comment]
This was done.
