### ISSUE TITLE
village icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#314]
For id-support from #270 

[Village on taginfo](http://taginfo.openstreetmap.org/keys/place%3Avillage)

[reference to Maki 1 icon for village](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/village-24.svg)

icon for place:village

cc @nickidlugash

**Comment by aparlato** [comment]
#### First draft of village:

[village-11](https://github.com/mapbox/maki/blob/id-support/icons/village-11.svg)

[village-15](https://github.com/mapbox/maki/blob/id-support/icons/village-15.svg)

**11:** ![image](https://cloud.githubusercontent.com/assets/15698320/21123552/3f11b716-c08e-11e6-98a3-a66efc431dde.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123583/6c84308e-c08e-11e6-9ddc-fe10aee4f250.png)



**15:** ![image](https://cloud.githubusercontent.com/assets/15698320/21123563/499efea0-c08e-11e6-9748-20af7e2c41b1.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21123578/61ee1770-c08e-11e6-86a4-1b802fc42bee.png)



It would be good to look at these next to [City](https://github.com/mapbox/maki/issues/307) and [Town](https://github.com/mapbox/maki/issues/313)

**Comment by natslaughter** [comment]
@aparlato 
I think these are off to a good start, but primarily need the building voids to be more clear.

**Comment by aparlato** [comment]
**Draft 2**



**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21158293/8af3f470-c131-11e6-9b51-aa6ddc9401fa.png)


**15:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21158295/924a8ae0-c131-11e6-970b-f597bd3e7ff4.png)

**Comment by aparlato** [comment]
**To consider:**
![image](https://cloud.githubusercontent.com/assets/15698320/21166817/ccfb1f1c-c15c-11e6-9f36-54f4618b6e78.png)

Posting this from Slack into the ticket.
____
One alternative approach to using the buildings next to each other is to have a single building type to represent each, making a singular icon. Below are a quick look at what that might look like.

City
![image](https://cloud.githubusercontent.com/assets/15698320/21166766/7311b2b8-c15c-11e6-82f5-cf48e166e50a.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21166770/7ad927c4-c15c-11e6-9079-e73fef2f8d2a.png)
____
Town
![image](https://cloud.githubusercontent.com/assets/15698320/21166775/8215ca56-c15c-11e6-87a6-4b5ae457c0bc.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21166781/88d17304-c15c-11e6-8a0e-a007a870d98b.png)

____
Village
![image](https://cloud.githubusercontent.com/assets/15698320/21166784/8fee31fe-c15c-11e6-9d5d-ed1bcb93d1de.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21166790/973ecf7c-c15c-11e6-9ed3-ef03f912678e.png)
____

In the meantime I'm trying to think up other alternatives. @natslaughter suggested circles scaled by population which I like, but I would be concerned that it would not be distinct enough and that it might become confusing having two sizes for each representative circle (but maybe that wouldn't matter).

_posting this same comment to town #313 and city #307_

**Comment by aparlato** [comment]
Thoughts on this approach to city, town, village? (posting to all three tickets)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21209433/1246d60c-c229-11e6-9249-ec1d0b1d27da.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209440/1ba5861c-c229-11e6-897f-af8ea7661dc9.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209446/2495cea8-c229-11e6-8ea5-6803e9cdcd05.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21209460/3ca398c2-c229-11e6-99a3-42caeacf6e7a.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21209464/440932ac-c229-11e6-897c-9a75112a0356.png)  ![image](https://cloud.githubusercontent.com/assets/15698320/21209471/4b194dc0-c229-11e6-906d-79543dc97b7c.png)

**Comment by natslaughter** [comment]
@aparlato 
These look great!
Looking at the existing Maki catalogue, there are no icons that have multiple objects that are separated with a white line. 
I would be open to a discussion on whether or not these are similar to Maki, or too different.

cc @samanpwbb @nickidlugash

**Comment by aparlato** [comment]
@natslaughter Sounds good. I thought having them look crowded in this way made it resemble a single icon more than the first effort, which was based on Maki 1. I'd love to brainstorm/hear other alternative ideas when we discuss this as well.

**Comment by natslaughter** [comment]
![image](https://cloud.githubusercontent.com/assets/15698320/21248417/cfd08278-c2eb-11e6-9b70-4fe638c32c7a.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248423/d5f8ce44-c2eb-11e6-8004-693c5fff18a8.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248426/dbee0918-c2eb-11e6-9d93-9f4d890538e1.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21248434/ef0db2be-c2eb-11e6-80ca-0f1fa5047f89.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248440/f679bff2-c2eb-11e6-9f72-f669b9795b04.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248443/ff9c4a6e-c2eb-11e6-8f12-a9aadcf6d572.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21248454/1031951e-c2ec-11e6-8209-4a4d5ba1bade.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248458/159ca1ce-c2ec-11e6-985a-7c0136dc3612.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248462/1a53c3f0-c2ec-11e6-838e-d8857ed8c0ba.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21248471/296a1024-c2ec-11e6-9c38-3074898e63f2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248473/32d66b4e-c2ec-11e6-9281-6afa5426ab50.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21248484/3e72664c-c2ec-11e6-8be3-a87630239908.png)

**Comment by natslaughter** [comment]
@aparlato 

I think this one needs the most work, and is conceptually different from the city and town icons. The village icons seem more "overlapping," which I think could work, but we need to pick one strategy. I am guessing there wasn't enough space for side by side placement due to the roof? 
The back building's relationship to the front is awkward, however it almost reads in the 15 pixel icon. The 11 pixel is a little confusing. 
I would recommend another iteration and just more time hashing out the details.

**Comment by aparlato** [comment]
**Updates from Friday update to village ticket**
Just updating on all three tickets (city, town, village)

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282326/bba5e46a-c3a8-11e6-80a1-a5d321fbea3c.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282328/c384a5fe-c3a8-11e6-99f8-cbca5ed752c7.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282811/45e85dc4-c3ae-11e6-8c25-295388da9ed5.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21282348/e1d5b110-c3a8-11e6-9426-e9c0ef5872f1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282352/e8a9f94c-c3a8-11e6-851e-0f3c763fe3b2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282814/4f2b4bf8-c3ae-11e6-89f5-5b2c817d9a95.png)

**Comment by aparlato** [comment]
**Update to village**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21321958/fee672ba-c5e4-11e6-8256-580a577b892e.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21322000/27879b40-c5e5-11e6-849a-b57fecf674d8.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21321972/09dbfda2-c5e5-11e6-85ad-627b11ac0675.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21322004/2f4ad34c-c5e5-11e6-8797-9750dcbb163f.png)

____
![image](https://cloud.githubusercontent.com/assets/15698320/21282326/bba5e46a-c3a8-11e6-80a1-a5d321fbea3c.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282328/c384a5fe-c3a8-11e6-99f8-cbca5ed752c7.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21321958/fee672ba-c5e4-11e6-8256-580a577b892e.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21282348/e1d5b110-c3a8-11e6-9426-e9c0ef5872f1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282352/e8a9f94c-c3a8-11e6-851e-0f3c763fe3b2.png)![image](https://cloud.githubusercontent.com/assets/15698320/21321972/09dbfda2-c5e5-11e6-85ad-627b11ac0675.png)

**Comment by aparlato** [comment]
Based on discussion with @natslaughter and @nickidlugash I tried to take the eaves of of the building in the back to allow room for a detail. So far this doesn't seem to be making it more clear and it makes it more similar to the town icons. I will post again after a couple more renditions.
**before** ![image](https://cloud.githubusercontent.com/assets/15698320/21329431/a27b9f4c-c606-11e6-80d0-ae0039ee0c3e.png)

**after** ![image](https://cloud.githubusercontent.com/assets/15698320/21329416/8decd4ec-c606-11e6-9b18-e70fb5938b0f.png)
____
**town-11** ![image](https://cloud.githubusercontent.com/assets/15698320/21329447/bc6b3156-c606-11e6-9806-f35c86a41239.png)

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21331238/50595c0a-c60f-11e6-916c-b8f42e82ee3b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21331248/5b0160f8-c60f-11e6-8eed-efca85037e8c.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21331260/665a98ca-c60f-11e6-97ae-7802c40d5965.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21331266/6e2a7db8-c60f-11e6-9bae-17a651d31c31.png)
____
city, town, village

![image](https://cloud.githubusercontent.com/assets/15698320/21282326/bba5e46a-c3a8-11e6-80a1-a5d321fbea3c.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282328/c384a5fe-c3a8-11e6-99f8-cbca5ed752c7.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21331238/50595c0a-c60f-11e6-916c-b8f42e82ee3b.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21282348/e1d5b110-c3a8-11e6-9426-e9c0ef5872f1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21282352/e8a9f94c-c3a8-11e6-851e-0f3c763fe3b2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21331260/665a98ca-c60f-11e6-97ae-7802c40d5965.png)

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21370395/6c82f4d4-c6d9-11e6-875d-54d1510e274a.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21370782/99c414d0-c6db-11e6-9691-8302f58f5800.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21370411/800eda9a-c6d9-11e6-8086-aa89fccff43b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21370776/8fda9462-c6db-11e6-86f6-07ef2d965a76.png)

Revised in accordance with Maki sync today (eaves on back house, no eaves on front house, only front house has chimney)

My only hesitance is when blown up a little the angles look kind of off. I've checked them so they are not off, but I think it's because of where they meet each other and the contrast of differently angled roofs.

Thoughts?

cc @nickidlugash 
cc @natslaughter

**Comment by aparlato** [comment]
This was done.
