### ISSUE TITLE
park-alt1 icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#315]
For id-support from #270 

[reference to ticket 296 in maki-icons repo about naming alternative icons](https://github.com/mapbox/maki/issues/296)

alternative icon for landuse:park
may be used for landuse: forest, landuse: orchard, landuse: wood

cc @nickidlugash

**Comment by nickidlugash** [comment]
Let's test out the [alternate icon naming convention here](https://github.com/mapbox/maki/issues/296)? /cc @natslaughter

**Comment by aparlato** [comment]
**First draft**

Currently using a pine tree because it's distinguished from our main park icon tree, it's distinctive in general, and it fits for landuse:forest and landuse:wood well (landuse:orchard not so much).

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21166603/68f1b25c-c15b-11e6-8982-7771d40c8fe8.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21166623/73c81e64-c15b-11e6-839c-e211e8b28b44.png)

**Comment by natslaughter** [comment]
@aparlato 
Nice start!
I think the 15 pixel is looking good. Similar to the `entrance-alt1` icon comment, I'm seeing circles being used to create corners that are a bit off. 
The 11-pixel icon is a bit blurry, and creating more white space around the edges would help.
If you look in pixel-preview, the edges are more grey than white:

![screen shot 2016-12-14 at 9 19 39 am](https://cloud.githubusercontent.com/assets/16616543/21185545/17270600-c1df-11e6-9b07-036337fe1ad3.png)

One crude trick is putting white squares in pixels you want to be white. It makes the icon look horrible, but it reads well at 100% scale. 

![screen shot 2016-12-14 at 9 32 55 am](https://cloud.githubusercontent.com/assets/16616543/21185849/52abb09e-c1e0-11e6-9486-17ed0f5e78b7.png)

However, people should be able to use Maki at larger scales if they want, so perhaps a more elegant solution is required.

**Comment by aparlato** [comment]
**Draft 2**

@natslaughter I also changed 15 as well to keep the icons consistent with each other. Definitely looks better at size, but up close they are not very pretty. I tried to make it a little nicer looking blown up, but, the choice as-is, I think this will be a bit of a compromise either way.

I think I can make this look better still, although what's posted here is going to be close to the look, as the points on either side are too small to round with a .5px minimum and the curves are awkward to get that pixel of white space, so those are the limitations at the moment.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21203237/79b16b36-c206-11e6-8b86-5ba508c5ae8e.png) 
![image](https://cloud.githubusercontent.com/assets/15698320/21203292/ae28d534-c206-11e6-9199-4b02e4c56cca.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21203250/82859e8a-c206-11e6-8a30-2a42addcc37c.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21203303/b8299a82-c206-11e6-8213-4374df11779b.png)

**Comment by aparlato** [comment]
^ update: _slightly_ better.

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21204693/72be01b6-c20d-11e6-8b5c-039913d7669e.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21204730/9177850a-c20d-11e6-9f25-08a170f0f4c5.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21204707/7eb12e08-c20d-11e6-853c-93813bfd8ba1.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21204717/894e125e-c20d-11e6-9262-b5f173a2d26b.png)

**Comment by aparlato** [comment]
I'm actually leaning toward sticking with the first draft icon (cleaned up) because with a background, the newer versions are almost unreadable + there's the benefit of looking good blown up. Thoughts? 
**11:**
old ![image](https://cloud.githubusercontent.com/assets/15698320/21206672/6e321780-c218-11e6-8565-d41d2fb12df3.png) **vs**  ![image](https://cloud.githubusercontent.com/assets/15698320/21206714/a7b4fdce-c218-11e6-8387-51421b41f339.png) new

**15:**
old ![image](https://cloud.githubusercontent.com/assets/15698320/21206764/dcecc6ca-c218-11e6-93ea-9d2b10dbd1b7.png) **vs** ![image](https://cloud.githubusercontent.com/assets/15698320/21206773/ea1dedec-c218-11e6-9229-cf95cd6a0549.png) new

**Comment by aparlato** [comment]
**Draft 3**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21207015/63bc5dae-c21a-11e6-96a6-1bea41218238.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21207083/d2c1ef5c-c21a-11e6-94f5-1ffd11acb108.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21207045/9b8149c0-c21a-11e6-9763-fdc5aaf913ab.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21207038/92a48db2-c21a-11e6-987c-803f1d3d0fc4.png)

**Comment by aparlato** [comment]
**Draft 5**

I changed the 11px to look a little taller when blown up to match better with the 15px.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21318111/e50b5478-c5d5-11e6-8a03-5b671c2c5594.png)

![image](https://cloud.githubusercontent.com/assets/15698320/21318100/dd112c48-c5d5-11e6-8c04-814d6593ccf1.png)
**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21318129/f856663a-c5d5-11e6-90b7-95ab2d17ae33.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21318140/0107df34-c5d6-11e6-8dcc-f123221e21e7.png)

**Comment by natslaughter** [comment]
@aparlato 
![screen shot 2016-12-19 at 12 07 46 pm](https://cloud.githubusercontent.com/assets/16616543/21321675/d0eaa58a-c5e3-11e6-84dd-1475eab49357.png)

**Comment by aparlato** [comment]
**11px revision**

![image](https://cloud.githubusercontent.com/assets/15698320/21323529/e7678852-c5eb-11e6-8729-20d7e7031d07.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21323535/edd259e2-c5eb-11e6-8823-7e2fab80776c.png)
Brought in to fix grey pixels.
![image](https://cloud.githubusercontent.com/assets/15698320/21323542/fa1bda7a-c5eb-11e6-8442-618ea279db8a.png)

**Comment by aparlato** [comment]
**New 11px**

More clarity, fewer "triangles."

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21327875/2c2c85ce-c5ff-11e6-82f2-0ce6a3fb4f05.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21327882/34e07e00-c5ff-11e6-96e4-bd78442b2f03.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21318129/f856663a-c5d5-11e6-90b7-95ab2d17ae33.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21318140/0107df34-c5d6-11e6-8dcc-f123221e21e7.png)

**Comment by nickidlugash** [comment]
I think three triangles for the 11px works well 👍  Can the stem between the bottom and middle triangles be slightly thicker?

**Comment by aparlato** [comment]
This was done.
