### ISSUE TITLE
barrier icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#316]
For id-support from #270 

[Barrier on taginfo](http://taginfo.openstreetmap.org/keys/barrier)

[reference of prison icon from maki 1 which we were using for most barriers as well](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/prison-24.svg)

[reference for prison icon currently in use](https://github.com/mapbox/maki/blob/master/icons/prison-15.svg)

icon for barrier: (key)

cc @nickidlugash

**Comment by aparlato** [comment]
**First Draft**

First draft is based on the Maki 1 icon which looks like a fence and is now differentiated from the newer [prison icon](https://github.com/mapbox/maki/blob/master/icons/prison-15.svg). I think I may want to revisit this tonight or tomorrow and come up with another solution, but I think starting with the translation of the Maki 1 gate will help to make decisions next to if going a new direction.

Also, debating whether for this set if barrier-15 feels too thick.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21166465/91bd9710-c15a-11e6-84ec-2cbf2e1f2c2e.png)


**15:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21166473/9a5a4012-c15a-11e6-9a16-e7669bb8d061.png)

**Comment by natslaughter** [comment]
@aparlato 
These look good, although when I pulled them up in illustrator, the spaces in-between the fence elements weren't reading on a non-retina screen. 
Looking at the barrier tag info, this icon is used for a wide variety of barriers from fences to hedges. Would using a more general icon concept like this be appropriate? It's used for barriers, but sometimes construction sites. It might be too much. 

![image](https://cloud.githubusercontent.com/assets/16616543/21185132/68385884-c1dd-11e6-9276-61828cea2869.png)

**Comment by bhousel** [comment]
@natslaughter In iD I've been using the maki1 "roadblock" icon as a generic "barrier" tag, also for things like bollards, stiles, lift gates, etc.

<img width="364" alt="screen shot 2016-12-14 at 9 21 31 am" src="https://cloud.githubusercontent.com/assets/38784/21185521/01780872-c1df-11e6-8650-b028190a95be.png">

**Comment by aparlato** [comment]
@bhousel @natslaughter So should we break this icon up into two based on @bhousel 's comment do you think? I'll make a pass at the more general barrier from @natslaughter 's comment to start.

**Comment by natslaughter** [comment]
@aparlato
Maki already has this exact 'barrier' icon, although it's called [roadblock](https://github.com/mapbox/maki/blob/master/icons/roadblock-15.svg)

**Comment by aparlato** [comment]
**Draft 2**

I actually really like the barrier @natslaughter suggested. Here's how that looks.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21199908/496958be-c1fa-11e6-94bf-813e01175245.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21199917/505c013a-c1fa-11e6-95bf-9e2d57b904a3.png)

**Comment by natslaughter** [comment]
@aparlato 
These look amazing.
We should definitely use this somewhere, if we end up sticking with the existing barrier icon.

**Comment by aparlato** [comment]
**Draft 3**

Just rounded the sign corners.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21283195/46203dc0-c3b3-11e6-826a-17a8de7adccd.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21283196/4cfe8aa2-c3b3-11e6-98d1-d4665ff49a09.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21283200/541dcece-c3b3-11e6-9d77-720f9d701fdd.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21283201/5b5b94b4-c3b3-11e6-8702-7a9083311168.png)

**Comment by aparlato** [comment]
I added another line crossing in the 15px sign's design to resolve the issue of too much negative space creating an awkward space when used with a stroke in the Maki editor.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21328822/b58d03bc-c603-11e6-8e75-51a7ec4e633f.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21328829/bbe0f174-c603-11e6-88e4-347c0ba00159.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21328843/c7d39ebe-c603-11e6-9367-233dfc3b3078.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21328853/cefc0c3a-c603-11e6-89ae-b373d958dc7d.png)

**Comment by aparlato** [comment]
This was done.
