### ISSUE TITLE
entrance-alt1 icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#317]
For id-support from #270 

[Entrance on taginfo](http://taginfo.openstreetmap.org/keys/entrance)

[reference to Maki 1 icon for entrance](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/entrance-24.svg)

[reference to current entrance icon](https://github.com/mapbox/maki/blob/master/icons/entrance-15.svg)

We need an entrance icon for buildings, parking garages, etc. instead of only escalators for subway entrances.

icon for entrance: (key)

cc @nickidlugash

**Comment by nickidlugash** [comment]
@aparlato We already have an [`entrance` icon](https://github.com/mapbox/maki/blob/master/icons/entrance-11.svg). Let's test out the [alternate icon naming convention here](https://github.com/mapbox/maki/issues/296)? /cc @natslaughter

**Comment by aparlato** [comment]
**First draft**

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21166665/d06a2b4e-c15b-11e6-912a-5852279542bd.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21166674/dbf9a7fa-c15b-11e6-954f-725037848572.png)

**Comment by natslaughter** [comment]
@aparlato 
Looks good. Not to send us down a rabbit hole, but I wonder if there is another style of arrow we could use. The one you used is probably best as it reads well. 

I noticed that your rounded corners are separate circles:

![screen shot 2016-12-14 at 8 59 16 am](https://cloud.githubusercontent.com/assets/16616543/21184693/9c8c6b0e-c1db-11e6-808f-6ab753e12a64.png)

Eventually we will need the icon to be a single path, but the circles are also causing the corners to be a little jagged:

![screen shot 2016-12-14 at 8 57 36 am](https://cloud.githubusercontent.com/assets/16616543/21184726/c12b716c-c1db-11e6-84ed-baec1c3b7a49.png)

And just a minor detail:

![screen shot 2016-12-14 at 8 57 56 am](https://cloud.githubusercontent.com/assets/16616543/21184740/cf8041c0-c1db-11e6-918d-6249c11cb195.png)

**Comment by nickidlugash** [comment]
@aparlato @natslaughter none of our icons use perspective (this is in our design guidelines). Do you two feel like this icon can justify the deviation?

**Comment by natslaughter** [comment]
@aparlato 
@nickidlugash has a good point.
I've seen this icon in 2D where the door is simply a rectangle with the same opening for the arrow. 
Want to try that?

**Comment by aparlato** [comment]
**Draft 2**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21206431/cac70c6e-c216-11e6-8ca3-c938ce2a3625.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21206457/f9aa8182-c216-11e6-96e2-e114560be12d.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21206435/d20b57be-c216-11e6-9938-de8133b1b3e5.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21206444/dd6c5e28-c216-11e6-8a7a-4fa940948924.png)

**Comment by natslaughter** [comment]
@aparlato 
The 2d approach is working a lot better. 

I think it would be nice to use a more contemporary arrow like this, but with a slightly longer stem:
![image](https://cloud.githubusercontent.com/assets/16616543/21228986/fcd61f5a-c2ad-11e6-9c1f-149fcb13329c.png)

Regarding the door, I like the thinner line weight, but the end nubs need to be the same: 

![screen shot 2016-12-15 at 10 14 00 am](https://cloud.githubusercontent.com/assets/16616543/21229358/5947956a-c2af-11e6-8e87-65eee3d1371e.png)

**Comment by aparlato** [comment]
**Draft 3**

Sorry about that! the missing round curve was an oversight. Let me know what you think of new and improved arrow. 
I tried to go a little thicker with the 15 arrow, but found it awkward so I brought it back to the same line thickness as 11 but all lines longer.

**Also** do you think I should keep the rounded corners on the rectangle considering the new arrow? Or I was thinking of keeping the rounded corners, but getting rid of the rounded line caps.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21234187/9a078dc0-c2a6-11e6-9ab1-9a5490d21625.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21234202/a2fe1c00-c2a6-11e6-8d05-6aadd71e5951.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21234211/ac38cc7a-c2a6-11e6-965e-6a86bde34105.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21234219/b5b744de-c2a6-11e6-9a72-bafd360972e0.png)

**Comment by natslaughter** [comment]
@aparlato 
Thanks for trying that out, but I'm not seeing much difference at 100% scale, and we should probably stick to the rounded ends. Sorry.

**Comment by aparlato** [comment]
**Draft 4**

@natslaughter all good, here's a better version of the rounded arrow.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21235806/30c87462-c2ad-11e6-936f-25fbc5664ff0.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21235817/3a1cb096-c2ad-11e6-8860-c6b06597caa6.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21235825/42e8cd18-c2ad-11e6-868d-14cda31f1b2d.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21235830/4a7e71d6-c2ad-11e6-95a7-142c568445e9.png)

**Comment by aparlato** [comment]
**Draft 5**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21246589/92be64de-c2de-11e6-87c6-2298f28d2285.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21246599/9b6a2dd4-c2de-11e6-8d3d-5557f1895265.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21246614/aace96ac-c2de-11e6-9247-bd3a1cba5579.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21246623/b0ece23c-c2de-11e6-8ad1-a7ef6f3d1336.png)

**Comment by natslaughter** [comment]
@aparlato 
the 11 pixel icon is looking sharp.

**Comment by natslaughter** [comment]
@aparlato 
I think the main issue is the door proportions. The 11-pixel door is very square, whereas the 15-pixel is very rectangular. This might take some finessing on your part, but try extending the 15-pixel's horizontal door elements a few pixels further to see if that helps it get more square. 
Here are some additional comments:

![screen shot 2016-12-16 at 3 05 55 pm](https://cloud.githubusercontent.com/assets/16616543/21276969/fbc44f66-c3a1-11e6-8088-814cb101a1e2.png)

![screen shot 2016-12-16 at 3 08 42 pm](https://cloud.githubusercontent.com/assets/16616543/21276970/ff222d5e-c3a1-11e6-82de-f324a42a5573.png)

**Comment by aparlato** [comment]
**Draft 6**

I think this looks pretty good. Two possible concerns: 
1) By shortening the arrow's pointed end's strokes, it has begun to feel more like a solid triangle element at the end of a stick rather than a stick arrow at scale.
2) I'm not sure whether to keep the ends of the open rectangle in the 15px coming around the last corner or terminating before turning towards each other like in the 11px version.

Thoughts on these concerns?

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21280049/8640226e-c398-11e6-82d8-24f72adbc05d.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21280061/921d7956-c398-11e6-9701-1cfcebaac8d8.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21280068/a1f2a8b0-c398-11e6-86ef-342194d94084.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21280077/abcb9694-c398-11e6-8e74-c60105a0df9d.png)

**Comment by natslaughter** [comment]
@aparlato 
I see what you're saying about the 11-pixel arrow looking more like a solid triangle: my bad.
Please revert to the 11-pixel arrow ends extending into the adjacent left pixels.

**Comment by aparlato** [comment]
@natslaughter Can do. In the meantime, how do we feel about the 15px more open without the last corners rounding towards each other to better mimic the 11px?

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21323099/04090fb4-c5ea-11e6-8f42-4a9cf127d950.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21323107/0b0468ea-c5ea-11e6-81bb-0d174d77208a.png)

**Comment by aparlato** [comment]
**11px reverted**

![image](https://cloud.githubusercontent.com/assets/15698320/21323264/a2d426ba-c5ea-11e6-9193-a78764633622.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21323273/abab6744-c5ea-11e6-9c85-13e0b2e4b5f9.png)

The arrow's end triangle strokes have been re-extended and the point brought back some to allow a pixel of white space between all the arrow's lines for clairty.
![image](https://cloud.githubusercontent.com/assets/15698320/21323290/b8ca4ab2-c5ea-11e6-9e84-974af2635027.png)

**Comment by aparlato** [comment]
This was done.
