### ISSUE TITLE
defibrillator icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#318]
For id-support from #270 

[Defibrillator on taginfo](http://taginfo.openstreetmap.org/tags/emergency=defibrillator)

see #104 request for AED / defibrillator.

icon for emergency:defibrillator

cc @nickidlugash

**Comment by natslaughter** [comment]
@aparlato 
Here is the first draft.
The icon concept is based on [this icon](http://josm.openstreetmap.de/attachment/ticket/8849/aed.2.svg), which was in the #104 ticket

My initial thoughts are:
Having the 'electrical bolt' within the heart makes this icon be specific to defibrillators, however it doesn't read as a bolt at the 11 pixel scale and might cause confusion. Maybe being accompanied by the 'plus' sign helps clear up any confusion. I'm considering removing the bolt.

<img width="132" alt="screen shot 2016-12-13 at 2 59 55 pm" src="https://cloud.githubusercontent.com/assets/16616543/21156945/a474328e-c145-11e6-96d2-e20f81f3ca7d.png">

cc @nickidlugash @samanpwbb

**Comment by aparlato** [comment]
@natslaughter nice! The heart looks really good, but I also definitely can't read the bolt at 11 (15 is fairly legible though).

I'd be wary of removing the bolt though as I think that the bolt is actually the main indicator that this is a defibrillator/AED while just the heart with a plus is used for a variety of general first aid purposes. 

Maybe get rid of the plus and just use the heart with the bolt outside? Or maybe without the plus, the heart can be larger and house the bolt in a clearer way. Either way, I think the bolt might be essential.

**Comment by samanpwbb** [comment]
can you do just a heart with a bolt, drop the +?

**Comment by natslaughter** [comment]
@aparlato @samanpwbb 

Second pass using the heart+bolt concept

The main issue is the bolt's illegibility. I'll keep massaging it, but here are two approaches:
- Big heart with the bolt inside
- Heart with the bolt in the upper right corner

![screen shot 2016-12-14 at 10 36 52 am](https://cloud.githubusercontent.com/assets/16616543/21188528/b322fafa-c1e9-11e6-8c78-59710c719904.png)

**Comment by nickidlugash** [comment]
Another potential option: heart with EKG reading? Not sure how widely used this is versus the heart with lightning bolt.

![](http://www.fenlandfirstaid.co.uk/wp-content/uploads/2015/08/bespoke-icon-heart.png)

**Comment by aparlato** [comment]
I think the bolt inside the heart reads best as defibrillator, partially because it feels like an individual symbol. Both work great at 15. When the bolt is separated, I am more open to interpretation when it's 11px and not 100% clear.

**Comment by aparlato** [comment]
This was done.
