### ISSUE TITLE
generic landuse icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#319]
For id-support from #270 

[Landuse on taginfo](http://taginfo.openstreetmap.org/keys/landuse#overview)

[reference to Maki 1 icon for landuse](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/land-use-24.svg)

icon for landuse: (key)

cc @nickidlugash

**Comment by aparlato** [comment]
**First Draft**

Based loosely on Maki 1 icon.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21208321/37698526-c222-11e6-9ec1-d4229409a28b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21208326/401f2482-c222-11e6-8dd8-8ea98f5c3e9a.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21208330/46e6eade-c222-11e6-8f72-03eba4e4c316.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21208335/4fd993bc-c222-11e6-9736-0b79969df793.png)

**Comment by aparlato** [comment]
Alternative:
Does this make sense over the previous one? Are there any other thoughts? I actually prefer the first draft, but this one is more consistent with Maki.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21333808/9b135456-c620-11e6-93a3-3b5092c1f83d.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21333814/a129b4ac-c620-11e6-982c-34c2e7034f24.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21333818/a97e0edc-c620-11e6-97de-23a517a6a029.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21333825/aed7e52e-c620-11e6-8686-0c3c58f376eb.png)

**Comment by nickidlugash** [comment]
I think that either version of the tree works – I don't think it necessarily needs to look exactly like a tree that we've used in other icons.

The factory in the bottom/house on the top is starting to work well I think. Perhaps the factory could be a little more [factory-like](https://www.google.com/search?q=factory+icon&biw=1392&bih=891&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjSlMapuoPRAhUM6YMKHbXADOYQ_AUIBigB)?

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21367246/6608d9ba-c6cb-11e6-8757-5142b1bdf52b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21367253/6ec59340-c6cb-11e6-9e88-46e48e7e7051.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21367441/2e171a16-c6cc-11e6-9ae9-c1436e139be9.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21367447/3768f13e-c6cc-11e6-81d6-a0ba111b0120.png)

In the 15px, the industrial triangles are made tall to prevent awkward negative space when it receives a 1px stroke.


cc @nickidlugash 
cc @natslaughter

**Comment by natslaughter** [comment]
@aparlato 
The 15-pixel industrial shape seems a bit busy and at 100% scale, doesn't read as two triangles and two strokes. Maybe using just one triangle would suffice? Also, having the triangles and the strokes at different heights might help differentiate between the two. 

The 11-pixel icon might also want one triangle and different heights between the triangle and stroke.

**Comment by aparlato** [comment]
I think this is better although the industrial piece is still slightly ambiguous.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21368314/11c9ee8e-c6d0-11e6-8dfe-529d9b6635fb.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21368317/19a759e8-c6d0-11e6-8c5e-7b68eeea6de2.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21368320/21604528-c6d0-11e6-9840-20c8e702fadd.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21368326/294e49c4-c6d0-11e6-99fc-6f2ec561a8a8.png)

**Comment by aparlato** [comment]
This was done.
