### ISSUE TITLE
fence icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#324]
For id-support from #270 

[Fence on taginfo](http://taginfo.openstreetmap.org/tags/barrier=fence)
[Gate on taginfo](http://taginfo.openstreetmap.org/tags/barrier=gate)

[reference of prison icon from maki 1 which we were using for most barriers/fences as well](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/prison-24.svg)

[reference for prison icon currently in use](https://github.com/mapbox/maki/blob/master/icons/prison-15.svg)

icon for barrier: fence, barrier:gate, and similar items.

cc @nickidlugash

**Comment by aparlato** [comment]
**First draft**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21278915/84678122-c392-11e6-961b-0e5ad23270cb.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21278934/a39734d4-c392-11e6-9585-c64498808e0d.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21278925/92bd3c76-c392-11e6-94e3-78cc77a5fcf8.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21278930/99db5cea-c392-11e6-8a1c-5a74ec8e8365.png)

**Comment by Hufkratzer** [comment]
This kind is only used inside of villages I think. Larger fences look different, see:
- https://wiki.openstreetmap.org/wiki/Tag:barrier=fence
- https://en.wikipedia.org/wiki/Fence
- https://commons.wikimedia.org/wiki/Category:Agricultural_fences
- https://commons.wikimedia.org/wiki/Category:Horse_fences
- https://josm.openstreetmap.de/browser/trunk/images/presets/barrier/fence.svg

**Comment by aparlato** [comment]
This is done.
