### ISSUE TITLE
florist icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#330]
There is a need for a florist icon to distinguish between `garden`, `garden center` and `store`. 

[Here](http://taginfo.openstreetmap.org/search?q=florist#keys) is the OSM tag information.

As for image references, last June this icon was started but not finished:
______
![screen shot 2016-12-22 at 11 59 41 am](https://cloud.githubusercontent.com/assets/16616543/21433814/52e4bc6c-c83f-11e6-972d-0eab2ee7280f.png)
______
I would recommend something along these lines that isn't JUST a flower. A single flower could suggest a `garden` or `nursery`. Having some icon element that distinguishes it from these other two would be great to have. 

cc / @aparlato

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21435963/537a134c-c84a-11e6-9b0f-d3db249b1363.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21435972/59f488c4-c84a-11e6-9401-f10e26005096.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21435978/600c5138-c84a-11e6-80cc-5e3d0253cf0b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21435986/665dd804-c84a-11e6-9cb9-96f68e1d6b6c.png)

**Comment by natslaughter** [comment]
@aparlato 
These look great! Nice use of the diagonal orientation.

**Comment by nickidlugash** [comment]
This was done.
