### ISSUE TITLE
communication-tower icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#337]
As per request from @valleyofdawn

**Taginfo:**

key
[communication: radio](http://taginfo.openstreetmap.org/keys/communication:radio)
[communication: mobile phone](http://taginfo.openstreetmap.org/keys/communication:mobile_phone)
and/or
[list of appropriate tags](https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dcommunication)

**Comment by natslaughter** [comment]
Here is the current state of the communication-tower icons:

11-pixels
![screen shot 2016-12-23 at 2 23 40 pm](https://cloud.githubusercontent.com/assets/16616543/21460979/7e43dbea-c91b-11e6-8b16-2bcdf6af6aeb.png)

15-pixels
![screen shot 2016-12-23 at 2 23 30 pm](https://cloud.githubusercontent.com/assets/16616543/21460978/7b68c570-c91b-11e6-8178-0e6f9c4c1d08.png)

**Comment by tristen** [comment]
This was done in #445
