### ISSUE TITLE
Observation tower

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#339]
As per request from @valleyofdawn

**Taginfo:**

key
[observation:](http://taginfo.openstreetmap.org/keys/observation)
and/or
[list of appropriate tags](https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dobservation)

**Comment by natslaughter** [comment]
Here is the current state of the observation-tower icons:

11-pixels
![screen shot 2016-12-23 at 2 35 17 pm](https://cloud.githubusercontent.com/assets/16616543/21461154/11d683a2-c91d-11e6-93a0-558057221aed.png)

15-pixels
![screen shot 2016-12-23 at 2 35 10 pm](https://cloud.githubusercontent.com/assets/16616543/21461155/162dbcea-c91d-11e6-9d2c-848b8b65c0d3.png)

**Comment by tristen** [comment]
Done in https://github.com/mapbox/maki/pull/548
