### ISSUE TITLE
waterfall icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#343]
As per request from @valleyofdawn

**Taginfo:**

[list of appropriate tags](https://wiki.openstreetmap.org/wiki/Waterfalls)

**Comment by natslaughter** [comment]
Here is the current state of the waterfall icons:

11-pixels
![screen shot 2016-12-23 at 2 50 58 pm](https://cloud.githubusercontent.com/assets/16616543/21461402/4886cf5e-c91f-11e6-9e0a-754e0ac80c86.png)

15-pixels
![screen shot 2016-12-23 at 2 50 50 pm](https://cloud.githubusercontent.com/assets/16616543/21461407/4e08f434-c91f-11e6-92d5-2458a13e17c7.png)

**Comment by aparlato** [comment]
Here are a couple of iterations I'm working on. I think iteration 2 is _starting_ to show some promise but is not there yet for sure.

### Iteration 1

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22220118/452a7332-e162-11e6-9356-9e2d78bbc205.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22220123/4c020c10-e162-11e6-87b5-0e5bc7ff4294.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22220134/55bfbdd8-e162-11e6-8e74-1efe93ccc6b4.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22220142/5ce72fd8-e162-11e6-8ea8-8fb0cdd250af.png)


### Iteration 2

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22220167/724fbe1c-e162-11e6-8368-271edb596246.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22220176/7bd977c0-e162-11e6-8244-5ecbd02f1b2f.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22220189/8693cefe-e162-11e6-9343-c3b12c7bbebe.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22220196/8ddb5f1a-e162-11e6-95eb-c05662559e0b.png)

**Comment by aparlato** [comment]
Still looking very ambiguous. :confused:

![image](https://cloud.githubusercontent.com/assets/15698320/22220748/cd261942-e164-11e6-8493-2d37a125cbdd.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22220757/d48afe14-e164-11e6-9c38-a7f43f69b7a7.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22220779/e9ba0654-e164-11e6-8556-8134595f8dc9.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22220785/ef6eb022-e164-11e6-8c68-4af2173ee032.png)

**Comment by peterqliu** [comment]
@aparlato it may help to draw the white prongs at different lengths, to accentuate movement. Similarly, different sizes of circles at the bottom would introduce some nice asymmetry and strengthen the overall silhouette.

**Comment by aparlato** [comment]
@peterqliu good suggestions! Here's an attempt at what you said. Definitely looking _better_

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22226829/f2816788-e17c-11e6-8c3f-58a4350f8a51.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22226835/fa2eaaf4-e17c-11e6-91f5-5c67a96cf96b.png)

**Comment by peterqliu** [comment]
@aparlato may be time to simplify. try 2 and 3 prongs for `11` and `15` respectively, instead of 3 and 5. Fewer affords bigger.

Also, try making the circles _huge_, to emphasize the froth and splash. right now it looks like pouring paint.

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22231168/9500e56a-e196-11e6-84e4-e9d81e9fafb1.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22231171/9cb5f26e-e196-11e6-96b0-287efdfb3ce0.png)
**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22231176/a912a372-e196-11e6-9da9-c5a34720c6ef.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22231192/b144eeec-e196-11e6-85ee-687b6c660196.png)

I did bigger circles above and I like the results, however I find fewer prongs confusing, so I'm leaning against going with any fewer than is used above here. 

____

Here are a couple of versions with fewer below. None of my versions got much less awkward than this.

![image](https://cloud.githubusercontent.com/assets/15698320/22231264/570ed2ca-e197-11e6-94f7-ed12596cd56e.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22231270/5fe7b0ec-e197-11e6-86f3-b74f0dda4ba3.png)

and this 15px which has some awkward pixel alignment.

![image](https://cloud.githubusercontent.com/assets/15698320/22231351/eaf6eeaa-e197-11e6-84f6-7ea7379121d5.png)

**Comment by natslaughter** [comment]
@aparlato 
For me the three-pronged approach works, and keeps the water strokes at 1 pixel. @peter has a good point of trying to make the water lines thicker, but since you're also using the lines to frame the icon around the water, there isn't a lot of room to get bigger without losing the outer black lines. 

Can you create a branch so that I can pull and view in illustrator by chance?

**Comment by aparlato** [comment]
@natslaughter pushed to branch :+1:

**Comment by aparlato** [comment]
@natslaughter also now that I'm reading your comment again, 
> since you're also using the lines to frame the icon around the water

I'm seeing that maybe you guys are actually reading this icon differently than I have been which might actually be a better way to view it. Are you both seeing this as multiple waterfalls on a mountain or seeing the white part as accents to a single waterfall where the whole icon is just the water?

**Comment by peterqliu** [comment]
>the white part as accents to a single waterfall where the whole icon is just the water

this. The asymmetrical circles in https://github.com/mapbox/maki/issues/343#issuecomment-274646396 seemed effective, but we lost the asymmetry in https://github.com/mapbox/maki/issues/343#issuecomment-274682252. How did they work when asymmetrical _and_ huge.

**Comment by aparlato** [comment]
@peterqliu ok we were on the same page then. 
Here's some iterations trying to make that work.

**a)** 
![image](https://cloud.githubusercontent.com/assets/15698320/22262591/687838f0-e226-11e6-99df-7e27bbcc3fa2.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22262598/70754070-e226-11e6-8ca5-80ed5ac34302.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22262613/7ef67222-e226-11e6-8df1-d117917be5d6.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22262628/87263d7e-e226-11e6-954b-cecbd45d07f8.png)

**b)**
![image](https://cloud.githubusercontent.com/assets/15698320/22262654/9e964ab2-e226-11e6-8bc9-2b0c239cd5fd.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22262659/a6229376-e226-11e6-9845-c6517c917823.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22262682/b3f8c4ca-e226-11e6-9a46-630ceb61e13f.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22262689/bc2f1f36-e226-11e6-8ac8-b31810dc07bc.png)

**c)**
![image](https://cloud.githubusercontent.com/assets/15698320/22263336/f0ebb3ea-e228-11e6-8aac-e3f0614d0071.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22263537/a30be3d8-e229-11e6-9fd6-c0c5663b83f1.png)

![image](https://cloud.githubusercontent.com/assets/15698320/22263360/041c4d12-e229-11e6-8d49-1f0608331831.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22263545/ad7d6094-e229-11e6-9b2b-08a8972902a5.png)

**Comment by natslaughter** [comment]
@aparlato 
looking good. I'm finding the 11-pixel icons to be a bit too abstract in this new iteration, because it only has one black line. Increasing the white space, to me, wasn't necessary as the vertical black lines read clearly when there were three. Is there a way to increase the black line to 2 pixels? What does that look like?

**Comment by aparlato** [comment]
@natslaughter Good point. Here's two iterations of the 11px with that in mind. One goes back to three prongs and the other tries out a 2px black line.

![image](https://cloud.githubusercontent.com/assets/15698320/22273297/c58fd862-e254-11e6-865c-65731c799d15.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22273304/cbe9ee28-e254-11e6-94f3-26df9017d6c3.png)

And here again is the current 15px for reference. I lean toward three prong on both.

![image](https://cloud.githubusercontent.com/assets/15698320/22273351/1d958d7c-e255-11e6-84c4-68f82e4de0b3.png)
