### ISSUE TITLE
map icon

### ISSUE THREAD

**Issue by Hufkratzer** [mapbox/maki#348]
Boards with maps ([information=map](http://wiki.openstreetmap.org/wiki/Tag:information=map)) should better have different icons than other objects with tag [tourism=information](http://wiki.openstreetmap.org/wiki/Tag:tourism=information) because sometimes there are lots of such objects in one place, compare:
- [taginfo tourism=information](http://taginfo.openstreetmap.org/tags/tourism=information#combinations)
- from www.wanderreitkarte.de:<br> ![nops](https://cloud.githubusercontent.com/assets/5958184/21466302/0c327362-c9c6-11e6-8e0a-05804ce5afe8.jpg)
- https://github.com/gravitystorm/openstreetmap-carto/issues/1978
- https://github.com/lonvia/waymarked-trails-site/issues/264

### Proposal:
Explanation: The zigzag line on the board shall symbolize a route like in the [current icons for route=* in iD](https://github.com/openstreetmap/iD/blob/c8e4f76c230512dc82dc060bf337e3ba489b113e/svg/iD-sprite.src.svg)
#### 11px:
![map-11-11px](https://cloud.githubusercontent.com/assets/5958184/21466310/82fecd60-c9c6-11e6-87dd-62ae6dc06219.png)
![map-11-200px](https://cloud.githubusercontent.com/assets/5958184/21466312/8c2d95b0-c9c6-11e6-816b-1f2751753618.png)
#### 15px:
![map-15-15px](https://cloud.githubusercontent.com/assets/5958184/21466317/a5f58142-c9c6-11e6-9aa7-0f2884a6360b.png)
![map-15-200px](https://cloud.githubusercontent.com/assets/5958184/21466318/ac58d084-c9c6-11e6-8ce3-dc8c62c3ef7c.png)

**Comment by natslaughter** [comment]
@Hufkratzer 
Thank you for your submittal and interest in Maki! Your request has been received and after evaluating the icon, we do not think it’s a good fit for the Maki catalogue. Maki focuses on ”points of interest” icons specific for map design. Check out the nounproject.com and see if you can find your icon there. Best of luck!”
