### ISSUE TITLE
 board icon

### ISSUE THREAD

**Issue by Hufkratzer** [mapbox/maki#349]
Information boards ([information=board](http://wiki.openstreetmap.org/wiki/Tag:information=board), not [with map](https://github.com/mapbox/maki/issues/348)) should better have different icons than other objects with tag [tourism=information](http://wiki.openstreetmap.org/wiki/Tag:tourism=information) because sometimes there are lots of such objects in one place, compare:
- [taginfo tourism=information](http://taginfo.openstreetmap.org/tags/tourism=information#combinations)
- [JOSM board icon]( https://josm.openstreetmap.de/browser/josm/trunk/images/presets/misc/information/board.svg) different from the [information icon]( https://josm.openstreetmap.de/browser/josm/trunk/images/presets/misc/information/information.svg)
- from www.wanderreitkarte.de:<br>![nops](https://cloud.githubusercontent.com/assets/5958184/21466391/6d0c339a-c9ca-11e6-8144-b0d7791ee630.jpg)
- the board from the [map icon](https://github.com/mapbox/maki/issues/348) may be reused
#### 11px:
![board-11-11px](https://cloud.githubusercontent.com/assets/5958184/21466393/e185fd00-c9ca-11e6-81b6-7f20931df862.png)
![board-11-200px](https://cloud.githubusercontent.com/assets/5958184/21466394/eb88560e-c9ca-11e6-91a1-e4df2fe7850b.png)
#### 15px:
![board-15-15px](https://cloud.githubusercontent.com/assets/5958184/21466399/ff4ac5dc-c9ca-11e6-8aca-a7b2bf0fd01a.png)
![board-15-200px](https://cloud.githubusercontent.com/assets/5958184/21466402/18b1c3ae-c9cb-11e6-8631-5e5c148502ce.png)

**Comment by natslaughter** [comment]
“Thank you for your submittal and interest in Maki! Your request has been received and after evaluating the icon, we do not think it’s a good fit for the Maki catalogue. Maki focuses on ”points of interest” icons specific for map design. Perhaps you could use the existing Maki icon `information`. Check out the nounproject.com and see if you can find your icon there. Best of luck!”
