### ISSUE TITLE
green-receptacle icon

### ISSUE THREAD

**Issue by aahmedxlsolutions** [mapbox/maki#354]
Hello! Thanks for contributing. 

If you are opening an issue about the Maki editor, style guidelines or another Maki-related component, please provide a detailed description and any supporting imagery. If you are making an icon request, please make sure the following items are in your issue. 

#### Icon Request
- green-receptacle icon
- This is symbol for receptacles used in parts of USA ,as Victor Stanley(https://www.connect.victorstanley.com) is placing the receptacles for trash collection on the streets of Baltimore, Florida, Washington Dc, Boston, pittsberg -  etc and are expanding to other regions as well we would like to register an icon of their own. 

Which can be used to display as symbols for better development use as well.

![greenreceptacle-11](https://cloud.githubusercontent.com/assets/25078299/21887715/153cf8ee-d8e7-11e6-9919-4369845acd52.png)
![greenreceptacle-15](https://cloud.githubusercontent.com/assets/25078299/21887733/27954abe-d8e7-11e6-9f28-57a7843d7432.png)

**Comment by natslaughter** [comment]
Thank you for your submittal and interest in Maki! Maki already has a [waste-basket icon](https://github.com/mapbox/maki/blob/master/icons/waste-basket-15.svg), so we suggest using this particular icon and changing its color using the [maki editor](https://www.mapbox.com/maki-icons/editor/). Best of Luck!
