### ISSUE TITLE
bridge icon

### ISSUE THREAD

**Issue by ajashton** [mapbox/maki#359]
Bridges can be important landmarks that one might want to call out with an icon at medium scales. I'm thinking like a basic suspension bridge silhouette.

**Comment by natslaughter** [comment]
![bridge](https://cloud.githubusercontent.com/assets/16616543/22025608/249c949e-dc9c-11e6-9a9d-1e9b01a65769.png)

**Comment by aparlato** [comment]
(somehow I forgot to post this friday and it's been sitting here as draft)

**Draft 1**
This is the suspension bridge approach. It definitely needs a good bit of refinement, but at scale do you think it's working overall?

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21950696/75f7916e-d9b2-11e6-9d73-4ad18fd5463d.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21950708/827dd98e-d9b2-11e6-89ae-8b0a9604b0da.png)

Other approaches at 11px

![image](https://cloud.githubusercontent.com/assets/15698320/21950761/fd140754-d9b2-11e6-8063-76b23ea23163.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21950764/04983338-d9b3-11e6-9776-430123f6008d.png)

**Comment by aparlato** [comment]
Another alternative approach. Torn between this and suspension bridge approach. Both have their ambiguities.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22033557/cd8a49d8-dc9d-11e6-9184-19e0de80126b.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22033567/d4821efa-dc9d-11e6-9a65-aecdfb26eea9.png)

**Comment by ajashton** [comment]
I do like your initial suspension bridge style, but can see how it might be misread.

---

![image](https://cloud.githubusercontent.com/assets/15698320/22033557/cd8a49d8-dc9d-11e6-9184-19e0de80126b.png) ![image](https://cloud.githubusercontent.com/assets/15698320/22033567/d4821efa-dc9d-11e6-9a65-aecdfb26eea9.png)

One thing I like about these ones ^ is that it's kind of ambiguous what size of bridge is being represented (could be applied to a footbridge or a multilane highway), but  reads pretty clearly as a bridge to me.

**Comment by natslaughter** [comment]
[OSM tags](https://en.wikipedia.org/wiki/List_of_bridge_types) for bridge types.
It seems that most if not all these bridges fall within two types:

A: platform for movement with structure underneath
B: platform for movement with structure both underneath and above

![screen shot 2017-01-17 at 1 39 27 pm](https://cloud.githubusercontent.com/assets/16616543/22034652/ebcab456-dcba-11e6-87d3-9029ff8c012d.png)  
  
I would recommend going in the direction of @aparlato's second approach (B) having structure both under and above the bridge. It seems that this direction would be more applicable to the different bridge types.   

---

@aparlato I like both of these initial approaches. I would be curious to see the suspension bridge icons without the outer cables about the bridge, to see if it makes the 11-pixel icon less like an enclosure, but it could end up looking too empty. 

The second approach is working nicely. It almost seems to be a collage of different bridge elements put into one icon.

**Comment by aparlato** [comment]
@natslaughter 
Here's the suspension style bridge without those cables. I think this just ends up looking too ambiguous all together. I'm not sure bridge would be my first guess on these two.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22035187/e32c1a36-dca3-11e6-9325-41a250d0b8d1.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/22035243/1d473d9a-dca4-11e6-94aa-2eb82a194cd8.png)

**Comment by natslaughter** [comment]
@aparlato yeah that looks very odd.

**Comment by natslaughter** [comment]
@aparlato I do gravitate towards the earlier iteration because of the extra negative space in- between the upper tension cables.

**Comment by aparlato** [comment]
@natslaughter great! Are there any changes you can see that need to be made or other thoughts to try out? It looks good on my end. I pushed this to the branch and it should be clean / free of extraneous anchor points.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/22040390/88c62514-dcb7-11e6-8052-3e081cf818e4.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22040399/8eb768de-dcb7-11e6-9a9d-a7dc582dc77a.png)


**15:**

![image](https://cloud.githubusercontent.com/assets/15698320/22040417/96891b5c-dcb7-11e6-8ce7-fbf4bd81a92a.png)
![image](https://cloud.githubusercontent.com/assets/15698320/22040429/9d1235bc-dcb7-11e6-8e02-8b71b2ab9263.png)

**Comment by natslaughter** [comment]
@aparlato looks great!
the outer negative spaces on top in the 11-pixel icon are a tad blurry, and I'm guessing due to the lack of space there isn't much we can do about that. 
I love how this icon is a combination of the two, structural types used for bridges: you got your medieval and your modern in one icon.
