### ISSUE TITLE
college-15 should not have a fill

### ISSUE THREAD

**Issue by bhousel** [mapbox/maki#360]
<img width="499" alt="screenshot 2017-01-15 01 24 42" src="https://cloud.githubusercontent.com/assets/38784/21957658/7b4a716c-dac1-11e6-8a0f-0de0ec3ed600.png">

**Comment by samanpwbb** [comment]
👍 – should add a check to https://github.com/mapbox/maki/blob/master/test/maki.test.js that bans all properties but `d` from paths.
