### ISSUE TITLE
Mountain icon request returns invalid request

### ISSUE THREAD

**Issue by matter3** [mapbox/maki#363]
I am trying to request a icon via static request. Could someone let me know why this request is not returning a valid icon? 

**Request**
https://api.mapbox.com/v4/marker/pin-m-mountain+087cca@2x.png?access_token={my_token}

**Response**
`{"message":"Marker \"pin-m-mountain+087cca\" is invalid."}`

I am able to make successful requests for other icons, like campsite. Thanks!

**Comment by samanpwbb** [comment]
The Mapbox v4 static API supports a much older version of Maki, and it will not be updated to support new Maki (see https://github.com/mapbox/maki/tree/mb-pages).
