### ISSUE TITLE
Doctor icon

### ISSUE THREAD

**Issue by CouchFrancois** [mapbox/maki#370]
The doctor icon (stethoscope) doesn't seem to be working.  Others work when I hit the api, but doctor doesn't.  Was it renamed?

**Comment by samanpwbb** [comment]
> Others work when I hit the ap

The mapbox marker API was designed with an old version of Maki that did not have the doctor icon. You can see info about the old version of Maki in the `mb-pages` branch: https://github.com/mapbox/maki/blob/mb-pages/www/maki.js
