### ISSUE TITLE
Can't get an icon via api

### ISSUE THREAD

**Issue by vladim1** [mapbox/maki#374]
Why can't I get a "castle" icon via API
https://api.tiles.mapbox.com/v4/marker/pin-m-castle.png?access_token=[my_token]
I am getting an error
```
{"message":"Marker \"pin-m-castle\" is invalid."}
```
PS: But I can get a "rocket" icon for example
https://api.tiles.mapbox.com/v4/marker/pin-m-rocket.png?access_token=[my_token]

**Comment by fspoettel** [comment]
The static API only works with `v0.5.0` of Maki, newer icons are not supported.
