### ISSUE TITLE
Fountain icon

### ISSUE THREAD

**Issue by vladim1** [mapbox/maki#375]
Fountains are important landmarks, that should be on the maps
[OSM Tag](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfountain)
[Possible concept](http://wiki.openstreetmap.org/wiki/File:Fountain-14.svg)

**Comment by tristen** [comment]
Closing. there are icons for "water" and "drinking-water". Please re-open if you this doesn't capture things
