### ISSUE TITLE
finish-flag icon

### ISSUE THREAD

**Issue by Niklitov** [mapbox/maki#378]
Finish flag (Race finished / winner, chequered flag) icon Request:

A finish flag icon would be useful to go along with the auto racing and WikiExpeditions maps, etc. mode of transportation icons and flags in major racing leagues icons.

For example:
https://commons.wikimedia.org/wiki/File:F1_chequered_flag.svg
https://en.wikipedia.org/wiki/File:LateModelCelebratesHeatWin.jpg
https://en.wikipedia.org/wiki/Racing_flags#The_chequered_flag
https://ru.wikimedia.org/wiki/Sakhalin_WikiExpedition_2017

**Comment by natslaughter** [comment]
@Niklitov 
Thank you for your submittal and interest in Maki! After evaluating the icon request, we do not think it’s a good fit for the Maki catalogue. Maki focuses on ”points of interest” icons specific for map design. Check out the nounproject.com and see if you can find your icon there. Best of luck!
