### ISSUE TITLE
Getting new standalone marker with new API

### ISSUE THREAD

**Issue by vladim1** [mapbox/maki#379]
I am trying to get a standalone marker with new maki images (>v0.5.0) with new Api as mentioned here https://github.com/mapbox/maki/issues/377#issuecomment-284938059
When I use
https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/pin-s-amusement-park+9ed4bd(-122.46589,37.77343)/auto/30x70?access_token=[my_token]
I am getting a background with map behind the marker, but i want to get a transparent background like it was before.
How can I achieve this? And is this a proper way to use new API?

**Comment by tristen** [comment]
Closing as stale. Please reopen if you are still experiencing the issue with a screenshot of the output and correct query parameters in the request url.
