### ISSUE TITLE
I made some icons!

### ISSUE THREAD

**Issue by bhousel** [mapbox/maki#380]
<img width="973" alt="screenshot 2017-03-09 09 10 04" src="https://cloud.githubusercontent.com/assets/38784/23753660/5114b1e4-04a8-11e7-8aba-b84c70ee39ae.png">

I made these icons so that we'd have better coverage of the iD presets, see https://github.com/openstreetmap/iD/issues/3569, https://github.com/openstreetmap/iD/issues/3856 . They probably don't all belong in Maki, but at least some are worth contributing upstream.

The icons are good enough for what I need, but will need some work to be brought up to Maki standards.    I drew them all to be _mostly_ pixel-aligned, fill-only, fit within circular trim, etc.  Also I only drew 15px variants.  
 
Let me know how to proceed - pick the ones you like and I can open separate PRs for each?

<table><tr><td>

#### Row 1
- poi-foot (#333)
- poi-traffic-signals (#59)
- poi-yield
- poi-stop
- poi-warning (#372, #196)
- poi-fire-hydrant
- poi-power (#254)
- poi-mast (#337, #257)
- poi-bench
- poi-clock
- poi-ruins (#338)
- poi-junction
- poi-social-facility (#172)

</td><td>

#### Row 2
- poi-vending-machine (#75)
- poi-dice (#376)
- poi-beach (#58)
- poi-fountain (#375)
- poi-storage-tank (#362)
- poi-silo
- poi-street-lamp (lol #175)
- poi-tool
- poi-tower (#339)
- poi-military (#181)
- poi-chimney
- poi-bowling
- poi-binoculars (#271, #238)

</td></tr></table>

@natslaughter @aparlato @samanpwbb

**Comment by stevage** [comment]
Nice! FYI the one you describe as "poi-warning" doesn't fit the bill for me. In parts of Europe, this looks more like the "you have priority" sign to me, which is sort of the opposite of a warning. See [here](http://www.alpinedrivingskills.com/professional-alpine-drivers/2-driving-in-france/priorities-a-droite/)

**Comment by mcm-jyl** [comment]
+1, a warning sign is more like a yield sign with an exclamation point inside:
```
_____
\ ! /
 \ /
```
I believe that's more cultural neutral.

poi-street-lamp: I thought it was a shower (BTW existing icon request, just rename it :smile:)

**Comment by bhousel** [comment]
Thanks @mcm-jyl  👍 

Wow it's the 1 year anniversary of this! 🎂  
Anyway, in the past year I've made several more, including a better lamp icon.  

Because they don't completely match stylistically with maki, and don't have separate 11px versions, and I don't have time so spend on them, I'm going to:

- [ ] release them as a separate icon pack

**Comment by bhousel** [comment]
Closing, my icons are here now:
Temaki repo:  https://github.com/bhousel/temaki
Preview page:  http://bhousel.github.io/temaki/docs/

Hope they are helpful!  ✨
