### ISSUE TITLE
entrance-15 has bad path in svg

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#381]
![image](https://cloud.githubusercontent.com/assets/15698320/23974965/84e074fc-099b-11e7-8ffd-133dc152eb23.png)

Just noticed while working on other things that entrance-15 has an arbitrary line in it ⬆️

**Comment by tristen** [comment]
Looks like this was addressed:

<img width="611" alt="Screen Shot 2019-05-22 at 11 54 24 AM" src="https://user-images.githubusercontent.com/61150/58189405-6dbcd880-7c88-11e9-8ff9-1ff05f3b8b0a.png">
