### ISSUE TITLE
Invalid iconset error uploading .json files

### ISSUE THREAD

**Issue by amyleew** [mapbox/maki#382]
I'm trying to upload a [maki iconset .json](https://dl.dropboxusercontent.com/u/301177183/iconset-mapbox_streets_icons.json) from about 10 months ago and getting the error `Icon group style properties are invalid.`

![image](https://cloud.githubusercontent.com/assets/4587826/24016473/a5b8b9e2-0a62-11e7-8eb8-1ead65d92d01.png)

/cc @samanpwbb

**Comment by samanpwbb** [comment]
@aparlato – can you debug this? This is our top priority – we need a fix here before we can get any new features merged in. As we did before, start by writing a failing test using this icons.js, then work up from there until the test passes, and commit the test with the fix.
