### ISSUE TITLE
Update Streets layout

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki#383]
Based on recent changes to the Mapbox Streets style, [the Streets layout json](https://github.com/mapbox/maki/blob/master/layouts/streets.json) should be updated to include in the `General` category:

- square
- square-stroked
- star-stroked

/cc @aparlato

**Comment by dasulit** [comment]
As of https://github.com/mapbox/maki/pull/453, there is no longer a layouts/streets.json file to maintain.
