### ISSUE TITLE
Some of the Maki icons are not rendering in Inkscape

### ISSUE THREAD

**Issue by pathmapper** [mapbox/maki#385]
Hi, 
I used the Maki Editor with the following settings:

![bildschirmfoto von 2017-05-16 10-23-18](https://cloud.githubusercontent.com/assets/20856381/26096621/0cdc596e-3a22-11e7-95fb-d9ce0611c2d0.png)

In the preview everything looks fine, but when exporting (downloading) all icons, the .zip file contains some broken svg icons, e.g. buddhism-15, city-15, home-15:

![buddhism-15](https://cloud.githubusercontent.com/assets/20856381/26096853/de5316f4-3a22-11e7-94bd-5b1882a4c356.png)
![city-15](https://cloud.githubusercontent.com/assets/20856381/26096854/de5779c4-3a22-11e7-8938-0f2cbf6c330a.png)
![home-15](https://cloud.githubusercontent.com/assets/20856381/26096855/de59da20-3a22-11e7-8172-ed4b5486ae26.png)

(.svg saved as .png)

**Comment by pathmapper** [comment]
Open the downloaded home-15.svg in Inkscape looks like this:
![bildschirmfoto von 2017-05-16 10-51-39](https://cloud.githubusercontent.com/assets/20856381/26097555/440f795e-3a25-11e7-8cba-bb3e6e891592.png)

**Comment by pathmapper** [comment]
Same for downloading the latest release from github:
https://github.com/mapbox/maki/archive/v4.0.0.zip

![bildschirmfoto von 2017-05-16 10-56-03](https://cloud.githubusercontent.com/assets/20856381/26097769/ea6e7dea-3a25-11e7-9892-b16f16e7253b.png)

**Comment by pathmapper** [comment]
Sorry for the noise, when using these icons on a Map everything looks fine.
Maybe somebody could me explain why some icons are **looking** broken in Inkscape.

**Comment by natslaughter** [comment]
@pathmapper thanks for bringing this to our attention. I will look into this and get back to you

**Comment by natslaughter** [comment]
@pathmapper we were able to resolve this issue. Thanks for your interest in Maki!

**Comment by pathmapper** [comment]
@natslaughter wow! Thanks for the very fast investigation, the fix and providing Maki under CC0!

**Comment by pathmapper** [comment]
There are more Maki icons affected by this issue.
Unfortunately I don't have Illustrator available to fix them like in https://github.com/mapbox/maki/pull/386 . Is there any way I could help? Should I provide a list with the icons not rendering in Inkscape?

**Comment by natslaughter** [comment]
@pathmapper if you have a list of icons that are not rendered by Inkscape, that would be helpful information to figure out the best solution to this issue.

**Comment by pathmapper** [comment]
@natslaughter I checked the icons from https://github.com/mapbox/maki/tree/master/icons, here's the list:

barrier-11
defibrillator-11
defibrillator-15
emergency-phone-11
emergency-phone-15
entrance-alt1-11
entrance-alt1-15
fence-11
fence-15
florist-11
florist-15
gaming-11
horse-riding-11
horse-riding-15
logging-11
logging-15
marker-stroked-11 (renders like marker-11)
marker-stroked-15 (renders like marker-15)
mobile-phone-11
mobile-phone-15
park-alt1-11
park-alt1-15
natural-11
natural-15
scooter-11
scooter-15
snowmobile-11
snowmobile-15
slaughterhouse-15
slaughterhouse-11
telephone-11
town-11
town-15
village-11
village-15

**Comment by pathmapper** [comment]
@natslaughter Any update here? Are there plans to fix the listed icons?

**Comment by natslaughter** [comment]
@pathmapper I was able to open the icons listed above in Inkscape with no rendering issues. Can you confirm this is working on your end?

**Comment by pathmapper** [comment]
@natslaughter thanks for your answer!
With Inkscape on linux I still have the issues but it is probably because I am not using the latest version of Inkscape. I just tried the latest version on Windows and there are no issues, everything looks fine.
