### ISSUE TITLE
mapbox-static-image-url-marker icon

### ISSUE THREAD

**Issue by TheIronMarx** [mapbox/maki#387]
To keep things consistent on Android between the native `MapView` and the Static Image URL, I want the same icon to be used. Currently raindrop-like map markers are completely solid or have only an outline. I want the solid marker with a circle in it such as the one found [here. 
](https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/pin-s+2196f3(-122.46589,37.77343)/auto/800x400@2x?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejdueG92YjAwZHUzMnA5ZWIyMW1zcDQifQ.acDRLVcqW0LZfWQXvC3-pw&before_layer=road-label-small)

It looks a little goofy to have the solid marker in one place and then the marker with a circle in another.

**Comment by samanpwbb** [comment]
Hey @TheIronMarx – this repo only covers the POI icons, not the markers. I will relayed this issue to the Android team at Mapbox and they're aware of it.

**Comment by zugaldia** [comment]
Feel free to open a follow up ticket on https://github.com/mapbox/mapbox-gl-native/issues. For reference, we currently use the same icon for our mobile clients. It can [be found here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/resources/default_marker.svg).

**Comment by samanpwbb** [comment]
...and the marker the mapbox static api uses is here: https://github.com/mapbox/makiwich/tree/master/sources 😉  – someone just needs to connect the dots. _However_ I think the problem runs a little deeper? Does marker tinting on Android turn the white circle in the middle the same color as the rest of the icon?

**Comment by zugaldia** [comment]
> However I think the problem runs a little deeper? Does marker tinting on Android turn the white circle in the middle the same color as the rest of the icon?

I'm now re-reading OP, I missed the root issue reported. @TheIronMarx : are you saying that your default marker on Android doesn't have the white circle inside? The expected look is like the marker on this example: https://www.mapbox.com/android-sdk/examples/marker/.

**Comment by TheIronMarx** [comment]
The default markers on the SDK are correct. I just wanted to be able to color it according to my branding and was hunting for the icon. I'm satisfied with your earlier messag linking the Marker SVG.

**Comment by zugaldia** [comment]
@TheIronMarx 👍 thanks.
