### ISSUE TITLE
Ongoing support for simplestyle-spec - question

### ISSUE THREAD

**Issue by jbhoward-dublin** [mapbox/maki#388]
I've opened an issue regarding lack of support for new icons in the simplestyle-spec: [https://github.com/mapbox/simplestyle-spec/issues/26](https://github.com/mapbox/simplestyle-spec/issues/26).

Since the last update was mid-2015, I ask here whether there is ongoing support from Mapbox to the simplestyle-spec, which is very handy ...

**Comment by samanpwbb** [comment]
Hi @jbhoward-dublin – we do not have plans to release new versions of the v4 static API. You can take the icons in this project and use them however you'd like though. Source files are here: https://github.com/mapbox/maki/tree/master/icons
