### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by robertjliguori** [mapbox/maki#393]
Would be nice to have explicit icons for all of the following:

OBSTACLE, # IN DOF, MAKI ICON EXISTS
==========================
TOWER: 115989
POLE: 63181
WINDMILL: 53148
BLDG: 40153 (already exists as 'building') 
T-L TWR: 34029
FENCE: 14139 (already exists as 'fence') 
SIGN: 6285
TANK: 6212
CATENARY: 4896
NAVAID: 4747
STACK: 4099
GEN UTIL: 2354
ELEVATOR: 1930
ELEC SYS: 1817
BLDG-TWR: 698
CTRL TWR: 620
BRIDGE: 594
CRANE: 499
SPIRE: 332
PLANT: 293
UTILITY POLE: 202
RIG: 176
AG EQUIP: 159
MONUMENT: 129 (already exists as 'monument')
REFINERY: 122
DAM: 89 (already exists as 'dam')
COOL TWR: 87
DOME: 81
STADIUM: 37 (already exists as 'stadium')
TRAMWAY: 35
BALLOON: 13
ANTENNA: 12
LGTHOUSE: 9 (already exists as 'lighthouse') 
MET: 7
ARCH: 5
WINDSOCK: 2
GRAIN ELEVATOR: 1
HANGAR: 1

 
Reference: https://www.faa.gov/air_traffic/flight_info/aeronav/obst_data/

**Comment by robertjliguori** [comment]
TOWER: 115989
POLE: 63181
WINDMILL: 53148
BLDG: 40153 
T-L TWR: 34029
FENCE: 14139 
SIGN: 6285
TANK: 6212
CATENARY: 4896
NAVAID: 4747
STACK: 4099
GEN UTIL: 2354
ELEVATOR: 1930
ELEC SYS: 1817
BLDG-TWR: 698
CTRL TWR: 620
BRIDGE: 594
CRANE: 499
SPIRE: 332
PLANT: 293
UTILITY POLE: 202
RIG: 176
AG EQUIP: 159
MONUMENT: 129  
REFINERY: 122
DAM: 89  
COOL TWR: 87
DOME: 81
STADIUM: 37  
TRAMWAY: 35
BALLOON: 13
ANTENNA: 12
LGTHOUSE: 9  
MET: 7
ARCH: 5
WINDSOCK: 2
GRAIN ELEVATOR: 1
HANGAR: 1

Reference: https://www.faa.gov/air_traffic/flight_info/aeronav/obst_data/

**Comment by natslaughter** [comment]
@robertjliguori 
Thanks for your interest in Maki. Although I do agree with you that it would be nice to have icons for all of these, most of them don't fit the original intent of Maki, which is to provide an icon set of commonly used points of interest. These seem more aviation-specific. Best of luck and thanks again for your interest.

**Comment by robertjliguori** [comment]
Of the ones requested... can you please tell me which ones apply to the Maki philosophy and which would be excluded?

**Comment by natslaughter** [comment]
@robertjliguori 
I could see `windmill`, `tower` and `bridge` being included to the Maki set, in that they are widely used across a wide range of maps and the number of uses.
