### ISSUE TITLE
Maki editor feature request: additional shape (pin)

### ISSUE THREAD

**Issue by pathmapper** [mapbox/maki#397]
Hi @samanpwbb @natslaughter,
with the Mapbox Static API it is possible to request a marker with a _pin_ shape.
But this is only working with Maki release v0.5.0 .
According to https://github.com/mapbox/maki/issues/395 there are no plans to update the Static API.

[Maki editor](https://www.mapbox.com/maki-icons/editor/) is very useful, at the moment there are the shapes _circle_ and _rectangle_ available.
Would it be possible to add the feature to be able to create also a _pin_ shape with Maki editor?
This would be an easy way to create pin markers with the current Maki release.

**Comment by ajashton** [comment]
Is the [marker icon](https://github.com/mapbox/maki/blob/master/icons/marker-15.svg) close enough to what you want?

**Comment by pathmapper** [comment]
Yes, but what I meant is only for the outer shape. Inside I would like to use one out of all available Maki icons. Here is an example of an old icon:
![image](https://user-images.githubusercontent.com/20856381/31998637-d2728c78-b990-11e7-82bd-b5c8c0a982fd.png)

**Comment by tristen** [comment]
Going to close this in favor of the feature request for this in maki-icons. See https://github.com/mapbox/maki-icons/issues/141
