### ISSUE TITLE
Maki editor encounters a fatal error editing colors

### ISSUE THREAD

**Issue by SKalt** [mapbox/maki#399]
In Chrome 61 and Firefox 57 the editor is unusable. 
First, when no named groups are selected (such as when I click one icon), clicking the color editor results in the following error: 
On each click in Chrome 61:
```
bundle.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at Object._dragStart (bundle.js:1)
    at Object.r (bundle.js:12)
    at o (bundle.js:10)
    at Object.s [as executeDispatchesInOrder] (bundle.js:10)
    at d (bundle.js:10)
    at m (bundle.js:10)
    at Array.forEach (<anonymous>)
    at r (bundle.js:14)
    at Object.processEventQueue (bundle.js:10)
    at r (bundle.js:12)
```
On only the first click in Firefox 57:
```
TypeError: t.changedTouches is undefined[Learn More] bundle.js:1:20908
	_dragStart https://www.mapbox.com/maki-icons/bundle.js:1:20908
	_dragStart self-hosted:953:17
	r https://www.mapbox.com/maki-icons/bundle.js:12:20509
	o https://www.mapbox.com/maki-icons/bundle.js:10:25824
	s https://www.mapbox.com/maki-icons/bundle.js:10:26041
	d https://www.mapbox.com/maki-icons/bundle.js:10:22210
	m https://www.mapbox.com/maki-icons/bundle.js:10:22338
	forEach self-hosted:273:13
	r https://www.mapbox.com/maki-icons/bundle.js:14:12401
	processEventQueue https://www.mapbox.com/maki-icons/bundle.js:10:23400
	r https://www.mapbox.com/maki-icons/bundle.js:12:20757
	handleTopLevel https://www.mapbox.com/maki-icons/bundle.js:12:20845
	a https://www.mapbox.com/maki-icons/bundle.js:12:21327
	perform https://www.mapbox.com/maki-icons/bundle.js:14:7944
	batchedUpdates https://www.mapbox.com/maki-icons/bundle.js:12:18060
	a https://www.mapbox.com/maki-icons/bundle.js:13:19782
	dispatchEvent https://www.mapbox.com/maki-icons/bundle.js:12:22344
	dispatchEvent self-hosted:997:17
```
After selecting and populating a named group, the error persists.  Clicking the paddles on the HSV and attempting to edit the HSV values does not raise any errors, but also does not produce any changes.  Editing alpha and hex values result in visible changes the value in question.

Please direct me to where I might access the editor code and contribute further its design.

**Comment by samanpwbb** [comment]
Hi @SKalt – the maki icon editor isn't open source. Do you see the same issue on https://www.mapbox.com/react-colorpickr/?

**Comment by SKalt** [comment]
Yep, react-colorpickr reproduces those errors exactly.  I'll close this issue here and raise it in  [the react-colorpickr repository](https://github.com/mapbox/react-colorpickr).
