### ISSUE TITLE
rect element causing issues in mapnik

### ISSUE THREAD

**Issue by curiousdeveloper2** [mapbox/maki#403]
I ran into an issue where the rect element of the SVG was causing a stroke to be applied both to the rect and the icon:  Detailed issue here: https://github.com/mapnik/mapnik/issues/3868

Here is the outcome: 

![image](https://user-images.githubusercontent.com/37081025/36989022-72b2619c-206e-11e8-9453-efd35e94e965.png)

**Comment by tristen** [comment]
I suspect this is no longer an issue as the asset for this uses `path` now and not `rect`. Please re-open however if you're seeing otherwise!
