### ISSUE TITLE
noodle restaurant icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#405]
### noodle restaurant icon

**use case**
For general and specialty restaurants with a focused menu showcasing noodles

**tagging information**
Maki field = { cuisine: 'noodle' }, { cuisine: 'ramen' }, { cuisine: 'soba' }, etc
[OSM tag info](https://taginfo.openstreetmap.org/keys/cuisine#values)

**possible symbol**
A generic bowl with depiction of noodle and/or chop sticks? 

![image](https://user-images.githubusercontent.com/16616543/38837082-9c8acf9e-419e-11e8-9c33-6ab3728c3090.png)

**Comment by natslaughter** [comment]
going with a 'bowl of noodles with chop sticks' for the symbol concept

<img width="303" alt="screen shot 2018-05-10 at 11 08 13 am" src="https://user-images.githubusercontent.com/16616543/39877108-0778769c-5443-11e8-9276-8bb0b4aa20a6.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by natslaughter** [comment]
I'm leaning towards `#4-fancy-bowl`, but feel the 11 pixel icon needs work: the space in-between the chopsticks is off:

<img width="703" alt="restaurant-noodles-draft-1" src="https://user-images.githubusercontent.com/16616543/40742622-1fdcb81c-641d-11e8-8abd-ddd5e6617ffe.png">

**Comment by aparlato** [comment]
@natslaughter I agree with your assessment that `4: fancy-bowl` is working best overall. That said, I really like the two noodle loops in `2: two loops` and `original concept` as well as the fact you can see the separation of the chopsticks on the left side of the noodles in `original concept`. I feel those elements, mostly being able to see the separation of chopsticks in `original concept`, do a good job of clarifying this isn't some kind of lighthouse or spray (or something similar). I wonder if we can bring some of this element back into the fancy bowl icon?

**Comment by tristen** [comment]
Happened https://github.com/mapbox/maki/blob/master/icons/restaurant-noodle-15.svg
