### ISSUE TITLE
confectionary icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#406]
### confectionary icon

**use case**
For shops and factories with shops that sell confectionary items, candy, chocolate. I think it's safe to assume that all confectionary factories have shops, or that the user who is considering a confectionary factory on a map has the incentive and ability to talk factory workers into obtaining confections. So let's give factories this icon too. 

**tagging information**
Maki field = { shop: 'confectionary' }, { shop: 'candy_store' } { shop: 'chocolate' }
[OSM tag info for confectionary](https://taginfo.openstreetmap.org/search?q=confectionary#values)
[OSM tag info for chocolate](https://taginfo.openstreetmap.org/search?q=chocolate#values)

If we could identify keys that equal `amenity` or `shop`, we could add more general values such as `candy` and `chocolate`

**possible symbol**
![image](https://user-images.githubusercontent.com/16616543/38874434-09ea0abe-4226-11e8-9952-5772cf665441.png)

![image](https://user-images.githubusercontent.com/16616543/38874453-16d0314a-4226-11e8-91ae-9eb62d2bf913.png)

**Comment by natslaughter** [comment]
going with an 'ambiguous candy shape' for the symbol concept

<img width="337" alt="screen shot 2018-05-10 at 11 08 01 am" src="https://user-images.githubusercontent.com/16616543/39877084-f21078c2-5442-11e8-8682-8ddc12f9e0e9.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by natslaughter** [comment]
curious to hear what level of detail the candy should have. here are three options: 

<img width="666" alt="confectionary-draft-1" src="https://user-images.githubusercontent.com/16616543/40739278-c554aba6-6413-11e8-99c0-4c9959644301.png">

cc/ @mapbox/maps-design

**Comment by aparlato** [comment]
@natslaughter definitely in favor of the halved candy. Quartered gets too detailed and doesn't work great with a background shield and the singular candy is a bit ambiguous and may read a little like a satellite.

**Comment by eschow** [comment]
+1 for halved!

**Comment by dasulit** [comment]
@natslaughter curious if you have tried creating a candy pattern with a fill rather than a stroke! Quick pass just drawing over your last mockup:

<img width="666" alt="40739278-c554aba6-6413-11e8-99c0-4c9959644301" src="https://user-images.githubusercontent.com/8495845/42518770-9c196f50-8430-11e8-9f55-357d5acc801a.png">

**Comment by tristen** [comment]
https://github.com/mapbox/maki/pull/443
