### ISSUE TITLE
convenience store icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#407]
### convenience store icon

**use case**
For convenience stores. Convenience stores currently receive a 'grocery cart' icon, which is a bit misleading. 

**tagging information**
Maki field = { shop: 'convenience' }
[OSM tag info for convenience store](https://taginfo.openstreetmap.org/search?q=convenience#values)

**possible symbol**

![image](https://user-images.githubusercontent.com/16616543/38885808-2601f506-4242-11e8-944f-e958aeb2b97d.png)

**Comment by 1ec5** [comment]
I saw this issue right after seeing #406, so the suggested symbol above reminded me of a cupcake. 😋

**Comment by natslaughter** [comment]
going with a shopping basket for the symbol concept

<img width="328" alt="screen shot 2018-05-10 at 11 08 08 am" src="https://user-images.githubusercontent.com/16616543/39877046-d6286c6e-5442-11e8-9237-2e716a919b59.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by natslaughter** [comment]
posting draft-1 of icons

<img width="560" alt="convenience-draft-1" src="https://user-images.githubusercontent.com/16616543/40736620-8532f26e-640c-11e8-8484-4455f925db13.png">

**Comment by aparlato** [comment]
@natslaughter the refined version of this icon looks really nice! After reading @1ec5 's comment, I wonder if this does read a little too much like a cupcake. Did we try out a concept that looks more like a storefront?
<img width="30%" src="https://user-images.githubusercontent.com/15698320/42480149-d9f73c94-8390-11e8-88de-7dcdebec52b5.png"/>
Likely would become too vague at that scale, but just curious if this is something worth trying.

**Comment by tristen** [comment]
https://github.com/mapbox/maki/pull/443
