### ISSUE TITLE
bowling alley icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#413]
### bowling alley icon

**use case**
Icon to represent bowling alleys

**tagging information**
Maki field = { leisure: 'bowling_alley' }
[OSM tag info for bowling alley](https://taginfo.openstreetmap.org/search?q=bowling_alley#values)

**possible symbol concept**
Bowling ball, pin, or combination? 

![image](https://user-images.githubusercontent.com/16616543/38889346-72245ff0-424c-11e8-860f-8167942944ce.png)

![image](https://user-images.githubusercontent.com/16616543/38889353-7b74a93e-424c-11e8-8aec-352143bf4eda.png)

![image](https://user-images.githubusercontent.com/16616543/38889471-d1def6e4-424c-11e8-8b58-768d3d242b20.png)

**Comment by natslaughter** [comment]
going with a bowling ball & pin

<img width="397" alt="screen shot 2018-05-10 at 10 20 32 am" src="https://user-images.githubusercontent.com/16616543/39874713-978cbbf0-543c-11e8-951f-43fc9937affd.png">
 for the symbol concept

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by rasagy** [comment]
Took @natslaughter’s concept forward and worked on recreating the bowling pins, flipped the holes in the ball to fit well in the 11px icon and added a cut on the top of the pin with exaggerated negative space:

<img width="35" alt="screenshot 2018-06-20 20 55 48" src="https://user-images.githubusercontent.com/1117531/41774495-9fdee404-763d-11e8-8c99-03fc6cf51a56.png">

**Comment by natslaughter** [comment]
<img width="391" alt="screen shot 2018-06-25 at 10 20 18 am" src="https://user-images.githubusercontent.com/16616543/41855767-65b89d08-7861-11e8-9202-ce8c7544af4c.png">

Per chat with @rasagy the 11-pixel icon: the ball squares off when it meets the pin on non-retina screens. By shaving off some of the ball, pixels would receive a lighter grey value so the ball feels more rounded.

**Comment by rasagy** [comment]
Here’s how the trimmed edges + solid pin looks like:
<img width="34" alt="screenshot 2018-07-05 19 44 09" src="https://user-images.githubusercontent.com/1117531/42328426-d2c011ba-808b-11e8-8acf-e1179202a9d7.png">

Previous iteration for comparison:

<img width="35" alt="screenshot 2018-06-20 20 55 48" src="https://user-images.githubusercontent.com/1117531/42328330-9464779e-808b-11e8-8042-e1ee8cddd82d.png">

**Comment by natslaughter** [comment]
@rasagy after reviewing this new, 11-pixel icon iteration on a non-retina screen, I believe the new version does look more clear:
- the shaved ball does create a clear distinction between the ball and pin
- removing the pin's 'stripe,' helps in the overall pin silhouette. 

Next steps: let's test this new 11-pixel along with the 15-pixel on a map.

**Comment by natslaughter** [comment]
@rasagy I noticed that in the 15 pixel icon, the pin neck looks segregated and I wonder if it's geometry should be extended/exaggerated so that it appears more unified

<img width="171" alt="screen shot 2018-07-19 at 10 07 43 am" src="https://user-images.githubusercontent.com/16616543/42947671-d7cd67b0-8b3b-11e8-8df6-ab7d4d8e4df1.png">

**Comment by natslaughter** [comment]
Here is the 11-pixel for context. It does not include the pin stripe, so the 15 pixel icon might also want to purge it's stripe

<img width="135" alt="screen shot 2018-07-19 at 10 09 55 am" src="https://user-images.githubusercontent.com/16616543/42947761-033d96fe-8b3c-11e8-97ca-0cc2cf9c0e1a.png">

**Comment by rasagy** [comment]
@natslaughter I’ve been curious about the negative space for the holes not showing up in the map tests, and noticed that merging the shape using shape builder makes the holes barely visible in pixel preview. Is that just an Illustrator thing or expected? Wondering if exaggerating the holes would help the icon read better?

_Top: Icon merged with shape builder, Middle: Icon without merging, Bottom: Exaggerated holes._

![bowling-details](https://user-images.githubusercontent.com/1117531/43145363-d214db24-8f7c-11e8-9cde-f63cd3c17549.gif)

**Comment by tristen** [comment]
This happened https://github.com/mapbox/maki/blob/master/icons/bowling-alley-15.svg
