### ISSUE TITLE
skateboarding icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#414]
### skateboarding icon

**use case**
Icon to represent areas designated and equipped for skateboarding

**tagging information**
Maki field = { sport: 'skateboard' }
[OSM tag info for skateboard](https://taginfo.openstreetmap.org/search?q=skateboard#values)

**possible symbol concept**
an icon representing structures typically found in skateboard park design
![image](https://user-images.githubusercontent.com/16616543/38889959-1aed68e2-424e-11e8-9203-fa449d0cb3b0.png)

skateboard
![image](https://user-images.githubusercontent.com/16616543/38889998-30e32150-424e-11e8-8490-ec00c802db4d.png)

**Comment by natslaughter** [comment]
going with a skateboard for the symbol concept

<img width="392" alt="screen shot 2018-05-10 at 10 20 48 am" src="https://user-images.githubusercontent.com/16616543/39874843-f7b03462-543c-11e8-8cc4-0feee521ecfa.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by rasagy** [comment]
The icon by Nat looks great (perfectly on grid!), will push this to my WIP PR and mock it up on a map.

**Comment by rasagy** [comment]
Started adding a bit more weight to the icons, especially the 15px one:

<img width="57" alt="screenshot 2018-07-24 19 00 06" src="https://user-images.githubusercontent.com/1117531/43141573-dd92abec-8f73-11e8-9d4e-b091babd58b6.png">

**Comment by tristen** [comment]
Closing. This exists https://github.com/mapbox/maki/blob/master/icons/skateboard-11.svg
