### ISSUE TITLE
table tennis icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#415]
### table tennis icon

**use case**
Icon to represent facilities for playing ping pong

**tagging information**
Maki field = { sport: 'table_tennis' }
[OSM tag info for table tennis](https://taginfo.openstreetmap.org/search?q=table_tennis#values)

**possible symbol concept**
paddle or paddle with ball

![image](https://user-images.githubusercontent.com/16616543/38890469-7fda02b4-424f-11e8-90c3-3b48e0773fd1.png)

**Comment by rasagy** [comment]
Tweaked @natslaughter’s design and made it align slightly better on the grid:

<img width="45" alt="screenshot 2018-06-14 19 13 40" src="https://user-images.githubusercontent.com/1117531/41415851-2ad32ef4-7007-11e8-9a6b-43d565eee86b.png">

**Comment by rasagy** [comment]
Made slight improvements based on Nat’s feedback, with higher negative space in 11px paddle and more rounded handle for the 15px version:
<img width="41" alt="screenshot 2018-06-22 16 43 11" src="https://user-images.githubusercontent.com/1117531/41774000-912f3b86-763b-11e8-9616-83db6a004d42.png">

**Comment by natslaughter** [comment]
@rasagy I am now just noticing the slight mis-alignment of the 11 pixel icon, which seems to be aligned to the upper right portion of the viewBox. I'm not sure if this will need adjustment, but since we plan on mocking these icons on a map, let's make sure the 11 pixel icon appears to be center-aligned. If not, we will need to adjust the icon geometries. 

<img width="385" alt="screen shot 2018-07-13 at 9 13 25 am" src="https://user-images.githubusercontent.com/16616543/42693418-0aa97278-867d-11e8-9235-f20a90490a53.png">

**Comment by rasagy** [comment]
Thanks @natslaughter for noticing that, completely missed aligning it properly. I’ve rescaled + aligned both icons now:

<img width="43" alt="screenshot 2018-07-16 19 00 22" src="https://user-images.githubusercontent.com/1117531/42762886-1d21e4d0-892f-11e8-9d2e-0b29767ac024.png">

<img width="771" alt="screenshot 2018-07-16 19 35 45" src="https://user-images.githubusercontent.com/1117531/42763007-72e3ccb2-892f-11e8-9bda-dbaf879999a2.png">

**Comment by tristen** [comment]
Happened https://github.com/mapbox/maki/blob/master/icons/table-tennis-15.svg
