### ISSUE TITLE
volleyball icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#416]
### volleyball icon

**use case**
Icon to represent facilities for volleyball

**tagging information**
Maki field = { sport: 'volleyball' }, { sport: ‘beach_volleyball’}
[OSM tag info for volleyball](https://taginfo.openstreetmap.org/search?q=volleyball#values)
[OSM tag info for beach_volleyball](https://taginfo.openstreetmap.org/search?q=beach_volleyball#values)

**possible symbol concept**

![image](https://user-images.githubusercontent.com/16616543/38892658-e3279c40-4255-11e8-9f96-571aac9725ee.png)

**Comment by natslaughter** [comment]
going with a volleyball for the symbol concept

<img width="461" alt="screen shot 2018-05-10 at 10 21 13 am" src="https://user-images.githubusercontent.com/16616543/39874943-3d00c1d0-543d-11e8-997a-fe64f29f09f9.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by rasagy** [comment]
Tried to recreate @natslaughter’s underlying grid for the shapes (the pieces in the center ended up being thinner in mine) and made the 11px one align better on the grid.

<img width="43" alt="screenshot 2018-06-14 19 13 46" src="https://user-images.githubusercontent.com/1117531/41416023-997097c0-7007-11e8-8cee-8f9a5d469f89.png">

**Comment by rasagy** [comment]
Here’s a glimpse at the grid:

I started by trying to symmetrically divide the ball (9px) to recreate the curves for the pieces (with the help of three pairs of circles nearly twice the ball):

<img width="385" alt="screenshot 2018-06-22 16 49 22" src="https://user-images.githubusercontent.com/1117531/41774324-d674239a-763c-11e8-9188-4a2d25ecb190.png">
<img width="385" alt="screenshot 2018-06-22 16 49 59" src="https://user-images.githubusercontent.com/1117531/41774374-22cafea8-763d-11e8-82b2-f8612bbf6af2.png">


I created the icon by expanding the stroke of outer circles and using shape builder tool to merge the surface:

<img width="386" alt="screenshot 2018-06-22 16 51 05" src="https://user-images.githubusercontent.com/1117531/41774394-374a9b0e-763d-11e8-90c7-5477d074ccf6.png">

Using this grid allowed me to vary the stroke of these circles to get thinner or thicker negative space, like the last two iterations with a change in 0.25px stroke:

<img width="39" alt="screenshot 2018-06-22 16 53 27" src="https://user-images.githubusercontent.com/1117531/41774444-5d1b0b34-763d-11e8-9737-c1b7fe659132.png">
<i>(Before on top, thicker stroke on bottom)</i>

**Comment by tristen** [comment]
Done https://github.com/mapbox/maki/blob/master/icons/volleyball-15.svg
