### ISSUE TITLE
pizza restaurant icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#429]
### pizza restaurant icon

**use case**
For places that sell pizza

**tagging information**
Maki field = { cuisine: 'pizza' }
[OSM tag info](https://taginfo.openstreetmap.org/search?q=pizza#values)

**possible symbol**
A slice of pizza

![image](https://user-images.githubusercontent.com/16616543/38900277-e1f2bb94-4268-11e8-9c43-a7ed0c257203.png)

**Comment by natslaughter** [comment]
going with a slice of jalapeño and pineapple pizza for the symbol concept

<img width="275" alt="screen shot 2018-05-10 at 11 08 18 am" src="https://user-images.githubusercontent.com/16616543/39876950-9871d8c4-5442-11e8-883b-eacfbc0bbbf5.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by natslaughter** [comment]
<img width="662" alt="restaurant-pizza-draft-1" src="https://user-images.githubusercontent.com/16616543/40747311-e3cf4e6c-642a-11e8-8fea-f123f38891a9.png">

**Comment by aparlato** [comment]
@natslaughter lgtm! 🍕 Draft 2 of 11px is :+1: 🍕

**Comment by tristen** [comment]
https://github.com/mapbox/maki/pull/443
