### ISSUE TITLE
maki icon design tracker

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#431]
This ticket is for tracking the progress of several icons being designed at the same time

| maki icon | symbol concept approved* | completed | 
| -- | -- | -- | 
| [casino](https://github.com/mapbox/maki/issues/376) | ✅  |  ✅  |
| [car-rental](https://github.com/mapbox/maki/issues/404) | ✅  |  ✅   |
| [restaurant-noodle](https://github.com/mapbox/maki/issues/405) | ✅   |  ✅   |
| [restaurant-pizza](https://github.com/mapbox/maki/issues/429) | ✅   |  ✅   |
| [restaurant-seafood](https://github.com/mapbox/maki/issues/430) | ✅   |  ✅   |
| [confectionary](https://github.com/mapbox/maki/issues/406) | ✅   |  ✅   |
| [convenience](https://github.com/mapbox/maki/issues/407) | ✅   |  ✅   |
| [bridge](https://github.com/mapbox/maki/pull/369) | ✅   |  ✅   |
| [communications-tower](https://github.com/mapbox/maki/issues/257) | ✅   |  ✅   |
| [watermill](https://github.com/mapbox/maki/issues/408) | ✅  |  ✅   |
| [windmill](https://github.com/mapbox/maki/issues/409) | ✅  |  ✅   |
| [car-repair](https://github.com/mapbox/maki/issues/410) | ✅  |  ✅   |
| [charging-station](https://github.com/mapbox/maki/pull/371) | ✅  |  ✅   |
| [playground](https://github.com/mapbox/maki/issues/428) | ✅  |  ✅   |
| [basketball](https://github.com/mapbox/maki/issues/424) |  ✅  |  ✅   |
| [beach](https://github.com/mapbox/maki/issues/411) |  ✅  |  ✅   |
| [bowling-alley](https://github.com/mapbox/maki/issues/413) | ✅ |  ✅   |
| [fitness-centre](https://github.com/mapbox/maki/issues/402) |  ✅  |  ✅   |
| [skateboard](https://github.com/mapbox/maki/issues/414) | ✅  |  ✅   |
| [slipway](https://github.com/mapbox/maki/issues/58) |  ✅  |  ✅   |
| [table-tennis](https://github.com/mapbox/maki/issues/415) |  ✅  |  ✅   |
| [tennis](https://github.com/mapbox/maki/issues/427) |  ✅  |  ✅   |
| [viewpoint](https://github.com/mapbox/maki/pull/392) | ✅  |  ✅   |
| [volleyball](https://github.com/mapbox/maki/issues/416) | ✅  |  ✅   |
| [furniture](https://github.com/mapbox/maki/issues/417) | ✅   |  ✅   |
| [hardware](https://github.com/mapbox/maki/issues/418) | ✅   |  ✅   |
| [globe](https://github.com/mapbox/maki/issues/419) | ✅   |  ✅   |
| [jewelry-store](https://github.com/mapbox/maki/issues/420) | ✅   |  ✅   |
| [optician](https://github.com/mapbox/maki/issues/421) | ✅   |  ✅   |
| [shoe](https://github.com/mapbox/maki/issues/422) | ✅   |  ✅   |
| [watch](https://github.com/mapbox/maki/issues/423) | ✅   |  ✅   |
| [waterfall](https://github.com/mapbox/maki/pull/373) | ✅  |  ✅  |
| [ranger-station](https://github.com/mapbox/maki/issues/432) | ✅  |  ✅   |

_*green check here ensures the symbol will work at Maki scale, and is globally recognizable enough to use_

**Comment by tristen** [comment]
Closing as stale
