### ISSUE TITLE
Halo in icon-editor

### ISSUE THREAD

**Issue by tomass** [mapbox/maki#439]
Currently it is only possible to add _circle_ or _rectangle_ background for icons in maki icon editor.
When creating some maps (for example topographic maps), no background is required for symbols. But as icons could be placed on a background of any colour, a halo would be required. Like here for church and tower symbols:
![paveikslas](https://user-images.githubusercontent.com/969513/42757385-8a75b3d0-8908-11e8-8f8f-10eb45fbf756.png)
It is (currently?) not possible in _mapbox-gl-js_ to add a halo to a svg icon in map style. The only way I found is to have halo directly in sprite file. It is possible to do that with external image editor (like Gimp), but it takes additional time and you have to repeat it after any change to the sprite. Sometimes not all symbols in a sprite need a halo which makes automated sprite editing hard or impossible.
It would be good to have a possibility to create a "halo" alongside "circle" and "rectangle" background directly in icon editor.

**Comment by natslaughter** [comment]
@tomass thank you for your interest in Maki. 
Mapbox gl-js does not yet support vector icons, so I would recommend using the [Maki icon editor](https://www.mapbox.com/maki-icons/editor/) to create 'halos' for .svg icons. You can 'enable stroke' and edit the color and pixel width of your icon 'halo.'

<img width="848" alt="screen shot 2018-07-16 at 9 07 24 am" src="https://user-images.githubusercontent.com/16616543/42760627-0d826352-88d9-11e8-8a7a-aaae4a2ab7d4.png">

**Comment by tomass** [comment]
Thank you, it works as needed:
![paveikslas](https://user-images.githubusercontent.com/969513/42761451-4237deb4-8916-11e8-9701-64c2d509d8fa.png)
Don't know how could I have missed this.
