### ISSUE TITLE
[animals from farm] icons

### ISSUE THREAD

**Issue by fabrice-regnier** [mapbox/maki#442]
Hello,

First, thank you for this pool of nice icons.

I'm looking for some animals from farm icons such as:
* cow
* pig
* horse
* chicken
* goat
* sheep
*...

The aim of this icons is to show on an OSM map, the farms production of any area.

regards,

f.

**Comment by tristen** [comment]
Closing this. Icons included in the Maki should represent places in the world. Different farm animals fall outside of that guideline.
