### ISSUE TITLE
icon Helsinki Metro

### ISSUE THREAD

**Issue by obb12** [mapbox/maki#456]
Hello!
Can the helsinki metro logo added to the iconset?

**Comment by dasulit** [comment]
Hey @obb12! Maki icons are meant to be generic, point-of-interest icons, so regional metro icons aren't a good fit for this icon set.

[Mapbox Streets](https://www.mapbox.com/maps/streets/) comes with some metro icons, but it does not include Helsinki. I would suggest looking there for inspiration— perhaps you could recolor the Washington DC Metro icon, which looks quite similar.
