### ISSUE TITLE
dirname no longer exported yet its used in the "For developers" example

### ISSUE THREAD

**Issue by nreese** [mapbox/maki#461]
The [For developers](https://github.com/mapbox/maki#for-developers) section lists an example that uses `maki.dirname`. See below.

```
var maki = require('@mapbox/maki');

files.forEach(function(fileName, j) {
  maki.layouts.all.forEach(function(icon) {
    fs.readFile(maki.dirname + '/icons/' + icon + '-11.svg', 'utf8', function(err, file) {
      // Read icons as strings in node
      console.log(file);
    });
  });
});
```

`maki.dirname` was removed in this commit https://github.com/mapbox/maki/commit/20dffa42caea08c9c3244612632dc1849d558c6b#diff-168726dbe96b3ce427e7fedce31bb0bc.

The example needs to be updated.

**Comment by tristen** [comment]
See https://github.com/mapbox/maki/pull/457 which resolves documentation.

**Comment by nreese** [comment]
#457 does not resolve the issue. The example still uses `maki.dirname`. `maki` no longer contains a value for `dirname`.

**Comment by tristen** [comment]
Apologies. Can address this in that PR.

**Comment by tristen** [comment]
Will be addressed in the next version (changes appear in the `main` branch)
