### ISSUE TITLE
Allow npm @mapbox/maki artifact to be used in browser

### ISSUE THREAD

**Issue by nreese** [mapbox/maki#462]
npm `@mapbox/maki` can not be used in the browser because [gather-files](https://github.com/mapbox/maki/blob/master/scripts/gather-files.js) script uses `readdirSync` to gather the SVGs.

Would it be possible to add a build phase so that the scripts are already gathered and placed into a dist folder so that the npm artifact could be used in the browser?

**Comment by tristen** [comment]
Unassigning myself to this older issue but would welcome a PR for this change!

**Comment by mbullington** [comment]
Played around with this to get test data for you-know-what (or maybe you don't if you're not @tristen) and making a browser bundle is pretty easy.

```js
import maki from '@mapbox/maki';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

writeFileSync(resolve(process.cwd(), 'maki.json'), JSON.stringify(maki));
```

Maybe we should add this to the the build step and specify the output file in "browser" of `package.json`?

**Comment by tristen** [comment]
Closed by https://github.com/mapbox/maki/pull/556!
