### ISSUE TITLE
Alternative localized Maki set

### ISSUE THREAD

**Issue by tristen** [mapbox/maki#467]
Japan has [standard symbols](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols) (called _chizukigou_) to represent things in the world. An alternative localized set would serve as a counterpart to Maki icons where - if you are in Japan - they are used in place of the standard version.

Here's a quick list of localized versions to Japan we could start with:

Maki | Japanese version | Reference |
-- | -- | -- |
`bank` | `bank-JP` | [link](http://goinjapanesque.com/wpos/wp-content/uploads/2016/01/Japanese-map-symbols19.png) |
`castle` | `castle-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Castle).svg) |
`fire-station` | `fire-station-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Fire_station).svg) |
`landmark` | `landmark-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Historical_site-Place_of_scenic_beauty-Natural_monument-Protected_animal_plant).svg) |
`hospital` | `hospital-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Historical_site-Place_of_scenic_beauty-Natural_monument-Protected_animal_plant).svg) |
`police` | `police-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Police_station).svg) |
`post` | `post-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Post_office).svg) |
`school` | `school-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Elementary_or_Junior_high_school).svg) |
`religious-buddist` | `religious-buddist-JP` | |
`cemetery` | `cemetery-JP` | [link](https://en.wikipedia.org/wiki/List_of_Japanese_map_symbols#/media/File:Japanese_Map_symbol_(Graveyard).svg) |

**Comment by lily-chai** [comment]
@tristen `shrine` is changed to `religious-shinto` in https://github.com/mapbox/maki/issues/470#issuecomment-512695642. Will `religious-shinto` have both a regular maki version and a `-JP` Japanese version?

**Comment by tristen** [comment]
> Will `religious-shinto` have both a regular maki version and a `-JP` Japanese version?

@lily-chai Good question. Good question: it will not. The regular Maki version should visually match any `-JP` version so there's no need to add value for it.
