### ISSUE TITLE
Racetrack types

### ISSUE THREAD

**Issue by tristen** [mapbox/maki#471]
Racetracks combined with a [sports tag](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtrack#Sports)

- Generic `racetrack`
- Cycling `racetrack-cycling`
- Horse `racetrack-horse`
- Boat `racetrack-boat`

---

Ref https://github.com/mapbox/maki/issues/212

**Comment by willymaps** [comment]
Include generic `racetrack`.

Related: https://github.com/mapbox/maki/issues/212

**Comment by tristen** [comment]
Done in 

- https://github.com/mapbox/maki/pull/552
- https://github.com/mapbox/maki/pull/551
- https://github.com/mapbox/maki/pull/550
- https://github.com/mapbox/maki/pull/549
