### ISSUE TITLE
top-down-ship icon

### ISSUE THREAD

**Issue by nreese** [mapbox/maki#472]
[Kibana](https://github.com/elastic/kibana) is using Maki icons to show data points in a map. For example, GPS tracks showing current location of ships. We would like to have a ship icon that can show direction when rotated. We believe the best icon for this would be a top down ship icon and would like to contribute such an icon to Maki. 

Would Maki be interested in a couple of additional icons that are better for showing data points and direction? Other icons we have in mind would be an arrow icon, a top down vehicle icon, and maybe top down footprints icon.

#### Icon Request
- [x] Make the issue title: "[icon name] icon." E.g. "garden icon" or "place-of-worship icon"
- [x] Describe any specific use cases that prompted the request.
- [ ] If applicable, please share an [OpenStreetMap tag(s)](http://taginfo.openstreetmap.org/keys) tag(s) link. The OSM usage will help determine what icon concept to use.
- [ ] Please suggest any icon concepts that might be helpful, along with reference images.

**Comment by tristen** [comment]
> Would Maki be interested in a couple of additional icons that are better for showing data points and direction?

Hey @nreese thanks for your interest in Maki! icons that are designed to be displayed in different positions sound slightly out of scope for the project. That said, I could definitely see an arrow icon included as well as footprints if there's an associated OSM tag you would relate it to.

**Comment by nreese** [comment]
> icons that are designed to be displayed in different positions sound slightly out of scope for the project. That said, I could definitely see an arrow icon included as well as footprints

Does this mean Maki would be interested in a top down ship? Or just the other icon ideas?

**Comment by tristen** [comment]
I think a "top down ship" is out of scope for the project. A generic "boat" icon would be a better fit but there would be no guarantee that it would be designed to be viewed top down.

**Comment by ryankeairns** [comment]
These are rough sketches of what we have in mind, next I'll look up some potential tags. I had started down the boat path prior to your last comment :) , but perhaps this icon follows a similar use case as the `airport` or `airfield` icons (e.g. marina).

<img width="42" alt="Screenshot 2019-06-26 09 24 38" src="https://user-images.githubusercontent.com/446285/60188024-3c3dac80-97f4-11e9-82c3-7f568bd3257e.png">

**Comment by ryankeairns** [comment]
Marina: https://taginfo.openstreetmap.org/tags/leisure=marina

**Comment by tristen** [comment]
Both [`ferry`](https://github.com/mapbox/maki/blob/master/icons/ferry-15.svg) and [`harbor`](https://github.com/mapbox/maki/blob/master/icons/harbor-15.svg) exist. I think we're covered there. 

There are a [number](https://github.com/mapbox/maki/blob/master/icons/circle-15.svg) [of](https://github.com/mapbox/maki/blob/master/icons/circle-stroked-15.svg) [generic](https://github.com/mapbox/maki/blob/master/icons/triangle-15.svg) [icons](https://github.com/mapbox/maki/blob/master/icons/triangle-stroked-15.svg) that don't need an associated tag! I think `arrow` falls within this generic category.

**Comment by tristen** [comment]
Closing as stale.
