### ISSUE TITLE
Rename `sushi` to `restaurant-sushi`

### ISSUE THREAD

**Issue by lily-chai** [mapbox/maki#474]
All maki icons for food places currently have the prefix `restaurant-` (e.g. `restaurant-seafood`, `restaurant-noodle`, [`restaurant-bbq`](https://github.com/mapbox/maki/issues/468). Should `sushi` be rename to `restaurant-sushi` for consistency?

cc @tristen

**Comment by willymaps** [comment]
Added to https://github.com/mapbox/maki/tree/main
