### ISSUE TITLE
Map icon suggestions

### ISSUE THREAD

**Issue by MwithHook** [mapbox/maki#483]
Hi, as noted [here](https://www.mediawiki.org/wiki/Help_talk:Extension:Kartographer/Icons) there are a few things that bug me!

- [ ] The school icon should resemble [common school icons](https://www.google.com/search?q=school+icon&bih=795&biw=1600&rlz=1C1ASRM_enUS733US733&hl=en&sxsrf=ALeKk00lFocs1LchQbkiEV_Q95otoDZajQ:1582157950643&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj8joHV7d7nAhXO854KHV1-CbwQ_AUoAXoECA4QAw) (more easily identifiable)
- [ ] The church icon should resemble [common church icons](https://www.google.com/search?q=church+icon&bih=795&biw=1600&rlz=1C1ASRM_enUS733US733&hl=en&sxsrf=ALeKk00xR5xFZvGA6rv_GHbwQVNlQEP0tw:1582157760284&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiFzp767N7nAhXBuZ4KHRsLDdIQ_AUoAXoECA4QAw) (more easily identifiable)
- [ ] The synagogue icon should resemble [common synagogue icons](https://www.google.com/search?q=synagogue+icon&bih=795&biw=1600&rlz=1C1ASRM_enUS733US733&hl=en&sxsrf=ALeKk02kMmnhCL6SYivOTMdxoIr7kXrA3Q:1582157894620&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjs7KW67d7nAhUT7J4KHf-hCwMQ_AUoAXoECAwQAw) (more easily identifiable)
- [x] The library icon would look better if it incorporated a building and a book/books, see [two of these](https://www.google.com/search?q=library+icon&bih=795&biw=1600&rlz=1C1ASRM_enUS733US733&hl=en&sxsrf=ALeKk01RkS3pB9Y6oEM9v-bLW2UARKZ57g:1582158027253&source=lnms&tbm=isch&sa=X&ved=2ahUKEwienMX57d7nAhUCoZ4KHdu0AhcQ_AUoAXoECA4QAw)
- [ ] I suppose all the missing icons on Wikimedia are here, including 'fire station', but that shouldn't look like an ongoing fire on a map, like the symbol used for wildfires in California, etc.
- [ ] An icon for 'train station' would be immensely useful more than many of these on Wikipedia, the rail icon isn't too clear for that. I'd recommend [something like this](https://cdn0.iconfinder.com/data/icons/transportation-and-logistics/50/Transportation_and_Logistics-60-512.png).

Thanks for your help and support, please let me know what is possible. I use these icons a lot in maps all over Wikimedia projects, so your work is really appreciated.

**Comment by MwithHook** [comment]
Also really needs a law/justice/courthouse icon.

**Comment by tristen** [comment]
> Also really needs a law/justice/courthouse icon.

Tracking in https://github.com/mapbox/maki/issues/53

> * An icon for 'train station' would be immensely useful more than many of these on Wikipedia, the rail icon isn't too clear for that. I'd recommend [something like this](https://cdn0.iconfinder.com/data/icons/transportation-and-logistics/50/Transportation_and_Logistics-60-512.png).

If you'd like to see `train-station` as a new Maki icon, please cut a separate ticket for that request.

>  The school icon should resemble common school icons (more easily identifiable)

Tracking in https://github.com/mapbox/maki/issues/434

---

The points you've added here are subjective. What helps us as project maintainers are tickets per icons (or better a PR with proposed changes) and we can debate If it makes sense. Closing this ticket on the basis of being broad.
