### ISSUE TITLE
Arrow

### ISSUE THREAD

**Issue by kelsey-taylor** [mapbox/maki#484]
An `arrow` icon for indicating direction of a building exit

**Comment by kelsey-taylor** [comment]
These icons were pretty straightforward:
![image](https://user-images.githubusercontent.com/57634568/83924845-99a3e280-a753-11ea-9461-10b21951411b.png)

Actual size:
![image](https://user-images.githubusercontent.com/57634568/83924800-7d07aa80-a753-11ea-8529-c280589767b2.png)

Any initial thoughts from these screenshots @tristen? I have the SVGs formatted and ready for a PR if reviewing that way is easier.

**Comment by tristen** [comment]
>  I have the SVGs formatted and ready for a PR if reviewing that way is easier.

Oh yes! That would be helpful.

**Comment by kelsey-taylor** [comment]
closed via https://github.com/mapbox/maki/pull/495
