### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by kelsey-taylor** [mapbox/maki#486]
### Icon Request
An `Elevator` icon

Initial thoughts:
- arrows on either side (or on top) to indicate up/down directionality

**Comment by todrobbins** [comment]
![](https://raw.githubusercontent.com/ideditor/temaki/master/icons/elevator.svg) [temaki-elevator](https://ideditor.github.io/temaki/docs/#icon-temaki-elevator)

**Comment by willymaps** [comment]
Closed: https://github.com/mapbox/maki/pull/536
