### ISSUE TITLE
Icon Wishlist

### ISSUE THREAD

**Issue by wboykinm** [mapbox/maki#49]
I definitely trend toward looking for illustrations of abstract concepts in 24 pixels. Here are a few of them with which I've been struggling to adapt existing Maki icons:
- Human population (I actually altered the svg of the runner to make a waving person, but man [is it ugly](http://www.flickr.com/photos/vtcraghead/8497407259/))
- Government Transparency
- Government Regulation (Which I ideologically approve of :)
- Climate Change
- Agriculture (sheaf of wheat or other specific crop)
- Farm

**Comment by samanpwbb** [comment]
We have farm, the other icons don't meet the "represent common places or things in the world" criteria.

**Comment by wboykinm** [comment]
Whoa, @samanpwbb - this is some serious archival stuff in here. Gov. regulation? WTH was I even working on?
