### ISSUE TITLE
I NEED chocolate ICON!!!  

### ISSUE THREAD

**Issue by kimseunghwa102** [mapbox/maki#497]
#### Icon Request
- [ ] Make the issue title: "[icon name] icon." E.g. "garden icon" or "place-of-worship icon"
- [ ] Describe any specific use cases that prompted the request.
- [ ] If applicable, please share an [OpenStreetMap tag(s)](http://taginfo.openstreetmap.org/keys) tag(s) link. The OSM usage will help determine what icon concept to use.
- [ ] Please suggest any icon concepts that might be helpful, along with reference images.

**Comment by tristen** [comment]
Closing as not actionable. If you would like to reopen this, please fill out the necessary details under "Icon request"
