### ISSUE TITLE
chocolate icon

### ISSUE THREAD

**Issue by kimseunghwa102** [mapbox/maki#498]
#### Icon Request
- [x] Make the issue title: "[icon name] icon." E.g. "garden icon" or "place-of-worship icon"
- [x] Describe any specific use cases that prompted the request.
- [x] If applicable, please share an [OpenStreetMap tag(s)](http://taginfo.openstreetmap.org/keys) tag(s) link. The OSM usage will help determine what icon concept to use.
- [x] Please suggest any icon concepts that might be helpful, along with reference images.

**Comment by kimseunghwa102** [comment]
Icon Request

**Comment by bhousel** [comment]
@tristen It might be useful in the readme to steer people towards https://github.com/ideditor/temaki if they want more icons.  
We've already drawn most of the common stuff people are mapping in OSM (including chocolate).

**Comment by tristen** [comment]
@bhousel I think we could consider an icon like this if I understood the intent around the request! I could have left the same response the [last time this was requested yesterday](https://github.com/mapbox/maki/issues/497#issuecomment-661938733)

**Comment by bhousel** [comment]
@tristen for sure, I'm just thinking it might cut down on the chatter if people knew about alternatives (temaki, font awesome, noun project, etc).

If there isn't a straightforward way to get the other icons onto people's maps, maybe I can help?

**Comment by tristen** [comment]
Ah! I see. and oh yeah! totally down with including https://github.com/ideditor/temaki in the readme. A pr for that would be happily accepted.
