### ISSUE TITLE
Toll booth icon

### ISSUE THREAD

**Issue by avi-c** [mapbox/maki#500]
Nav SDK team needs an icon for "tool booth" to place on a map as part of the Road Alerts feature. I believe these are tagged as "toll" in OSM: https://taginfo.openstreetmap.org/keys/toll

I would suggest something like coins/money going into a basket or perhaps a tollbooth with a human operator in it

**Comment by segheysens** [comment]
I think a maki icon similar to this could work and fit with the maki style: https://icons8.com/icons/set/toll
![image](https://user-images.githubusercontent.com/3592134/96059054-e8c4f700-0e5a-11eb-87d7-c7313074b205.png)

**Comment by avi-c** [comment]
I'm kind of partial to this style, but it might be too retro:

[Toll Booth Sign.pdf](https://github.com/mapbox/maki/files/5388300/Toll.Booth.Sign.pdf)

**Comment by avi-c** [comment]
Is there an ETA for getting something made? I can also try out using just the local currency symbol inside a circle or square shape.

**Comment by vknoppkewetzel** [comment]
Hola! @avi-c this currently isn't a priority for our team at the moment based on other work, but can you clarify the timeline when you / your team needs this? We can work on re-prioritizing if it is needed ASAP

**Comment by avi-c** [comment]
@asinghal22 to comment on priority
