### ISSUE TITLE
Update museum and town-hall icon

### ISSUE THREAD

**Issue by vknoppkewetzel** [mapbox/maki#505]
Improve museum icon by making it more global-friendly

inspo:
 ![Screen Shot 2021-01-19 at 3 58 42 PM](https://user-images.githubusercontent.com/7087091/109219498-b1117880-7785-11eb-9384-b44c50f0074d.png) 
 
 Our `museum` icon features an `M` , so creating a more global version is helpful for all geographies

**Comment by tristen** [comment]
👋 Should we just be replacing https://github.com/mapbox/maki/blob/master/icons/museum-15.svg? This symbology doesn't stand out to me as being different from what should be used globally.

**Comment by vknoppkewetzel** [comment]
@tristen yeah! Happy to replace current icon to make it more friendly globally ✨

**Comment by tristen** [comment]
> @tristen yeah! Happy to replace current icon to make it more friendly globally ✨

🤔 I'm a little concerned it bears a pretty close resemblance to https://github.com/mapbox/maki/blob/master/icons/town-hall-15.svg

**Comment by vknoppkewetzel** [comment]
@tristen yes, the townhouse icon looks a lot like the JP icon. The plan was to adjust the townhouse icon and make it look hopefully different enough and still indicative of Museum, while also removing the `M`. 

Then, -JP would have the icon sans `M` when calling the museum attribute and adding the -JP maki modifier. 

But goal adjustment-wise, updating the `museum` icon to be visually different than `townhouse` while still not having the `M` hopefully is attainable. 

I do like the idea of removing the `M` so that countries that don't refer to a museum with a word that starts with `M` have more of a connection to the museum icon.

definitely agree that it is a design challenge.

**Comment by vknoppkewetzel** [comment]
Could also be that while redesigning the museum icon, a redesign of townhall can be considered.

**Comment by vknoppkewetzel** [comment]
hrmm Not all museums look like the way we depict them with the roman architecture that inspired our Museum and Townhouse icons.

So maybe in a similar vein, we can consider what people commonly associate museums with. Art. Statues. Paintings. dinosaur skeletons.

Maybe something like the following could be a a good redesign for a museum icon @tristen:
![Screen Shot 2021-02-26 at 2 41 30 PM](https://user-images.githubusercontent.com/7087091/109347179-bf709a80-7840-11eb-8302-98893143e8e1.png)  ![Screen Shot 2021-02-26 at 2 45 40 PM](https://user-images.githubusercontent.com/7087091/109347557-54739380-7841-11eb-839e-6725cf8809b7.png)

or like, "roman pedestal used to showcase statues/pottery":
![Screen Shot 2021-02-26 at 2 42 07 PM](https://user-images.githubusercontent.com/7087091/109347265-e3cc7700-7840-11eb-877f-d9c14d1d3bdf.png)  ![Screen Shot 2021-02-26 at 2 42 54 PM](https://user-images.githubusercontent.com/7087091/109347301-f0e96600-7840-11eb-89ba-de13bdbe1f47.png)

or maybe a roman / greek vase:
![Screen Shot 2021-02-26 at 2 44 12 PM](https://user-images.githubusercontent.com/7087091/109347418-268e4f00-7841-11eb-97dc-df6a11287601.png)

vase / pedastal?
![Screen Shot 2021-02-26 at 2 44 56 PM](https://user-images.githubusercontent.com/7087091/109347483-3dcd3c80-7841-11eb-9486-ca4f114128e8.png)

I think the above could be good alternative associations for museums, I can test some out and see if they look good, get some feedback on that as well. Thoughts?

**Comment by vknoppkewetzel** [comment]
I'm circling back to this. The above are great museum options, but changing my thought process to retain original intent of having this work with -JP local recognition. I think updating the townhall icon to look different than it currently does, and then we can update the museum icon by just removing the`M`.

**Comment by vknoppkewetzel** [comment]
I'm circling back to this. The above are great museum options, but changing my thought process to retain original intent of having this work with -JP local recognition. I think updating the townhall icon to look different than it currently does, and then we can update the museum icon by just removing the`M`. Will work on creating a "flatter" option that has that "bell tower" and push up a PR for review for townhall icon, to see if that is a good solution for this ticket!
inspo icons:
<img width="40" alt="Screen Shot 2021-03-02 at 11 12 15 AM" src="https://user-images.githubusercontent.com/7087091/109677984-30b59380-7b48-11eb-9ae3-fcea5ba475a1.png"> <img width="40" alt="Screen Shot 2021-03-02 at 11 13 27 AM" src="https://user-images.githubusercontent.com/7087091/109678154-5a6eba80-7b48-11eb-9319-ed1a5554281d.png"><img width="40" alt="Screen Shot 2021-03-02 at 11 21 16 AM" src="https://user-images.githubusercontent.com/7087091/109679304-745ccd00-7b49-11eb-90b3-599d765d3e7a.png">

inspo buildings:
<img width="259" alt="Screen Shot 2021-03-02 at 11 12 53 AM" src="https://user-images.githubusercontent.com/7087091/109678077-46c35400-7b48-11eb-8b20-e6906c3a8af2.png">
<img width="261" alt="Screen Shot 2021-03-02 at 11 14 06 AM" src="https://user-images.githubusercontent.com/7087091/109678302-7b371000-7b48-11eb-8742-fad9f9342d20.png">
