### ISSUE TITLE
localized monument

### ISSUE THREAD

**Issue by vknoppkewetzel** [mapbox/maki#506]
inspo:
![Screen Shot 2021-01-19 at 4 15 29 PM](https://user-images.githubusercontent.com/7087091/109219907-3dbc3680-7786-11eb-871e-aac7b0e7d0b7.png) 

improve localization via creation of `monument-JP`

**Comment by vknoppkewetzel** [comment]
I believe the monument icon is still relevant in that GSI recently added a [`natural disaster monument` symbol/icon](https://www.gsi.go.jp/KIDS/map-sign-tizukigou-h05-01-19hakubutukan_00001.htm) in [2019](https://www.gsi.go.jp/kokusaikoryu/kokusaikoryu-e31026.html) that utilizes the base `monument` symbol/icon, and this icon was the first added i[n 13 years](https://soranews24.com/2019/03/18/japan-to-add-first-new-symbol-to-map-in-13-years-can-you-guess-what-it-means/) which seems significant

Given that `monument` is the base design for the above, it seems appropriate and okay to include this symbol into maki

**Comment by vknoppkewetzel** [comment]
👋 @tristen would you mind taking a look at this PR this week? also can reassign!

**Comment by tristen** [comment]
@vknoppkewetzel can you use the new pull request template for this? https://github.com/mapbox/maki/blob/master/.github/pull_request_template.md
