### ISSUE TITLE
localized lighthouse

### ISSUE THREAD

**Issue by vknoppkewetzel** [mapbox/maki#507]
create localized lighthouse icon for Japan 

inspo 
 ![Screen Shot 2021-01-19 at 4 15 56 PM](https://user-images.githubusercontent.com/7087091/109219964-4f054300-7786-11eb-8fdc-5cafb1f4539d.png)

**Comment by vknoppkewetzel** [comment]
👋 @tristen would you mind taking a look at this PR this week? also can reassign!

**Comment by tristen** [comment]
@vknoppkewetzel can you use the new pull request template for this? https://github.com/mapbox/maki/blob/master/.github/pull_request_template.md
