### ISSUE TITLE
Historic

### ISSUE THREAD

**Issue by tristen** [mapbox/maki#561]
We don't have an icon to represent historical sites so a [response like this](https://twitter.com/SarraK_/status/1486835152097533953?t=XVF0GkrzrhKgZ888ka9i8A&s=19) is not surprising when a default marker is shown for a plaque that says:

> Hostage taking January 9, 2015

<img width="290" alt="Screen Shot 2022-02-01 at 9 46 01 AM" src="https://user-images.githubusercontent.com/61150/151990185-c12b7c72-4a1c-4fcb-99ca-2c761bcb346a.png">

- **OSM Tag** https://taginfo.openstreetmap.org/keys/historic
- **Icon suggestion** Historic sites are often represented in the real world with a [sign](https://en.wikipedia.org/wiki/File:Archaeological_and_Historic_Sites_Board_of_Ontario_sign_-_Le_Griffon.jpg)

**Comment by Udobnyj** [comment]
I apologize for delaying the task. I wanted to do it last week. 
So, I'm still just trying to fit in the actual Maki style. So quickly sketched out some options, three seem to be the best. My fav is the third option.

![1.1.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/47833cf6-ae4c-44f3-91e1-ddd6291ae482)

![2.1.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/b4c25cce-3d5f-4d98-b7bd-bf989991d37e)

![3.1.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/40ef348b-eb1c-4651-8ae9-9c72f5c3fe88)

**Comment by tristen** [comment]
@Udobnyj Agree! 3 looks strong

**Comment by Udobnyj** [comment]
@tristen Thank you so much!
